# Generated by Django 4.2.28 on 2026-08-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TchapCredential",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        max_length=255, verbose_name="Identifiant utilisateur Matrix"
                    ),
                ),
                (
                    "device_id",
                    models.CharField(max_length=255, verbose_name="Device ID"),
                ),
                (
                    "access_token",
                    models.CharField(max_length=2048, verbose_name="Access token"),
                ),
                (
                    "crypto_store",
                    models.BinaryField(
                        blank=True,
                        null=True,
                        verbose_name="Crypto store nio (SQLite file)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Identifiants Tchap",
                "verbose_name_plural": "Identifiants Tchap",
            },
        ),
    ]
