services:
  django:
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.ci-guh
      - POSTGRES_DB=${POSTGRES_DB:-envergo}
    env_file:
      - ./envs/django
      - ./envs/postgres

  postgres:
    env_file:
      - ./envs/postgres
