# Generated by Django 4.2 on 2023-04-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                ("order", models.IntegerField(default=100, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Stat",
                "verbose_name_plural": "Stats",
                "ordering": ["order"],
            },
        ),
    ]
