# Generated by Django 4.2 on 2024-04-30 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Stat",
        ),
    ]
