# Generated by Django 3.2.6 on 2021-12-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='order',
            field=models.IntegerField(default=100, verbose_name='Order'),
        ),
    ]
