# Generated by Django 3.2.11 on 2022-01-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_stat_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stat",
            options={
                "ordering": ["order"],
                "verbose_name": "Stat",
                "verbose_name_plural": "Stats",
            },
        ),
    ]
