# Generated by Django 3.2.6 on 2021-08-26 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='^[\\d]{5}$')], verbose_name='Commune INSEE code')),
                ('section', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(regex='^[0A-Z][A-Z]$')], verbose_name='Section letter(s)')),
                ('prefix', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(regex='^[\\d]{3}$')], verbose_name='Prefix')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Parcel',
                'verbose_name_plural': 'Parcels',
                'unique_together': {('commune', 'section', 'prefix', 'order')},
            },
        ),
    ]
