# Generated by Django 3.2.6 on 2021-09-03 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_auto_20210827_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='section',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='The section must be one (zero-prefixed) or two uppercase letters.', regex='^[0A-Z][A-Z]$')], verbose_name='Section letter(s)'),
        ),
    ]
