# Generated by Django 4.2 on 2023-06-16 12:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0002_map_imported_zones"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="geometry",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                geography=True, null=True, srid=4326, verbose_name="Simplified geometry"
            ),
        ),
    ]
