# Generated by Django 3.2.6 on 2021-09-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0003_alter_parcel_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parcel',
            unique_together=set(),
        ),
    ]
