# Generated by Django 4.2 on 2023-07-18 14:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0003_map_geometry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="geometry",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                geography=True,
                help_text="DO NOT EDIT! We cannot easily deactivate this edition widget,\n            but if you use it, you will break EnvErgo.\n            ",
                null=True,
                srid=4326,
                verbose_name="Simplified geometry",
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="geometry",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                geography=True,
                help_text="DO NOT EDIT! We cannot easily deactivate this edition widget,\n            but if you use it, you will break EnvErgo.\n            ",
                srid=4326,
            ),
        ),
    ]
