# Generated by Django 4.2 on 2023-07-20 08:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0004_alter_map_geometry_alter_zone_geometry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="map",
            options={
                "ordering": ["name"],
                "verbose_name": "Map",
                "verbose_name_plural": "Maps",
            },
        ),
        migrations.AlterField(
            model_name="map",
            name="geometry",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True,
                geography=True,
                help_text="DO NOT EDIT! We cannot easily deactivate this edition widget,\n            but if you use it, you will break EnvErgo.\n            ",
                null=True,
                srid=4326,
                verbose_name="Simplified geometry",
            ),
        ),
    ]
