# Generated by Django 3.2.6 on 2021-11-04 10:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0006_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
