# Generated by Django 4.2 on 2023-07-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0006_zone_area_zone_npoints_alter_department_department_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(fields=["-area"], name="geodata_zon_area_68e970_idx"),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(
                fields=["-npoints"], name="geodata_zon_npoints_f95816_idx"
            ),
        ),
    ]
