# Generated by Django 4.2 on 2024-01-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0007_zone_geodata_zon_area_68e970_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="import_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Import date"
            ),
        ),
    ]
