# Generated by Django 4.2 on 2024-01-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0008_map_import_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="import_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Latest status date"
            ),
        ),
    ]
