# Generated by Django 4.2 on 2024-02-20 09:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0010_catchmentareatile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catchmentareatile",
            name="data",
            field=django.contrib.gis.db.models.fields.RasterField(
                srid=2154, verbose_name="Data"
            ),
        ),
    ]
