# Generated by Django 4.2 on 2024-02-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0011_alter_catchmentareatile_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="catchmentareatile",
            name="filename",
            field=models.CharField(default="", max_length=256, verbose_name="Filename"),
            preserve_default=False,
        ),
    ]
