# Generated by Django 4.2 on 2024-02-29 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0012_catchmentareatile_filename"),
    ]

    operations = [
        migrations.RenameField(
            model_name="catchmentareatile",
            old_name="data",
            new_name="rast",
        ),
    ]
