# Generated by Django 3.2.11 on 2022-01-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0012_auto_20220121_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
