# Generated by Django 4.2 on 2024-04-30 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0013_rename_data_catchmentareatile_rast"),
        ("evaluations", "0030_remove_request_parcels"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Parcel",
        ),
    ]
