# Generated by Django 4.2 on 2024-06-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0014_delete_parcel"),
    ]

    operations = [
        migrations.AddField(
            model_name="catchmentareatile",
            name="copy_to_staging",
            field=models.BooleanField(
                default=False,
                help_text="Don't touch this please",
                verbose_name="Copy to staging?",
            ),
        ),
    ]
