# Generated by Django 4.2 on 2024-06-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0014_rgealtidptprocess"),
    ]

    operations = [
        migrations.AddField(
            model_name="rgealtidptprocess",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date started"
            ),
        ),
        migrations.AlterField(
            model_name="rgealtidptprocess",
            name="filename",
            field=models.CharField(blank=True, max_length=256, verbose_name="Filename"),
        ),
    ]
