# Generated by Django 3.2.11 on 2022-01-24 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0014_auto_20220121_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='geodata.map'),
        ),
    ]
