# Generated by Django 4.2 on 2024-06-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0015_rgealtidptprocess_started_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rgealtidptprocess",
            name="expected_files",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Expected files"
            ),
        ),
        migrations.AddField(
            model_name="rgealtidptprocess",
            name="processed_files",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Processed files"
            ),
        ),
    ]
