# Generated by Django 4.2.13 on 2025-01-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0016_alter_department_geometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="attributes",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Entity attributes"
            ),
        ),
    ]
