# Generated by Django 3.2.11 on 2022-02-08 08:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0016_map_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326),
        ),
    ]
