# Generated by Django 3.2.12 on 2022-03-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0017_alter_zone_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=3, verbose_name='Department')),
                ('contact_md', models.TextField(verbose_name='Contact')),
                ('contact_html', models.TextField(blank=True, verbose_name='Contact (html)')),
            ],
            options={
                'verbose_name': 'Department contact data',
                'verbose_name_plural': 'Department contact data',
            },
        ),
    ]
