# Generated by Django 4.2.19 on 2025-04-29 09:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0018_alter_map_map_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.LineStringField(
                        geography=True,
                        help_text="DO NOT EDIT! We cannot easily deactivate this edition widget,\n            but if you use it, you will break EnvErgo.\n            ",
                        srid=4326,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date created"
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Entity attributes"
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="geodata.map",
                    ),
                ),
            ],
        ),
    ]
