# Generated by Django 4.2.19 on 2025-03-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0016_rgealtidptprocess_expected_files_and_more"),
        ("geodata", "0018_alter_map_map_type"),
    ]

    operations = []
