# Generated by Django 3.2.12 on 2022-03-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0019_alter_departmentcontact_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='task_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Celery task id'),
        ),
    ]
