# Generated by Django 4.2.19 on 2025-05-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0019_line"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="map_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zone_humide", "Zone humide"),
                    ("zone_inondable", "Zone inondable"),
                    ("species", "Espèces protégées"),
                    ("haies", "Haies"),
                    ("terres_emergees", "Délimitation terres + France"),
                ],
                max_length=50,
                verbose_name="Map type",
            ),
        ),
        migrations.AddIndex(
            model_name="map",
            index=models.Index(
                fields=["map_type"], name="geodata_map_map_typ_da8748_idx"
            ),
        ),
    ]
