# Generated by Django 3.2.12 on 2022-03-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0021_alter_department_geometry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterField(
            model_name='department',
            name='contact_md',
            field=models.TextField(blank=True, verbose_name='Contact'),
        ),
    ]
