# Generated by Django 4.2.19 on 2025-05-14 09:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0021_rename_expected_zones_map_expected_geometries_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True,
                geography=True,
                help_text="DO NOT EDIT! We cannot easily deactivate this edition widget,\n            but if you use it, you will break EnvErgo.\n            ",
                null=True,
                srid=4326,
                verbose_name="Simplified geometry",
            ),
        ),
    ]
