# Generated by Django 4.2.19 on 2025-05-20 16:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0022_alter_map_geometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="species_taxrefs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                null=True,
                size=None,
                verbose_name="Species taxrefs",
            ),
        ),
    ]
