# Generated by Django 3.2.12 on 2022-04-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0021_map_import_error_msg'),
        ('geodata', '0022_auto_20220328_0937'),
    ]

    operations = [
    ]
