# Generated by Django 4.2.19 on 2025-05-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0023_alter_map_map_type"),
        ("geodata", "0023_zone_species_taxrefs"),
    ]

    operations = []
