# Generated by Django 3.2.12 on 2022-04-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0023_merge_20220404_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='expected_zones',
            field=models.IntegerField(default=0, verbose_name='Expected zones'),
        ),
    ]
