# Generated by Django 4.2.23 on 2025-08-26 13:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0024_merge_20250522_1137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="line",
            name="geometry",
            field=django.contrib.gis.db.models.fields.MultiLineStringField(
                geography=True,
                help_text="DO NOT EDIT! We cannot easily deactivate this edition widget,\n            but if you use it, you will break EnvErgo.\n            ",
                srid=4326,
            ),
        ),
    ]
