# Generated by Django 4.2.19 on 2025-05-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0024_merge_20250520_2021"),
        ("geodata", "0024_merge_20250522_1137"),
    ]

    operations = []
