# Generated by Django 3.2.12 on 2022-04-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0024_map_expected_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='import_status',
            field=models.CharField(choices=[('success', 'Success'), ('partial_success', 'Partial success'), ('failure', 'Failure')], max_length=32, null=True, verbose_name='Import status'),
        ),
    ]
