# Generated by Django 4.2.23 on 2026-01-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0025_alter_line_geometry"),
        ("geodata", "0025_alter_line_geometry_alter_map_geometry"),
    ]

    operations = []
