# Generated by Django 3.2.12 on 2022-05-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0025_map_import_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='data_certainty',
            field=models.CharField(choices=[('certain', 'Certain'), ('uncertain', 'Uncertain')], default='certain', max_length=20, verbose_name='Data certainty'),
        ),
    ]
