# Generated by Django 4.2.28 on 2026-03-16 15:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0026_merge_20260113_1515"),
    ]

    operations = [
        migrations.AlterField(
            model_name="line",
            name="geometry",
            field=django.contrib.gis.db.models.fields.MultiLineStringField(
                geography=True,
                help_text="DO NOT EDIT! We cannot easily deactivate this edition widget,\n            but if you use it, you will break Envergo.\n            ",
                srid=4326,
            ),
        ),
    ]
