# Generated by Django 3.2.12 on 2022-06-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0026_map_data_certainty'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='display_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Display name'),
        ),
        migrations.AddField(
            model_name='map',
            name='source',
            field=models.URLField(blank=True, verbose_name='Source'),
        ),
    ]
