# Generated by Django 3.2.12 on 2022-06-15 06:56

from django.db import migrations
from django.db.models import F


def copy_map_names(apps, schema_editor):
    Map = apps.get_model('geodata', 'Map')
    Map.objects.update(display_name=F('name'))


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0027_auto_20220615_0653'),
    ]

    operations = [
        migrations.RunPython(copy_map_names, migrations.RunPython.noop)
    ]
