# Generated by Django 3.2.12 on 2022-06-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0028_copy_map_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='display_for_user',
            field=models.BooleanField(default=True, verbose_name='Display for user?'),
        ),
    ]
