# Generated by Django 4.2.28 on 2026-04-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0028_alter_map_map_type"),
        ("geodata", "0028_fix_terres_emergees_names"),
    ]

    operations = []
