# Generated by Django 4.2.28 on 2026-04-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0029_merge_20260413_1454"),
        ("geodata", "0029_merge_20260414_1532"),
    ]

    operations = []
