# Generated by Django 4.2.28 on 2026-05-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0029_merge_20260413_1454"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="map_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zone_humide", "Zone humide"),
                    ("zone_inondable", "Zone inondable"),
                    ("species", "Espèces protégées"),
                    ("species_legacy", "Espèces protégées (historique)"),
                    ("haies", "Haies"),
                    ("terres_emergees", "Délimitation terres + France"),
                    ("zonage", "Identifiant zonage"),
                    ("zone_sensible_ep", "Zone sensible EP"),
                ],
                max_length=50,
                verbose_name="Map type",
            ),
        ),
    ]
