# Generated by Django 3.2.12 on 2022-07-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0029_map_display_for_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='data_type',
            field=models.CharField(blank=True, choices=[('zone_humide', 'Zone humide'), ('zone_inondable', 'Zone inondable')], max_length=50, verbose_name='Data type'),
        ),
    ]
