# Generated by Django 3.2.12 on 2022-09-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0030_alter_map_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='source',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Source'),
        ),
    ]
