# Generated by Django 4.2.28 on 2026-05-11 14:00

from django.db import migrations


def rename_species_to_legacy(apps, schema_editor):
    """Rename all existing 'species' maps to 'species_legacy'."""
    Map = apps.get_model("geodata", "Map")
    Map.objects.filter(map_type="species").update(map_type="species_legacy")


def rename_legacy_to_species(apps, schema_editor):
    """Reverse: rename 'species_legacy' maps back to 'species'."""
    Map = apps.get_model("geodata", "Map")
    Map.objects.filter(map_type="species_legacy").update(map_type="species")


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0030_split_species_map_type"),
    ]

    operations = [
        migrations.RunPython(rename_species_to_legacy, rename_legacy_to_species),
    ]
