# Generated by Django 4.2.28 on 2026-06-01 14:20

from django.db import migrations, models


def update_map_type(apps, schema_editor):
    Map = apps.get_model("geodata", "Map")
    Map.objects.filter(map_type="terres_emergees").update(map_type="density_reference")


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0031_rename_species_to_legacy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="map_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zone_humide", "Zone humide"),
                    ("zone_inondable", "Zone inondable"),
                    ("species", "Espèces protégées"),
                    ("species_legacy", "Espèces protégées (historique)"),
                    ("haies", "Haies"),
                    (
                        "density_reference",
                        "Surface de référence du calcul de densité bocagère",
                    ),
                    ("zonage", "Identifiant zonage"),
                    ("zone_sensible_ep", "Zone sensible EP"),
                ],
                max_length=50,
                verbose_name="Map type",
            ),
        ),
        migrations.RunPython(update_map_type)
    ]
