# Generated by Django 4.2.28 on 2026-05-12 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0030_merge_20260416_1448"),
        ("geodata", "0031_rename_species_to_legacy"),
    ]

    operations = []
