# Generated by Django 4.2.28 on 2026-06-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0032_alter_map_map_type"),
        ("geodata", "0032_merge_20260512_0918"),
    ]

    operations = []
