# Generated by Django 4.2.28 on 2026-08-11 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import envergo.geodata.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geodata", "0032_alter_map_map_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapImportBatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom pense-bête", max_length=255, verbose_name="Nom"
                    ),
                ),
                (
                    "csv_file",
                    models.FileField(
                        storage=envergo.geodata.models.get_upload_storage,
                        upload_to="map_batches/csv/",
                        verbose_name="Fichier CSV",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Créé le"
                    ),
                ),
                (
                    "import_status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial_success", "Partial success"),
                            ("failure", "Failure"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="Statut de traitement du CSV",
                    ),
                ),
                (
                    "import_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date du dernier traitement"
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Celery task id",
                    ),
                ),
                (
                    "import_log",
                    models.TextField(blank=True, verbose_name="Log d'import"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lot d'import de cartes",
                "verbose_name_plural": "Lots d'import de cartes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="map",
            name="batch_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Créée par lot le"
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="batch_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Mise à jour par lot le"
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Identifiant unique utilisé pour les imports par lot",
                max_length=128,
                null=True,
                unique=True,
                verbose_name="Référence",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maps",
                to="geodata.mapimportbatch",
                verbose_name="Importé par lot",
            ),
        ),
        migrations.CreateModel(
            name="MapImportBatchFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=envergo.geodata.models.get_upload_storage,
                        upload_to=envergo.geodata.models.batch_file_path,
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1024, verbose_name="Nom du fichier"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="geodata.mapimportbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fichier de lot d'import",
                "verbose_name_plural": "Fichiers de lot d'import",
                "unique_together": {("batch", "name")},
            },
        ),
    ]
