# Generated by Django 3.2.16 on 2023-04-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0035_auto_20230323_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='data_type',
            new_name='map_type',
        ),
    ]
