# Generated by Django 3.2.16 on 2023-04-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0037_auto_20230411_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='data_type',
            field=models.CharField(choices=[('certain', 'Certain'), ('uncertain', 'Uncertain'), ('forbidden', 'Interdit')], default='certain', max_length=20, verbose_name='Data type'),
        ),
        migrations.AlterField(
            model_name='map',
            name='map_type',
            field=models.CharField(blank=True, choices=[('zone_humide', 'Zone humide'), ('zone_inondable', 'Zone inondable')], max_length=50, verbose_name='Map type'),
        ),
    ]
