# Generated by Django 4.2.13 on 2024-11-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionproject",
            name="demarches_simplifiees_dossier_number",
            field=models.IntegerField(
                blank=True,
                help_text="Dossier number on demarches-simplifiees.fr",
                null=True,
            ),
        ),
    ]
