# Generated by Django 4.2.13 on 2024-12-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0002_petitionproject_demarches_simplifiees_dossier_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionproject",
            name="demarches_simplifiees_state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("prefilled", "Prefilled"),
                    ("accepte", "Accepted"),
                    ("en_construction", "Under construction"),
                    ("en_instruction", "Under instruction"),
                    ("refuse", "Refused"),
                    ("sans_suite", "No follow-up"),
                ],
                default="draft",
                max_length=20,
                verbose_name="State of the dossier on demarches-simplifiees.fr",
            ),
        ),
    ]
