# Generated by Django 4.2.17 on 2025-02-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0003_petitionproject_demarches_simplifiees_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionproject",
            name="instructor_free_mention",
            field=models.TextField(
                blank=True, verbose_name="Mention libre de l'instructeur"
            ),
        ),
        migrations.AddField(
            model_name="petitionproject",
            name="onagre_number",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Référence Onagre du dossier"
            ),
        ),
    ]
