# Generated by Django 4.2.19 on 2025-04-28 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0018_alter_map_map_type"),
        ("petitions", "0007_alter_petitionproject_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionproject",
            name="department",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="geodata.department",
            ),
        ),
    ]
