# Generated by Django 4.2.19 on 2025-04-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0007_alter_petitionproject_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionproject",
            name="department_code",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=3,
                null=True,
                verbose_name="Department",
            ),
        ),
    ]
