# Generated by Django 4.2.19 on 2025-04-28 14:59

from django.db import migrations, models
import django.db.models.deletion
from envergo.utils.urls import extract_param_from_url


def set_department(apps, schema_editor):
    """Set department in existing petition project"""

    Department = apps.get_model('geodata', 'Department')
    PetitionProject = apps.get_model('petitions', 'PetitionProject')
    for project in PetitionProject.objects.filter(department__isnull=True):
        department_code = extract_param_from_url(project.moulinette_url, "department")
        project.department = Department.objects.filter(department=department_code).first()
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0018_alter_map_map_type"),
        ("petitions", "0007_alter_petitionproject_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionproject",
            name="department",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="petitionprojects",
                to="geodata.department",
            ),
        ),
        migrations.RunPython(set_department, migrations.RunPython.noop),
    ]
