# Generated by Django 4.2.21 on 2025-06-12 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import envergo.petitions.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("petitions", "0008_petitionproject_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=envergo.petitions.models.generate_token,
                        max_length=64,
                        unique=True,
                        verbose_name="Jeton",
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        default=envergo.petitions.models.one_month_from_now,
                        help_text="Date d'expiration du jeton",
                        null=True,
                        verbose_name="Valide jusqu'au",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date created"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte invitant",
                    ),
                ),
                (
                    "petition_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_tokens",
                        to="petitions.petitionproject",
                        verbose_name="Projet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur invité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jeton d'invitation",
                "verbose_name_plural": "Jetons d'invitation",
            },
        ),
    ]
