# Generated by Django 4.2.20 on 2025-07-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0009_invitationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionproject",
            name="demarches_simplifiees_raw_dossier",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="Données brutes du dossier provenant de Démarches Simplifiées",
            ),
        ),
    ]
