# Generated by Django 4.2.23 on 2025-08-29 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("petitions", "0010_petitionproject_demarches_simplifiees_raw_dossier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationtoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitation_tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Compte invité",
            ),
        ),
    ]
