# Generated by Django 4.2.23 on 2025-08-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0010_petitionproject_demarches_simplifiees_raw_dossier"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionproject",
            name="demarches_simplifiees_dossier_id",
            field=models.CharField(
                blank=True,
                help_text="Dossier ID on demarches-simplifiees.fr",
                null=True,
            ),
        ),
    ]
