# Generated by Django 4.2.23 on 2025-08-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "petitions",
            "0011_add_batiment_exploitation_to_amenagement_petition_projects",
        ),
        ("petitions", "0011_petitionproject_demarches_simplifiees_dossier_id"),
    ]

    operations = []
