# Generated by Django 4.2.23 on 2025-09-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "petitions",
            "0011_add_batiment_exploitation_to_amenagement_petition_projects",
        ),
        ("petitions", "0011_alter_invitationtoken_user"),
    ]

    operations = []
