# Generated by Django 4.2.23 on 2025-08-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0011_alter_invitationtoken_user"),
        ("petitions", "0012_merge_20250827_1112"),
    ]

    operations = []
