# Generated by Django 4.2.23 on 2025-09-05 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0024_merge_20250522_1137"),
        ("petitions", "0012_merge_20250902_1040"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petitionproject",
            name="department",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="petitionprojects",
                to="geodata.department",
                verbose_name="Département",
            ),
        ),
    ]
