# Generated by Django 4.2.23 on 2025-09-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0012_merge_20250902_1040"),
        ("petitions", "0013_merge_20250829_1039"),
    ]

    operations = []
