# Generated by Django 4.2.23 on 2025-09-05 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0013_alter_petitionproject_department"),
        ("petitions", "0014_merge_20250903_1047"),
    ]

    operations = []
