# Generated by Django 4.2.23 on 2025-09-17 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0011_petitionproject_demarches_simplifiees_dossier_id"),
        ("petitions", "0015_remove_petitionproject_result_and_more"),
    ]

    operations = []
