# Generated by Django 4.2.23 on 2025-09-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0014_petitionproject_result_petitionproject_stage_and_more"),
        ("petitions", "0015_merge_20250905_0859"),
    ]

    operations = []
