# Generated by Django 4.2.23 on 2025-09-17 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("petitions", "0015_remove_petitionproject_result_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="petitionproject",
            name="decision",
        ),
        migrations.RemoveField(
            model_name="petitionproject",
            name="stage",
        ),
        migrations.RemoveField(
            model_name="petitionproject",
            name="stage_date",
        ),
        migrations.RemoveField(
            model_name="petitionproject",
            name="stage_update_comment",
        ),
        migrations.RemoveField(
            model_name="petitionproject",
            name="stage_updated_at",
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("a_instruire", "À instruire"),
                            ("instruction", "Instruction"),
                            ("redaction_decision", "Rédaction décision"),
                            ("notification_publicite", "Notification & publicité"),
                            ("clos", "Dossier clos"),
                        ],
                        default="a_instruire",
                        max_length=30,
                        verbose_name="Étape",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("unset", "À déterminer"),
                            ("accord", "Accord"),
                            ("opposition", "Opposition"),
                            ("sans_suite", "Classé sans suite"),
                        ],
                        default="unset",
                        max_length=30,
                        verbose_name="Décision",
                    ),
                ),
                (
                    "update_comment",
                    models.TextField(
                        help_text="Ajouter un commentaire expliquant le contexte du changement.",
                        verbose_name="Commentaire",
                    ),
                ),
                (
                    "status_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Vous pouvez choisir une date rétroactive si nécessaire.",
                        verbose_name="Date effective du changement",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de saisie du changement de statut",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "petition_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="petitions.petitionproject",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de changement de statut de projet",
                "verbose_name_plural": "Historique des changements de statut de projet",
            },
        ),
    ]
