# Generated by Django 4.2.23 on 2025-09-24 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("petitions", "0016_merge_20250922_1648"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionproject",
            name="followed_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="followed_petition_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Instructeurs suivant le projet",
            ),
        ),
    ]
