# Generated by Django 4.2.23 on 2025-09-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0015_remove_petitionproject_result_and_more"),
        ("petitions", "0016_merge_20250911_0931"),
    ]

    operations = []
