# Generated by Django 4.2.23 on 2025-09-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0016_merge_20250922_1648"),
        ("petitions", "0016_remove_petitionproject_decision_and_more"),
    ]

    operations = []
