# Generated by Django 4.2.23 on 2025-09-30 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0017_merge_20250924_0923"),
        ("petitions", "0017_petitionproject_followed_by"),
    ]

    operations = []
