# Generated by Django 4.2.23 on 2025-09-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0016_remove_petitionproject_decision_and_more"),
        ("petitions", "0017_merge_20250912_1005"),
    ]

    operations = []
