# Generated by Django 4.2.23 on 2025-09-29 07:44

from django.db import migrations, models

def map_old_stages_to_new(apps, schema_editor):
    StatusLog = apps.get_model("petitions", "StatusLog")

    stage_mapping = {
        "a_instruire": "to_be_processed",
        "instruction": "instruction_d",
        "redaction_decision": "preparing_decision",
        "notification_publicite": "notification",
        "clos": "closed",
    }

    decision_mapping = {
        "accord": "express_agreement",
        "opposition": "objection",
        "sans_suite": "dropped",
    }

    for old, new in stage_mapping.items():
        StatusLog.objects.filter(stage=old).update(stage=new)

    for old, new in decision_mapping.items():
        StatusLog.objects.filter(decision=old).update(decision=new)

class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0017_merge_20250924_0923"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuslog",
            name="decision",
            field=models.CharField(
                choices=[
                    ("unset", "À déterminer"),
                    ("express_agreement", "Accord exprés"),
                    ("tacit_agreement", "Accord tacite"),
                    ("objection", "Opposition"),
                    ("dropped", "Classé sans suite"),
                ],
                default="unset",
                max_length=30,
                verbose_name="Décision",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="stage",
            field=models.CharField(
                choices=[
                    ("to_be_processed", "À instruire"),
                    ("instruction_d", "Instruction déclaration"),
                    ("instruction_a", "Instruction autorisation"),
                    ("instruction_h", "Instruction hors régime unique"),
                    ("preparing_decision", "Rédaction décision"),
                    ("notification", "Notification / Publicité"),
                    ("closed", "Dossier clos"),
                ],
                default="to_be_processed",
                max_length=30,
                verbose_name="Étape",
            ),
        ),
        migrations.AddConstraint(
            model_name="statuslog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("stage", "closed"), ("decision", "unset"), _negated=True
                ),
                name="forbid_closed_with_unset_decision",
            ),
        ),
    ]
