# Generated by Django 4.2.23 on 2025-10-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0018_alter_statuslog_decision_alter_statuslog_stage_and_more"),
        ("petitions", "0018_merge_20250930_0843"),
    ]

    operations = []
