# Generated by Django 4.2.23 on 2025-10-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0018_merge_20250930_0843"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuslog",
            name="due_date",
            field=models.DateField(
                null=True, verbose_name="Date de prochaine échéance"
            ),
        ),
    ]
