# Generated by Django 4.2.23 on 2025-09-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0017_petitionproject_followed_by"),
        ("petitions", "0019_merge_20250924_0934"),
    ]

    operations = []
