# Generated by Django 4.2.23 on 2025-10-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0019_merge_20251001_0741"),
        ("petitions", "0019_merge_20251008_1126"),
    ]

    operations = []
