# Generated by Django 4.2.23 on 2025-10-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0020_merge_20251010_0841"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuslog",
            name="due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de prochaine échéance"
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="update_comment",
            field=models.TextField(
                blank=True,
                help_text="Ajouter un commentaire expliquant le contexte du changement.",
                null=True,
                verbose_name="Commentaire",
            ),
        ),
    ]
