# Generated by Django 4.2.23 on 2025-09-30 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0018_alter_statuslog_created_by"),
        ("petitions", "0020_merge_20250925_1114"),
    ]

    operations = []
