# Generated by Django 4.2.23 on 2025-09-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0018_merge_20250930_0843"),
        ("petitions", "0020_merge_20250925_1114"),
    ]

    operations = []
