# Generated by Django 4.2.23 on 2025-10-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0021_statuslog_due_date_alter_statuslog_update_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuslog",
            name="update_comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Ajouter un commentaire expliquant le contexte du changement.",
                verbose_name="Commentaire",
            ),
            preserve_default=False,
        ),
    ]
