# Generated by Django 4.2.23 on 2025-10-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0019_merge_20251001_0741"),
        ("petitions", "0021_merge_20250930_0912"),
    ]

    operations = []
