# Generated by Django 4.2.23 on 2025-10-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0019_merge_20251008_1126"),
        ("petitions", "0022_merge_20251001_1151"),
    ]

    operations = []
