# Generated by Django 4.2.23 on 2025-11-06 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("petitions", "0022_alter_statuslog_update_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuslog",
            name="info_receipt_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date de réception des pièces complémentaires",
            ),
        ),
        migrations.AddField(
            model_name="statuslog",
            name="original_due_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date de prochaine échéance avant suspension",
            ),
        ),
        migrations.AddField(
            model_name="statuslog",
            name="response_due_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Échéance pour l'envoi de pièces complémentaires",
            ),
        ),
        migrations.AddField(
            model_name="statuslog",
            name="suspended_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suspended_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur de la demande d'informations complémentaires",
            ),
        ),
        migrations.AddField(
            model_name="statuslog",
            name="suspension_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date de suspension pour demande d'information complémentaire",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="decision",
            field=models.CharField(
                choices=[
                    ("unset", "À déterminer"),
                    ("tacit_agreement", "Accord tacite"),
                    ("express_agreement", "Accord exprès"),
                    ("opposition", "Opposition"),
                    ("dropped", "Classé sans suite"),
                ],
                default="unset",
                max_length=30,
                verbose_name="Décision",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="status_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Par défaut, la date du jour. Il est possible de choisir une date passée si le changement est rétroactif.",
                verbose_name="Date effective du changement",
            ),
        ),
        migrations.AddConstraint(
            model_name="statuslog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("suspension_date__isnull", False),
                        ("response_due_date__isnull", False),
                        ("original_due_date__isnull", False),
                    ),
                    models.Q(
                        ("suspension_date__isnull", True),
                        ("response_due_date__isnull", True),
                        ("original_due_date__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="supension_data_is_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="statuslog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("info_receipt_date__isnull", True),
                    models.Q(
                        ("info_receipt_date__isnull", False),
                        ("suspension_date__isnull", False),
                        ("response_due_date__isnull", False),
                        ("original_due_date__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="receipt_date_data_is_consistent",
            ),
        ),
    ]
