# Generated by Django 4.2.23 on 2025-11-05 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0022_alter_statuslog_update_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuslog",
            name="decision",
            field=models.CharField(
                choices=[
                    ("unset", "À déterminer"),
                    ("tacit_agreement", "Accord tacite"),
                    ("express_agreement", "Accord exprès"),
                    ("opposition", "Opposition"),
                    ("dropped", "Classé sans suite"),
                ],
                default="unset",
                max_length=30,
                verbose_name="Décision",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="status_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Par défaut, la date du jour. Il est possible de choisir une date passée si le changement est rétroactif.",
                verbose_name="Date effective du changement",
            ),
        ),
    ]
