# Generated by Django 4.2.23 on 2025-11-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0023_statuslog_info_receipt_date_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="statuslog",
            name="supension_data_is_consistent",
        ),
        migrations.RemoveConstraint(
            model_name="statuslog",
            name="receipt_date_data_is_consistent",
        ),
        migrations.AddConstraint(
            model_name="statuslog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("suspension_date__isnull", False),
                        ("response_due_date__isnull", False),
                    ),
                    models.Q(
                        ("suspension_date__isnull", True),
                        ("response_due_date__isnull", True),
                        ("original_due_date__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="suspension_data_is_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="statuslog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("info_receipt_date__isnull", True),
                    models.Q(
                        ("info_receipt_date__isnull", False),
                        ("suspension_date__isnull", False),
                        ("response_due_date__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="receipt_date_data_is_consistent",
            ),
        ),
    ]
