# Generated by Django 4.2.23 on 2025-11-21 10:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("petitions", "0023_alter_statuslog_decision_alter_statuslog_status_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionproject",
            name="latest_petitioner_msg",
            field=models.DateTimeField(
                default=datetime.datetime(2000, 1, 1, 0, 0, tzinfo=datetime.timezone.utc),
                verbose_name="Date du dernier message pétitionnaire",
            ),
        ),
        migrations.CreateModel(
            name="LatestMessagerieAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Dernier accès messagerie",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="petitions.petitionproject",
                        verbose_name="Projet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Accès par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dernier accès messagerie",
                "verbose_name_plural": "Derniers accès messagerie",
            },
        ),
    ]
