# Generated by Django 4.2.23 on 2025-10-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0020_merge_20251010_0841"),
        ("petitions", "0023_merge_20251008_1646"),
    ]

    operations = []
