# Generated by Django 4.2.23 on 2025-11-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0023_alter_statuslog_decision_alter_statuslog_status_date"),
        ("petitions", "0024_remove_statuslog_supension_data_is_consistent_and_more"),
    ]

    operations = []
