# Generated by Django 4.2.23 on 2025-10-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0021_statuslog_due_date_alter_statuslog_update_comment"),
        ("petitions", "0024_merge_20251010_0842"),
    ]

    operations = []
