# Generated by Django 4.2.23 on 2025-11-18 15:06

from django.db import migrations
from django.db.models import Count


def create_statuses(apps, schema_editor):
    PetitionProject = apps.get_model("petitions", "PetitionProject")
    StatusLog = apps.get_model("petitions", "StatusLog")
    projects = (
        PetitionProject.objects.all()
        .annotate(nb_logs=Count("status_history"))
        .filter(nb_logs=0)
    )
    for project in projects:
        StatusLog.objects.create(
            petition_project=project, update_comment="Création initiale"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0025_merge_20251114_1031"),
    ]

    operations = [migrations.RunPython(create_statuses, migrations.RunPython.noop)]
