# Generated by Django 4.2.23 on 2025-11-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0025_merge_20251113_1617"),
        ("petitions", "0025_merge_20251114_1031"),
    ]

    operations = []
