# Generated by Django 4.2.23 on 2025-11-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0026_create_initial_statuses"),
        ("petitions", "0026_merge_20251114_1033"),
    ]

    operations = []
