# Generated by Django 4.2.23 on 2025-11-27 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0024_petitionproject_latest_petitioner_msg_and_more"),
        ("petitions", "0026_create_initial_statuses"),
    ]

    operations = []
