# Generated by Django 4.2.23 on 2025-12-04 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0026_create_initial_statuses"),
    ]

    operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active\xa0?"),
                ),
                (
                    "moulinette_url",
                    models.URLField(max_length=2048, verbose_name="Moulinette url"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("petitioner", "Demandeur"),
                            ("instructor", "Instructeur"),
                        ],
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date created"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="petitions.petitionproject",
                        verbose_name="Simulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulation",
                "verbose_name_plural": "Simulations",
            },
        ),
        migrations.AddConstraint(
            model_name="simulation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("project", "is_active"),
                name="single_active_simulation",
            ),
        ),
    ]
