# Generated by Django 4.2.23 on 2025-12-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0027_alter_statuslog_options_simulation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="source",
            field=models.CharField(
                choices=[("petitioner", "Demandeur"), ("instructor", "Instructeur")],
                default="petitioner",
                verbose_name="Auteur",
            ),
        ),
    ]
