# Generated by Django 4.2.23 on 2025-11-27 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("petitions", "0027_merge_20251127_0917"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statuslog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Log de changement de statut de projet",
                "verbose_name_plural": "Historique des changements de statut de projet",
            },
        ),
        migrations.AlterField(
            model_name="latestmessagerieaccess",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messagerie_accesses",
                to="petitions.petitionproject",
                verbose_name="Projet",
            ),
        ),
        migrations.AlterField(
            model_name="latestmessagerieaccess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messagerie_accesses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Accès par",
            ),
        ),
        migrations.AlterField(
            model_name="petitionproject",
            name="latest_petitioner_msg",
            field=models.DateTimeField(
                default=None,
                null=True,
                verbose_name="Date du dernier message pétitionnaire",
            ),
        ),
        migrations.AddConstraint(
            model_name="latestmessagerieaccess",
            constraint=models.UniqueConstraint(
                fields=("user", "project"), name="access_unique_constraint"
            ),
        ),
    ]
