# Generated by Django 4.2.23 on 2025-12-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0027_merge_20251118_1619"),
        ("petitions", "0028_alter_statuslog_options_and_more"),
    ]

    operations = []
