# Generated by Django 4.2.23 on 2025-12-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0028_alter_statuslog_options_alter_simulation_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="comment",
            field=models.TextField(default="", verbose_name="Commentaire"),
            preserve_default=False,
        ),
    ]
