# Generated by Django 4.2.23 on 2025-12-18 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("petitions", "0028_alter_statuslog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuslog",
            name="resumed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resumed_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur de la reprise de la procédure suite à la réception d'informations complémentaires",
            ),
        ),
    ]
