# Generated by Django 4.2.23 on 2025-12-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0029_alter_statuslog_options_simulation_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="is_initial",
            field=models.BooleanField(default=False, verbose_name="Initiale\xa0?"),
        ),
        migrations.AddConstraint(
            model_name="simulation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_initial", True)),
                fields=("project", "is_initial"),
                name="single_initial_simulation",
            ),
        ),
    ]
