# Generated by Django 4.2.23 on 2025-12-11 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0030_alter_statuslog_options_simulation_is_initial_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simulations",
                to="petitions.petitionproject",
                verbose_name="Simulation",
            ),
        ),
    ]
