# Generated by Django 4.2.23 on 2025-12-11 08:48

from django.db import migrations
from django.db.models import Count


def set_first_migrations(apps, schema_editor):
    PetitionProject = apps.get_model("petitions", "PetitionProject")
    Simulation = apps.get_model("petitions", "Simulation")

    projects = PetitionProject.objects.annotate(
        nb_simulations=Count("simulations")
    ).filter(nb_simulations=0)
    for project in projects:
        Simulation.objects.create(
            project=project,
            is_initial=True,
            is_active=True,
            moulinette_url=project.moulinette_url,
            comment="Simulation initiale",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0031_alter_statuslog_options_alter_simulation_project"),
    ]

    operations = [migrations.RunPython(set_first_migrations, migrations.RunPython.noop)]
