# Generated by Django 4.2.23 on 2025-12-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0028_alter_statuslog_options_and_more"),
        ("petitions", "0032_set_first_simulation"),
    ]

    operations = []
