# Generated by Django 4.2.23 on 2026-01-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0029_statuslog_resumed_by_and_more"),
        ("petitions", "0033_merge_20251211_1513"),
    ]

    operations = []
