# Generated by Django 4.2.23 on 2025-12-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0029_merge_20251201_1101"),
        ("petitions", "0033_merge_20251211_1513"),
    ]

    operations = []
