# Generated by Django 4.2.23 on 2026-01-07 05:34

from django.db import migrations, models


def fix_missing_resumed_by(apps, schema_editor):
    """Set resumed_by for logs that have info_receipt_date but no resumed_by."""
    StatusLog = apps.get_model("petitions", "StatusLog")
    User = apps.get_model("users", "User")
    qs = StatusLog.objects.filter(
        info_receipt_date__isnull=False,
        resumed_by__isnull=True,
    )
    if qs.count() == 0:
        return

    user = User.objects.get(id=1)
    qs.update(resumed_by=user)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("petitions", "0034_merge_20260107_0633"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="statuslog",
            name="receipt_date_data_is_consistent",
        ),
        migrations.RunPython(fix_missing_resumed_by, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="statuslog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("info_receipt_date__isnull", True),
                        ("resumed_by__isnull", True),
                    ),
                    models.Q(
                        ("info_receipt_date__isnull", False),
                        ("resumed_by__isnull", False),
                        ("suspension_date__isnull", False),
                        ("response_due_date__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="receipt_date_data_is_consistent",
            ),
        ),
    ]
