# Generated by Django 4.2.23 on 2026-01-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0034_merge_20260107_0633"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="statuslog",
            name="receipt_date_data_is_consistent",
        ),
        migrations.AddConstraint(
            model_name="statuslog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("info_receipt_date__isnull", True),
                        ("resumed_by__isnull", True),
                    ),
                    models.Q(
                        ("info_receipt_date__isnull", False),
                        ("resumed_by__isnull", False),
                        ("suspension_date__isnull", False),
                        ("response_due_date__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="receipt_date_data_is_consistent",
            ),
        ),
    ]
