# Generated by Django 4.2.23 on 2025-12-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0029_statuslog_resumed_by_and_more"),
        ("petitions", "0034_merge_20251211_1515"),
    ]

    operations = []
