# Generated by Django 4.2.23 on 2026-01-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0035_merge_20251218_0645"),
        ("petitions", "0035_remove_statuslog_receipt_date_data_is_consistent_and_more"),
    ]

    operations = []
