# Generated by Django 4.2.27 on 2026-01-14 10:35

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0035_remove_statuslog_receipt_date_data_is_consistent_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="statuslog",
            name="suspension_data_is_consistent",
        ),
        migrations.RemoveConstraint(
            model_name="statuslog",
            name="receipt_date_data_is_consistent",
        ),
        migrations.AddField(
            model_name="statuslog",
            name="type",
            field=models.CharField(
                choices=[
                    ("status_change", "Changement d'état"),
                    ("suspension", "Demande de compléments"),
                    ("resumption", "Compléments reçus"),
                ],
                default="status_change",
                max_length=20,
                verbose_name="Type de log",
            ),
        ),
        migrations.AlterField(
            model_name="petitionproject",
            name="latest_petitioner_msg",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Date du dernier message pétitionnaire",
            ),
        ),
    ]
