# Generated by Django 4.2.27 on 2026-01-14 10:48

from django.db import migrations


def split_logs(apps, schema_editor):
    StatusLog = apps.get_model("petitions", "StatusLog")
    suspended_qs = StatusLog.objects.filter(suspension_date__isnull=False)
    for suspended in suspended_qs:
        StatusLog.objects.create(
            petition_project=suspended.petition_project,
            type='suspension',
            response_due_date=suspended.response_due_date,
            original_due_date=suspended.original_due_date,
            created_by=suspended.suspended_by,
            update_comment="Suspension de l’instruction, message envoyé au demandeur.",
            created_at=suspended.suspension_date,
        )
        suspended.suspension_date = None
        suspended.response_due_date = None
        suspended.original_due_date = None
        suspended.save()

    resumed_qs = StatusLog.objects.filter(info_receipt_date__isnull=False)
    for resumed in resumed_qs:

        interruption_days = resumed.info_receipt_date - resumed.suspension_date
        if resumed.original_due_date:
            new_due_date = resumed.original_due_date + interruption_days
        else:
            new_due_date = None

        StatusLog.objects.create(
            petition_project=resumed.petition_project,
            type='resumption',
            info_receipt_date=resumed.info_receipt_date,
            due_date=new_due_date,
            created_by=resumed.resumed_by,
            update_comment="Reprise de l’instruction, date d'échéance ajustée.",
            created_at=resumed.info_receipt_date,
        )
        resumed.info_receipt_date = None
        resumed.save()


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0036_remove_statuslog_suspension_data_is_consistent_and_more"),
    ]

    operations = [
        migrations.RunPython(split_logs, migrations.RunPython.noop),
    ]
