# Generated by Django 4.2.27 on 2026-01-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0037_split_logs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statuslog",
            name="resumed_by",
        ),
        migrations.RemoveField(
            model_name="statuslog",
            name="suspended_by",
        ),
        migrations.RemoveField(
            model_name="statuslog",
            name="suspension_date",
        ),
        migrations.AddConstraint(
            model_name="statuslog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("type", "suspension"), ("response_due_date__isnull", False)
                    ),
                    models.Q(
                        ("type", "status_change"),
                        ("response_due_date__isnull", True),
                        ("original_due_date__isnull", True),
                        ("info_receipt_date__isnull", True),
                    ),
                    models.Q(
                        ("type", "resumption"), ("info_receipt_date__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="suspension_data_is_consistent",
            ),
        ),]
