# Generated by Django 4.2.27 on 2026-01-19 10:38

from django.db import migrations, models


def cp_due_date(apps, schema_editor):
    StatusLog = apps.get_model("petitions", "StatusLog")
    suspension_qs = StatusLog.objects.filter(type="suspension")
    for suspension in suspension_qs:
        suspension.due_date = suspension.response_due_date
        suspension.save()

def back_to_response_due_date(apps, schema_editor):
    StatusLog = apps.get_model("petitions", "StatusLog")
    suspension_qs = StatusLog.objects.filter(type="suspension")
    for suspension in suspension_qs:
        suspension.response_due_date = suspension.due_date
        suspension.save()

class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0038_remove_statuslog_useless_fields"),
    ]

    operations = [

        migrations.RemoveConstraint(
            model_name="statuslog",
            name="suspension_data_is_consistent",
        ),
        migrations.RunPython(cp_due_date, back_to_response_due_date),
        migrations.AddConstraint(
            model_name="statuslog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("type", "suspension"), ("due_date__isnull", False)),
                    models.Q(
                        ("type", "status_change"),
                        ("original_due_date__isnull", True),
                        ("info_receipt_date__isnull", True),
                    ),
                    models.Q(
                        ("type", "resumption"), ("info_receipt_date__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="suspension_data_is_consistent",
            ),
        ),
        migrations.RemoveField(
            model_name="statuslog",
            name="response_due_date",
        ),
    ]
