# Generated by Django 4.2.27 on 2026-01-15 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0036_merge_20260107_1223"),
        ("petitions", "0038_remove_statuslog_useless_fields"),
    ]

    operations = []
