# Generated by Django 4.2.27 on 2026-01-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0039_merge_20260115_0645"),
        ("petitions", "0039_remove_statuslog_response_due_date"),
    ]

    operations = []
