# Generated by Django 4.2.27 on 2026-01-22 09:51

from django.db import migrations, models
from django.db.models import Prefetch

from envergo.petitions.models import STAGES


def populate_petition_project_status(apps, schema_editor):
    PetitionProject = apps.get_model("petitions", "PetitionProject")
    StatusLog = apps.get_model("petitions", "StatusLog")
    project_qs = PetitionProject.objects.prefetch_related(
                Prefetch(
                    "status_history",
                    queryset=StatusLog.objects.all().order_by("-created_at"),
                )
            )
    for project in project_qs:
        current_status = project.status_history.filter(type="status_change").first()
        project.stage= current_status.stage if current_status else "to_be_processed"
        project.decision = current_status.decision if current_status else "unset"

        latest_suspension = project.status_history.filter(type="suspension").first()
        latest_resumption= project.status_history.filter(type="resumption").first()
        if not latest_suspension:
            project.is_additional_information_requested = False
        elif not latest_resumption:
            project.is_additional_information_requested = True
        else:
            project.is_additional_information_requested = latest_suspension.created_at > latest_resumption.created_at

        if project.is_additional_information_requested:
            project.due_date = project.latest_suspension.due_date
        if latest_resumption and current_status:
            project.due_date = (
                latest_resumption.due_date
                if latest_resumption.created_at > current_status.created_at
                else current_status.due_date
            )
        elif current_status:
            project.due_date = current_status.due_date
        elif latest_resumption:
            project.due_date = latest_resumption.due_date

        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0039_remove_statuslog_response_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionproject",
            name="decision",
            field=models.CharField(
                choices=[
                    ("unset", "À déterminer"),
                    ("tacit_agreement", "Accord tacite"),
                    ("express_agreement", "Accord exprès"),
                    ("opposition", "Opposition"),
                    ("dropped", "Classé sans suite"),
                ],
                default="unset",
                max_length=30,
                verbose_name="Décision",
            ),
        ),
        migrations.AddField(
            model_name="petitionproject",
            name="is_additional_information_requested",
            field=models.BooleanField(
                default=False,
                verbose_name="En attente d'informations complémentaires\xa0?",
            ),
        ),
        migrations.AddField(
            model_name="petitionproject",
            name="stage",
            field=models.CharField(
                choices=[
                    ("to_be_processed", "À instruire"),
                    ("instruction_d", "Instruction déclaration"),
                    ("instruction_a", "Instruction autorisation"),
                    ("instruction_h", "Instruction hors régime unique"),
                    ("preparing_decision", "Rédaction décision"),
                    ("notification", "Notification / Publicité"),
                    ("closed", "Dossier clos"),
                ],
                default="to_be_processed",
                max_length=30,
                verbose_name="Étape",
            ),
        ),
        migrations.AddField(
            model_name="petitionproject",
            name="due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de prochaine échéance"
            ),
        ),
        migrations.RunPython(populate_petition_project_status, migrations.RunPython.noop),
    ]
