# Generated by Django 4.2.27 on 2026-01-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0040_merge_20260119_1420"),
        ("petitions", "0040_petitionproject_decision_and_more"),
    ]

    operations = []
