# Generated by Django 4.2.27 on 2026-01-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0040_petitionproject_decision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petitionproject",
            name="decision",
            field=models.CharField(
                choices=[
                    ("unset", "À déterminer"),
                    ("tacit_agreement", "Accord tacite"),
                    ("express_agreement", "Accord exprès"),
                    ("opposition", "Opposition"),
                    ("dropped", "Classé sans suite"),
                ],
                default="unset",
                help_text="Ce champ est mis à jour automatiquement à la création des StatusLogs",
                max_length=30,
                verbose_name="Décision",
            ),
        ),
        migrations.AlterField(
            model_name="petitionproject",
            name="due_date",
            field=models.DateField(
                blank=True,
                help_text="Ce champ est mis à jour automatiquement à la création des StatusLogs",
                null=True,
                verbose_name="Date de prochaine échéance",
            ),
        ),
        migrations.AlterField(
            model_name="petitionproject",
            name="is_additional_information_requested",
            field=models.BooleanField(
                default=False,
                help_text="Ce champ est mis à jour automatiquement à la création des StatusLogs",
                verbose_name="En attente d'informations complémentaires\xa0?",
            ),
        ),
        migrations.AlterField(
            model_name="petitionproject",
            name="stage",
            field=models.CharField(
                choices=[
                    ("to_be_processed", "À instruire"),
                    ("instruction_d", "Instruction déclaration"),
                    ("instruction_a", "Instruction autorisation"),
                    ("instruction_h", "Instruction hors régime unique"),
                    ("preparing_decision", "Rédaction décision"),
                    ("notification", "Notification / Publicité"),
                    ("closed", "Dossier clos"),
                ],
                default="to_be_processed",
                help_text="Ce champ est mis à jour automatiquement à la création des StatusLogs",
                max_length=30,
                verbose_name="Étape",
            ),
        ),
    ]
