# Generated by Django 4.2.28 on 2026-02-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0041_alter_petitionproject_decision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionproject",
            name="demarches_simplifiees_prefill_url",
            field=models.CharField(
                blank=True,
                help_text="Prefill dossier url on demarches-simplifiees.fr, used only when dossier is draft",
                null=True,
            ),
        ),
    ]
