# Generated by Django 4.2.28 on 2026-02-18 06:11

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0041_alter_petitionproject_decision_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                (
                    "moulinette_url",
                    models.URLField(max_length=2048, verbose_name="Moulinette url"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date created"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_snapshots",
                        to="petitions.petitionproject",
                        verbose_name="Projet",
                    ),
                ),
            ],
        ),
    ]
