# Generated by Django 4.2.27 on 2026-01-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0041_alter_petitionproject_decision_and_more"),
        ("petitions", "0041_merge_20260122_1217"),
    ]

    operations = []
