# Generated by Django 4.2.28 on 2026-03-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0042_petitionproject_demarches_simplifiees_prefill_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petitionproject",
            name="demarches_simplifiees_prefill_url",
            field=models.URLField(
                blank=True,
                help_text="Prefill dossier url on demarches-simplifiees.fr, used only when dossier is draft",
                null=True,
            ),
        ),
    ]
