# Generated by Django 4.2.28 on 2026-02-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0042_resultsnapshot"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="petitionproject",
            options={"verbose_name": "Dossier", "verbose_name_plural": "Dossiers"},
        ),
        migrations.AlterModelOptions(
            name="simulation",
            options={
                "verbose_name": "Simulation alternative",
                "verbose_name_plural": "Simulations alternatives",
            },
        ),
    ]
