# Generated by Django 4.2.28 on 2026-02-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0042_merge_20260123_0638"),
        ("petitions", "0042_resultsnapshot"),
    ]

    operations = []
