# Generated by Django 4.2.28 on 2026-02-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0043_alter_petitionproject_options_and_more"),
        ("petitions", "0043_merge_0042_merge_20260123_0638_0042_resultsnapshot"),
    ]

    operations = []
