# Generated by Django 4.2.28 on 2026-02-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0042_petitionproject_demarches_simplifiees_prefill_url"),
        ("petitions", "0044_merge_20260219_0719"),
    ]

    operations = []
