# Generated by Django 4.2.28 on 2026-03-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0043_alter_petitionproject_demarches_simplifiees_prefill_url"),
        ("petitions", "0044_populate_result_snapshots"),
    ]

    operations = []
