# Generated by Django 4.2.28 on 2026-02-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0044_populate_result_snapshots"),
        ("petitions", "0045_merge_20260219_1359"),
    ]

    operations = []
