# Generated by Django 4.2.28 on 2026-03-25 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0045_merge_20260311_1900"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petitionproject",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Date created",
            ),
        ),
        migrations.AlterField(
            model_name="petitionproject",
            name="demarches_simplifiees_date_depot",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Date de dépôt dans Démarches Simplifiées",
            ),
        ),
        migrations.AlterField(
            model_name="petitionproject",
            name="demarches_simplifiees_dossier_number",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Dossier number on demarches-simplifiees.fr",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="petitionproject",
            name="demarches_simplifiees_state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("prefilled", "Prefilled"),
                    ("accepte", "Accepted"),
                    ("en_construction", "Under construction"),
                    ("en_instruction", "Under instruction"),
                    ("refuse", "Refused"),
                    ("sans_suite", "No follow-up"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="State of the dossier on demarches-simplifiees.fr",
            ),
        ),
        migrations.AddIndex(
            model_name="petitionproject",
            index=models.Index(
                fields=[
                    "demarches_simplifiees_state",
                    "demarches_simplifiees_date_depot",
                ],
                name="pp_state_datedepot_idx",
            ),
        ),
    ]
