# Generated by Django 4.2.28 on 2026-03-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0045_merge_20260311_1900"),
        ("petitions", "0046_merge_20260224_1102"),
    ]

    operations = []
