# Generated by Django 4.2.28 on 2026-04-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0046_add_contexte_inconnu_to_moulinette_urls"),
        ("petitions", "0046_alter_petitionproject_created_at_and_more"),
    ]

    operations = []
