# Generated by Django 4.2.28 on 2026-05-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0047_merge_20260408_0746"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionproject",
            name="instructor_private_mention",
            field=models.TextField(
                blank=True, verbose_name="Notes privées de l'instructeur"
            ),
        ),
    ]
