# Generated by Django 4.2.28 on 2026-05-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0047_merge_20260408_0746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuslog",
            name="update_comment",
            field=models.TextField(
                blank=True,
                help_text="Ajouter un commentaire expliquant le contexte du changement.",
                verbose_name="Commentaire interne",
            ),
        ),
    ]
