# Generated by Django 4.2.28 on 2026-06-11 08:34

from django.db import migrations, models
import envergo.petitions.models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0048_alter_statuslog_update_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionproject",
            name="dn_archive",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=envergo.petitions.models.dn_archive_file_format,
                verbose_name="Archive Démarches numériques",
            ),
        ),
    ]
