# Generated by Django 4.2.28 on 2026-06-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0048_alter_statuslog_update_comment"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="petitionproject",
            name="pp_state_datedepot_idx",
        ),
        migrations.RenameField(
            model_name="petitionproject",
            old_name="demarches_simplifiees_date_depot",
            new_name="demarche_numerique_date_depot",
        ),
        migrations.RenameField(
            model_name="petitionproject",
            old_name="demarches_simplifiees_dossier_id",
            new_name="demarche_numerique_dossier_id",
        ),
        migrations.RenameField(
            model_name="petitionproject",
            old_name="demarches_simplifiees_dossier_number",
            new_name="demarche_numerique_dossier_number",
        ),
        migrations.RenameField(
            model_name="petitionproject",
            old_name="demarches_simplifiees_last_sync",
            new_name="demarche_numerique_last_sync",
        ),
        migrations.RenameField(
            model_name="petitionproject",
            old_name="demarches_simplifiees_prefill_url",
            new_name="demarche_numerique_prefill_url",
        ),
        migrations.RenameField(
            model_name="petitionproject",
            old_name="demarches_simplifiees_raw_dossier",
            new_name="demarche_numerique_raw_dossier",
        ),
        migrations.RenameField(
            model_name="petitionproject",
            old_name="demarches_simplifiees_state",
            new_name="demarche_numerique_state",
        ),
        migrations.AddIndex(
            model_name="petitionproject",
            index=models.Index(
                fields=["demarche_numerique_state", "demarche_numerique_date_depot"],
                name="pp_state_datedepot_idx",
            ),
        ),
        migrations.AlterField(
            model_name="petitionproject",
            name="demarche_numerique_date_depot",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Date de dépôt dans demarche.numerique.gouv.fr",
            ),
        ),
        migrations.AlterField(
            model_name="petitionproject",
            name="demarche_numerique_dossier_id",
            field=models.CharField(
                blank=True,
                help_text="Dossier ID on demarche.numerique.gouv.fr",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="petitionproject",
            name="demarche_numerique_dossier_number",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Dossier number on demarche.numerique.gouv.fr",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="petitionproject",
            name="demarche_numerique_last_sync",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Date de la dernière synchronisation avec demarche.numerique.gouv.fr",
            ),
        ),
        migrations.AlterField(
            model_name="petitionproject",
            name="demarche_numerique_prefill_url",
            field=models.URLField(
                blank=True,
                help_text="Prefill dossier url on demarche.numerique.gouv.fr, used only when dossier is draft",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="petitionproject",
            name="demarche_numerique_raw_dossier",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="Données brutes du dossier provenant de demarche.numerique.gouv.fr",
            ),
        ),
        migrations.AlterField(
            model_name="petitionproject",
            name="demarche_numerique_state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("prefilled", "Prefilled"),
                    ("accepte", "Accepted"),
                    ("en_construction", "Under construction"),
                    ("en_instruction", "Under instruction"),
                    ("refuse", "Refused"),
                    ("sans_suite", "No follow-up"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="State of the dossier on demarche.numerique.gouv.fr",
            ),
        ),
    ]
