# Generated by Django 4.2.28 on 2026-06-08 07:08
import logging
from datetime import date
from urllib.parse import urlparse, parse_qs

from dateutil import parser

from django.db import migrations, models
from django.db.models import Q
from tqdm import tqdm

from envergo.hedges.models import HedgeCategory, HedgeData

logger = logging.getLogger(__name__)

def extract_param_from_url(url, param_name):
    parsed_url = urlparse(url)
    query_params = parse_qs(parsed_url.query)
    return query_params.get(param_name, [None])[0]

def migrate_project_category(apps, schema_editor):
    PetitionProject = apps.get_model("petitions", "PetitionProject")
    ConfigHaie = apps.get_model("moulinette", "ConfigHaie")
    qs = PetitionProject.objects.all()
    total = qs.count()
    batch_size = 1000
    i = 0
    with tqdm(total=total) as pbar:
        while i < total:
            models = qs[i: i + batch_size].iterator()  # noqa
            to_update = []
            for model in models:
                date_str = extract_param_from_url(model.moulinette_url, "date")
                project_date = None
                if date_str:
                    try:
                        project_date = parser.isoparse(date_str).date()
                    except (ValueError, TypeError):
                        pass
                if not project_date:
                    project_date = date.today()
                config = ConfigHaie.objects.filter(department=model.department).filter(
            Q(validity_range__contains=project_date) | Q(validity_range__isnull=True)
        ).first()
                hedge_data = HedgeData.objects.get(pk=model.hedge_data_id)
                hedges_by_category = hedge_data.get_hedges_by_category(config.single_procedure)
                if HedgeCategory.ru in hedges_by_category and hedges_by_category[HedgeCategory.ru]:
                    model._category = HedgeCategory.ru.value
                elif HedgeCategory.l350_3 in hedges_by_category and hedges_by_category[HedgeCategory.l350_3]:
                    model._category = HedgeCategory.l350_3.value
                else:
                    model._category = HedgeCategory.hru.value
                logger.info("Project %s has category %s", model.reference, model._category)
                to_update.append(model)

            PetitionProject.objects.bulk_update(to_update, ["_category"])
            i += batch_size
            pbar.update(batch_size)



class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0048_alter_statuslog_update_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionproject",
            name="_category",
            field=models.CharField(
                choices=[
                    ("Régime unique", "Haies (procédure\xa0unique)"),
                    ("L350-3", "Alignements d'arbres bord de voie"),
                    ("Hors régime unique", "Linéaires hors procédure unique"),
                ],
                db_index=True,
                default="Hors régime unique",
                max_length=20,
                verbose_name="Catégorie du dossier",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_project_category, migrations.RunPython.noop),
    ]
