# Generated by Django 4.2.28 on 2026-06-12

from django.db import migrations, models

import envergo.petitions.models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0048_alter_statuslog_update_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuslog",
            name="prefectural_order",
            field=models.FileField(
                blank=True,
                upload_to=envergo.petitions.models.prefectural_order_file_format,
                verbose_name="Document de décision",
            ),
        ),
    ]
