# Generated by Django 4.2.28 on 2026-05-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0048_add_instructor_private_mention"),
        ("petitions", "0048_alter_statuslog_update_comment"),
    ]

    operations = []
