# Generated by Django 4.2.28 on 2026-06-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0048_alter_statuslog_update_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionproject",
            name="_category",
            field=models.CharField(
                choices=[
                    ("Régime unique", "Haies (procédure\xa0unique)"),
                    ("L350-3", "Alignements d'arbres bord de voie"),
                    ("Hors régime unique", "Linéaires hors procédure unique"),
                ],
                db_index=True,
                default="Hors régime unique",
                max_length=20,
                verbose_name="Catégorie du dossier",
            ),
            preserve_default=False,
        ),
    ]
