# Generated by Django 4.2.28 on 2026-06-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0049_petitionproject_dn_archive"),
        ("petitions", "0049_statuslog_prefectural_order"),
    ]

    operations = []
