# Generated by Django 4.2.28 on 2026-06-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0049_add_urgence_non_to_moulinette_urls"),
        ("petitions", "0049_merge_20260506_1542"),
    ]

    operations = []
