# Generated by Django 4.2.28 on 2026-06-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0049_merge_20260506_1542"),
        ("petitions", "0049_petitionproject_dn_archive"),
    ]

    operations = []
