# Generated by Django 4.2.28 on 2026-06-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0049_petitionproject_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionproject",
            name="original_multi_category_moulinette_url",
            field=models.URLField(
                blank=True,
                max_length=1024,
                verbose_name="Url de la moulinette multi catégorie d'où a été extrait ce projet le cas échéant (vide sinon)",
            ),
        ),
    ]
