# Generated by Django 4.2.28 on 2026-06-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0049_petitionproject_dn_archive"),
        ("petitions", "0050_merge_20260610_1220"),
    ]

    operations = []
