# Generated by Django 4.2.28 on 2026-06-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0050_merge_20260622_1031"),
        ("petitions", "0050_merge_20260623_0916"),
    ]

    operations = []
