# Generated by Django 4.2.28 on 2026-06-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0049_statuslog_prefectural_order"),
        ("petitions", "0051_merge_20260611_1452"),
    ]

    operations = []
