# Generated by Django 4.2.28 on 2026-06-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0049_petitionproject_dn_archive"),
        ("petitions", "0051_migrate_category_values"),
    ]

    operations = []
