# Generated by Django 4.2.28 on 2026-06-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0050_merge_20260617_1119"),
        ("petitions", "0052_merge_20260615_1658"),
    ]

    operations = []
