# Generated by Django 4.2.28 on 2026-07-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0051_merge_20260624_0831"),
        ("petitions", "0052_merge_20260618_1147"),
    ]

    operations = []
