# Generated by Django 4.2.28 on 2026-07-02 08:22
from urllib.parse import urlsplit, parse_qs, urlencode, urlunsplit

from django.db import migrations
from tqdm import tqdm


def update_qs(url, params):
    """Update an url query string with new parameters."""
    bits = urlsplit(url)
    query = parse_qs(bits.query)
    query.update(params)
    new_query = urlencode(query, doseq=True)
    new_bits = bits._replace(query=new_query)
    return urlunsplit(new_bits)


def date_depot_on_alternative_simulations(apps, schema_editor):
    PetitionProject = apps.get_model("petitions", "PetitionProject")
    Simulation = apps.get_model("petitions", "Simulation")
    qs = (PetitionProject.objects.prefetch_related('simulations')
          .exclude(demarche_numerique_state__in=['draft', 'prefilled']).all())
    total = qs.count()
    batch_size = 1000
    i = 0
    with tqdm(total=total) as pbar:
        while i < total:
            models = qs[i: i + batch_size].iterator()  # noqa
            to_update = []
            simulations_to_update = []
            for model in models:
                # add date in the url or overwrite it if there is already one
                model.moulinette_url = update_qs(
                    model.moulinette_url, {"date": model.demarche_numerique_date_depot.date().isoformat()}
                )

                simulations = list(model.simulations.all())
                for simulation in simulations:
                    simulation.moulinette_url = update_qs(simulation.moulinette_url, {"date": model.demarche_numerique_date_depot.date().isoformat()})
                    if simulation.is_initial:
                        simulation.created_at = model.demarche_numerique_date_depot

                simulations_to_update.extend(simulations)
                to_update.append(model)

            PetitionProject.objects.bulk_update(to_update, ["moulinette_url"])
            Simulation.objects.bulk_update(simulations_to_update, ['moulinette_url', 'created_at'])
            i += batch_size
            pbar.update(batch_size)


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0053_merge_20260701_1003"),
    ]

    operations = [
        migrations.RunPython(date_depot_on_alternative_simulations, migrations.RunPython.noop),
    ]

