# Generated by Django 4.2.28 on 2026-06-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0052_merge_20260618_1147"),
        ("petitions", "0053_merge_20260617_1148"),
    ]

    operations = []
