# Generated by Django 4.2.28 on 2026-07-02 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0050_merge_20260617_1119"),
        ("petitions", "0053_merge_20260701_1003"),
    ]

    operations = []
