# Generated by Django 4.2.28 on 2026-07-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0054_merge_20260702_1009"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuslog",
            name="applicant_message",
            field=models.TextField(
                blank=True, default="", verbose_name="Message au demandeur"
            ),
        ),
        migrations.AlterField(
            model_name="petitionproject",
            name="_category",
            field=models.CharField(
                choices=[
                    ("ru", "Haies bénéficiant d'une procédure unique"),
                    ("l350_3", "Alignements d'arbres en bord de voie"),
                    ("hru", "Autres haies et alignements, hors procédure unique"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Catégorie du dossier",
            ),
        ),
    ]
