# Generated by Django 4.2.28 on 2026-06-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0050_merge_20260623_0916"),
        ("petitions", "0054_merge_20260623_1202"),
    ]

    operations = []
