# Generated by Django 4.2.28 on 2026-07-10 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0054_date_depot_on_alternative_simu"),
        ("petitions", "0055_statuslog_applicant_message_and_more"),
    ]

    operations = []
