# Generated by Django 4.2.28 on 2026-06-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0051_merge_20260624_0831"),
        ("petitions", "0055_merge_20260624_0654"),
    ]

    operations = []
