# Generated by Django 4.2.28 on 2026-07-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0053_merge_20260701_1003"),
        ("petitions", "0056_merge_20260626"),
    ]

    operations = []
