# Generated by Django 4.2.28 on 2026-09-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0056_merge_20260710_0758"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="petitionproject",
            name="onagre_number",
        ),
    ]
