# Generated by Django 4.2.28 on 2026-09-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0057_remove_petitionproject_onagre_number"),
        ("petitions", "0057_simulation_created_by"),
    ]

    operations = []
