# Generated by Django 4.2.28 on 2026-07-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0054_date_depot_on_alternative_simu"),
        ("petitions", "0057_merge_0053_merge_20260701_1003_0056_merge_20260626"),
    ]

    operations = []
