# Generated by Django 4.2.28 on 2026-07-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "petitions",
            "0054_rename_demarches_simplifiees_fields_to_demarche_numerique_and_more",
        ),
        ("petitions", "0058_merge_20260702_1216"),
    ]

    operations = []
