# Generated by Django 5.2.17 on 2026-10-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0058_merge_20260915_1647"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petitionproject",
            name="_category",
            field=models.CharField(
                choices=[("ru", "ru"), ("l350_3", "l350_3"), ("hru", "hru")],
                db_index=True,
                max_length=20,
                verbose_name="Catégorie du dossier",
            ),
        ),
    ]
