# Generated by Django 4.2 on 2023-04-25 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_md", models.TextField(verbose_name="Content")),
                ("content_html", models.TextField(verbose_name="Content HTML")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date created"
                    ),
                ),
            ],
            options={
                "verbose_name": "News item",
                "verbose_name_plural": "News items",
            },
        ),
    ]
