# Generated by Django 4.2.13 on 2024-12-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_confirmed_by_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_confirmed_by_admin",
            field=models.BooleanField(
                default=False, verbose_name="Confirmed by an admin"
            ),
        ),
    ]
