# Generated by Django 4.2.13 on 2024-12-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_is_confirmed_by_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access_amenagement",
            field=models.BooleanField(
                default=True, verbose_name="Access amenagement site"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="access_haie",
            field=models.BooleanField(default=False, verbose_name="Access haie site"),
        ),
    ]
