# Generated by Django 4.2.13 on 2024-12-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_access_amenagement_user_access_haie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="access_amenagement",
            field=models.BooleanField(
                default=False, verbose_name="Access amenagement site"
            ),
        ),
    ]
