# Generated by Django 4.2.17 on 2025-02-13 16:11

from django.db import migrations

BASE_PERMISSIONS = [
    'view_logentry',
    'view_hostedfile',
    'view_topbar',
    'view_criterion',
    'view_department',
    'view_map',
    'view_zone',
    'view_species',
    'view_configamenagement',
    'view_confighaie',
    'view_perimeter',
    'view_regulation',
    'view_site',
]

def create_group_staff_base(apps, schema_editor):
    """Add group to staff users"""

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    view_permissions_pks = Permission.objects.filter(codename__in=BASE_PERMISSIONS) \
        .values_list('pk', flat=True)

    staff_base_group = Group.objects.get_or_create(name="Staff base")[0]
    staff_base_group.permissions.set(view_permissions_pks)

    User = apps.get_model("users", "User")
    staff_users = User.objects.filter(is_active=True, is_staff=True)
    for user in staff_users:
        user.groups.add(staff_base_group)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_access_amenagement"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(
            create_group_staff_base,
            reverse_code=migrations.RunPython.noop),
    ]
