# Generated by Django 4.2.17 on 2025-02-13 16:11

from django.db import migrations


def create_group_staff_base(apps, schema_editor):
    """Add group to staff users"""
    User = apps.get_model("users", "User")
    staff_users = User.objects.filter(is_active=True, is_staff=True)

    base_permissions = [
        'view_logentry',
        'view_hostedfile',
        'view_topbar',
        'view_criterion',
        'view_department',
        'view_map',
        'view_zone',
        'view_species',
        'view_configamenagement',
        'view_confighaie',
        'view_perimeter',
        'view_regulation',
        'view_site',
    ]
    Group = apps.get_model("django.contrib.auth", "Group")
    Permission = apps.get_model("django.contrib.auth", "Permission")
    view_permissions_pks = Permission.objects.filter(codename__in=base_perm).values_list('pk', flat=True)

    staff_base_group = Group.objects.get_or_create(name="Staff base")
    staff_base_group.group_permissions.set(view_permissions_pks)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_access_amenagement"),
    ]

    operations = []
