# Generated by Django 4.2.19 on 2025-04-23 15:26

from django.db import migrations, models


def set_default_department_aisne_to_instructors(apps, schema_editor):
    """Set department Aisne for existing instructors"""

    Department = apps.get_model('geodata', 'Department')
    Department_Aisne = Department.objects.filter(department="02").first()
    User = apps.get_model('users', 'User')
    for user in User.objects.filter(is_confirmed_by_admin=True, access_haie=True):
        user.departments.add(Department_Aisne)


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0018_alter_map_map_type"),
        ("users", "0006_alter_user_is_confirmed_by_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="departments",
            field=models.ManyToManyField(
                related_name="members",
                to="geodata.department",
                verbose_name="Departements",
            ),
        ),
        migrations.RunPython(set_default_department_aisne_to_instructors, migrations.RunPython.noop),
    ]
