# Generated by Django 4.2.19 on 2025-04-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0018_alter_map_map_type"),
        ("users", "0006_alter_user_is_confirmed_by_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="departments",
            field=models.ManyToManyField(
                related_name="members",
                to="geodata.department",
                verbose_name="Departements",
            ),
        ),
    ]
