# Generated by Django 4.2.19 on 2025-05-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0018_alter_map_map_type"),
        ("users", "0007_user_departments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                related_name="members",
                to="geodata.department",
                verbose_name="Departements",
            ),
        ),
    ]
