# Generated by Django 4.2.21 on 2025-06-19 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_departments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_confirmed_by_admin",
        ),
    ]
