# Generated by Django 4.2.23 on 2025-11-24 15:06

from django.db import migrations, models
from django.db.models import Q


def set_default_is_instructor(apps, schema_editor):
    """Set is_instructor True for
    - is active
    - has access haie
    - is_staff or users has departments"""

    User = apps.get_model("users", "User")
    q_is_staff = Q(is_staff=True)
    q_has_departments = Q(departments__isnull=False)
    for user in User.objects.filter(access_haie=True, is_active=True).filter(
        q_is_staff | q_has_departments
    ):
        user.is_instructor = True
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_user_is_confirmed_by_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_instructor",
            field=models.BooleanField(
                default=False,
                help_text="Instructeur pour tous les départements qui lui sont assignés. Si cette case n'est pas cochée, la personne a le statut d'invitée.",
                verbose_name="Instructor",
            ),
        ),
        migrations.RunPython(set_default_is_instructor, migrations.RunPython.noop),
    ]
