# Generated by Django 4.2.23 on 2025-11-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_user_is_confirmed_by_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_instructor",
            field=models.BooleanField(
                default=False,
                help_text="Instructeur pour tous les départements qui lui sont assignés. Si cette case n'est pas cochée, la personne a le statut d'invitée.",
                verbose_name="Instructor",
            ),
        ),
    ]
