# Generated by Django 4.2.23 on 2025-12-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_is_instructor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_instructor_for_departments",
            new_name="is_instructor",
        ),
    ]
