#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

sudo apt update
sudo apt install -y language-pack-fr
sudo locale-gen fr_FR.UTF-8
sudo update-locale LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8

python manage.py migrate
python manage.py runserver_plus 0.0.0.0:8000
