# Generated by Django 3.2.12 on 2022-06-30 09:39

import django.db.models.deletion
from django.db import migrations, models

import envergo.moulinette.fields
import envergo.moulinette.regulations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geodata", "0029_map_display_for_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perimeter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                (
                    "criterion",
                    envergo.moulinette.fields.CriterionChoiceField(
                        choices=[
                            (
                                envergo.moulinette.regulations.loisurleau.ZoneHumide,
                                "ZoneHumide",
                            ),
                            (
                                envergo.moulinette.regulations.loisurleau.ZoneInondable,
                                "ZoneInondable",
                            ),
                            (
                                envergo.moulinette.regulations.loisurleau.Ruissellement,
                                "Ruissellement",
                            ),
                        ],
                        max_length=250,
                        verbose_name="Criterion",
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="perimeters",
                        to="geodata.map",
                        verbose_name="Map",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perimeter",
                "verbose_name_plural": "Perimeters",
            },
        ),
    ]
