# Generated by Django 4.2 on 2023-05-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moulinetteconfig",
            name="ddtm_contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="DDT(M) contact email"
            ),
        ),
    ]
