# Generated by Django 3.2.12 on 2022-09-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moulinette', '0001_initial'),
    ]

    # For some reason, django won't create this field during the migration
    operations = [
        migrations.RunSQL('ALTER TABLE moulinette_perimeter ADD IF NOT EXISTS criterion VARCHAR(256) NOT NULL', migrations.RunSQL.noop)
    ]
