# Generated by Django 3.2.15 on 2022-11-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moulinette', '0002_add_missing_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimeter',
            name='activation_distance',
            field=models.PositiveIntegerField(default=0, verbose_name='Activation distance'),
        ),
    ]
