# Generated by Django 4.2 on 2023-06-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0002_moulinetteconfig_ddtm_contact_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                ("address_md", models.TextField(verbose_name="Address")),
                (
                    "address_html",
                    models.TextField(blank=True, verbose_name="Address HTML"),
                ),
                (
                    "perimeter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact",
                        to="moulinette.perimeter",
                        verbose_name="Perimeter",
                    ),
                ),
            ],
            options={
                "verbose_name": "SAGE datum",
                "verbose_name_plural": "SAGE data",
            },
        ),
    ]
