# Generated by Django 3.2.16 on 2023-03-15 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0032_map_copy_to_staging'),
        ('moulinette', '0003_perimeter_activation_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoulinetteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lse_contact_ddtm', models.TextField(verbose_name='LSE > Contact DDTM')),
                ('n2000_contact_ddtm_info', models.TextField(verbose_name='N2000 > Contact DDTM info')),
                ('n2000_contact_ddtm_instruction', models.TextField(verbose_name='N2000 > Contact DDTM instruction')),
                ('n2000_procedure_ein', models.TextField(verbose_name='N2000 > Procédure EIN')),
                ('evalenv_procedure_casparcas', models.TextField(verbose_name='EvalEnv > Procédure cas par cas')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='geodata.department', verbose_name='Department')),
            ],
        ),
    ]
