# Generated by Django 4.2 on 2023-06-12 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0003_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Contact", "verbose_name_plural": "Contacts"},
        ),
    ]
