# Generated by Django 4.2 on 2023-06-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0004_alter_contact_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="regulation_url",
            field=models.URLField(blank=True, verbose_name="Regulation URL"),
        ),
    ]
