# Generated by Django 3.2.16 on 2023-03-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0032_map_copy_to_staging'),
        ('moulinette', '0004_moulinetteconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moulinetteconfig',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='moulinette_config', to='geodata.department', verbose_name='Department'),
        ),
    ]
