# Generated by Django 3.2.16 on 2023-03-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moulinette', '0005_alter_moulinetteconfig_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moulinetteconfig',
            options={'verbose_name': 'Moulinette config', 'verbose_name_plural': 'Moulinette configs'},
        ),
        migrations.AddField(
            model_name='moulinetteconfig',
            name='is_activated',
            field=models.BooleanField(default=False, help_text='Is the moulinette available for this department?', verbose_name='Is activated'),
        ),
    ]
