# Generated by Django 3.2.16 on 2023-04-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moulinette', '0006_auto_20230328_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='moulinetteconfig',
            name='criteria_values',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Valeurs des critères'),
        ),
    ]
