# Generated by Django 4.2 on 2023-06-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0006_regulation_criterion"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterion",
            name="activation_distance",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Activation distance"
            ),
        ),
        migrations.AddField(
            model_name="regulation",
            name="activation_distance",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Activation distance"
            ),
        ),
    ]
