# Generated by Django 3.2.16 on 2023-04-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moulinette', '0007_moulinetteconfig_criteria_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='moulinetteconfig',
            name='n2000_lotissement_proximite',
            field=models.TextField(default='', verbose_name='N2000 > Précision proximité immédiate'),
        ),
    ]
