# Generated by Django 3.2.16 on 2023-04-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moulinette', '0008_moulinetteconfig_n2000_lotissement_proximite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moulinetteconfig',
            name='n2000_lotissement_proximite',
            field=models.TextField(blank=True, verbose_name='N2000 > Précision proximité immédiate'),
        ),
    ]
