# Generated by Django 4.2 on 2023-07-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0009_criterion_required_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterion",
            name="discussion_contact",
            field=models.TextField(
                blank=True,
                help_text="Le porteur de projet peut se rapprocher…",
                verbose_name="Discussion contact",
            ),
        ),
        migrations.AddField(
            model_name="criterion",
            name="project_impact",
            field=models.CharField(
                blank=True,
                help_text="Au vu des informations saisies, le projet…",
                max_length=256,
                verbose_name="Project impact",
            ),
        ),
        migrations.AlterField(
            model_name="criterion",
            name="required_action",
            field=models.CharField(
                blank=True,
                help_text="Le porteur doit s'assurer que son projet…",
                max_length=256,
                verbose_name="Required action",
            ),
        ),
    ]
