# Generated by Django 4.2 on 2023-07-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0010_criterion_discussion_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="regulation",
            name="map_caption",
            field=models.TextField(blank=True, verbose_name="Map caption"),
        ),
        migrations.AddField(
            model_name="regulation",
            name="polygon_color",
            field=models.CharField(
                default="blue", max_length=7, verbose_name="Polygon color"
            ),
        ),
        migrations.AddField(
            model_name="regulation",
            name="show_map",
            field=models.BooleanField(default=False, verbose_name="Show map"),
        ),
        migrations.AlterField(
            model_name="criterion",
            name="discussion_contact",
            field=models.TextField(
                blank=True,
                help_text="Le porteur de projet peut se rapprocher…",
                verbose_name="Discussion contact (html)",
            ),
        ),
    ]
