# Generated by Django 4.2 on 2023-07-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0011_regulation_map_caption_regulation_polygon_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterion",
            name="map_caption",
            field=models.TextField(blank=True, verbose_name="Map caption"),
        ),
        migrations.AddField(
            model_name="criterion",
            name="polygon_color",
            field=models.CharField(
                default="blue", max_length=7, verbose_name="Polygon color"
            ),
        ),
        migrations.AddField(
            model_name="criterion",
            name="show_map",
            field=models.BooleanField(
                default=False,
                help_text="Allow this criterion's map to be displayed at the regulation level.",
                verbose_name="Show map",
            ),
        ),
    ]
