# Generated by Django 4.2 on 2023-07-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0012_criterion_map_caption_criterion_polygon_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regulation",
            name="activation_distance",
        ),
        migrations.RemoveField(
            model_name="regulation",
            name="perimeter",
        ),
        migrations.RemoveField(
            model_name="regulation",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="regulation",
            name="title",
        ),
        migrations.AddField(
            model_name="regulation",
            name="regulation",
            field=models.CharField(
                choices=[
                    ("loi_sur_leau", "Loi sur l'eau"),
                    ("natura2000", "Natura 2000"),
                    ("eval_env", "Évaluation environnementale"),
                    ("sage", "Réglement de SAGE"),
                ],
                default="loi_sur_leau",
                max_length=64,
                verbose_name="Regulation",
            ),
            preserve_default=False,
        ),
    ]
