# Generated by Django 4.2 on 2023-07-13 09:36

from django.db import migrations


def remove_useless_perimeters(apps, schema_editor):
    Contact = apps.get_model("moulinette", "Contact")
    Contact.objects.all().delete()
    Perimeter = apps.get_model("moulinette", "Perimeter")
    Perimeter.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0014_rename_perimeter_criterion_activation_map_and_more"),
    ]

    operations = [
        migrations.RunPython(
            remove_useless_perimeters, reverse_code=migrations.RunPython.noop
        )
    ]
