# Generated by Django 4.2 on 2023-07-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0015_remove_useless_perimeters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perimeter",
            name="regulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="perimeters",
                to="moulinette.regulation",
                verbose_name="Regulation",
            ),
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
