# Generated by Django 4.2 on 2023-07-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0016_alter_perimeter_regulation_delete_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="perimeter",
            name="long_name",
            field=models.CharField(
                blank=True,
                help_text="Displayed below the regulation title",
                max_length=256,
                verbose_name="Long name",
            ),
        ),
    ]
