# Generated by Django 4.2 on 2023-07-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0019_perimeter_url_alter_criterion_activation_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="perimeter",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Contact email"
            ),
        ),
        migrations.AddField(
            model_name="perimeter",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Contact name"
            ),
        ),
        migrations.AlterField(
            model_name="regulation",
            name="regulation",
            field=models.CharField(
                choices=[
                    ("loi_sur_leau", "Loi sur l'eau"),
                    ("natura2000", "Natura 2000"),
                    ("eval_env", "Évaluation environnementale"),
                    ("sage", "Règlement de SAGE"),
                ],
                max_length=64,
                verbose_name="Regulation",
            ),
        ),
    ]
