# Generated by Django 4.2 on 2023-07-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0021_alter_criterion_weight_alter_regulation_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterion",
            name="backend_title",
            field=models.CharField(
                default="Change me",
                help_text="For backend usage only",
                max_length=256,
                verbose_name="Admin title",
            ),
            preserve_default=False,
        ),
    ]
