# Generated by Django 4.2 on 2023-07-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0022_criterion_backend_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criterion",
            name="title",
            field=models.CharField(
                help_text="For frontend usage", max_length=256, verbose_name="Title"
            ),
        ),
    ]
