# Generated by Django 4.2 on 2023-07-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0023_alter_criterion_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="perimeter",
            name="backend_name",
            field=models.CharField(
                default="Change me", max_length=256, verbose_name="Name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="perimeter",
            name="map_legend",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Map legend"
            ),
        ),
        migrations.AddField(
            model_name="perimeter",
            name="rules_url",
            field=models.URLField(blank=True, verbose_name="Rules url"),
        ),
    ]
