# Generated by Django 4.2 on 2023-07-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0024_perimeter_backend_name_perimeter_map_legend_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perimeter",
            name="rules_url",
            field=models.URLField(verbose_name="Rules url"),
        ),
    ]
