# Generated by Django 4.2 on 2023-07-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0025_alter_perimeter_rules_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perimeter",
            name="backend_name",
            field=models.CharField(
                help_text="For admin usage only",
                max_length=256,
                verbose_name="Backend name",
            ),
        ),
    ]
