# Generated by Django 4.2 on 2023-07-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0026_alter_perimeter_backend_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perimeter",
            name="url",
            field=models.URLField(blank=True, verbose_name="Url"),
        ),
    ]
