# Generated by Django 4.2 on 2023-09-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0029_update_moulinette_config_header_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="regulation",
            name="has_perimeters",
            field=models.BooleanField(
                default=False,
                help_text="Is this regulation linked to local perimetres?",
                verbose_name="Has perimeters",
            ),
        ),
    ]
