# Generated by Django 4.2 on 2023-09-21 12:43

import django.contrib.postgres.fields
from django.db import migrations, models
import envergo.moulinette.models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0030_regulation_has_perimeters"),
    ]

    operations = [
        migrations.AddField(
            model_name="moulinetteconfig",
            name="regulations_available",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("loi_sur_leau", "Loi sur l'eau"),
                        ("natura2000", "Natura 2000"),
                        ("eval_env", "Évaluation environnementale"),
                        ("sage", "Règlement de SAGE"),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=envergo.moulinette.models.all_regulations,
                size=None,
            ),
        ),
    ]
