# Generated by Django 4.2 on 2023-10-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0032_alter_moulinetteconfig_regulations_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="perimeter",
            name="is_activated",
            field=models.BooleanField(
                default=True,
                help_text="Check if all criteria have been set",
                verbose_name="Is activated",
            ),
        ),
    ]
