# Generated by Django 4.2 on 2023-11-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0035_moulinetteconfig_lse_free_mention"),
    ]

    operations = [
        migrations.RenameField(
            model_name="moulinetteconfig",
            old_name="ddtm_contact_email",
            new_name="ddtm_water_police_email",
        ),
        migrations.AddField(
            model_name="moulinetteconfig",
            name="ddtm_n2000_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="E-mail DDT(M) Natura\xa02000"
            ),
        ),
        migrations.AddField(
            model_name="moulinetteconfig",
            name="dreal_eval_env_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="E-mail DREAL pôle eval env"
            ),
        ),
    ]
