# Generated by Django 4.2 on 2023-11-09 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0036_moulinetteconfig_n2000_autorisation_urba_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoulinetteTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=256, verbose_name="Key")),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="Content"),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="templates",
                        to="moulinette.moulinetteconfig",
                        verbose_name="Config",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moulinette template",
                "verbose_name_plural": "Moulinette templates",
            },
        ),
    ]
