# Generated by Django 4.2 on 2023-11-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0036_remove_moulinetteconfig_ddtm_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moulinetteconfig",
            name="ddtm_water_police_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="E-mail DDT(M) police de l'eau"
            ),
        ),
    ]
