# Generated by Django 4.2 on 2023-11-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0037_moulinettetemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moulinettetemplate",
            name="key",
            field=models.CharField(
                choices=[
                    ("autorisation_urba_pc", "autorisation_urba_pc"),
                    (
                        "autorisation_urba_amenagement_dp",
                        "autorisation_urba_amenagement_dp",
                    ),
                    (
                        "autorisation_urba_construction_dp",
                        "autorisation_urba_construction_dp",
                    ),
                    ("autorisation_urba_none", "autorisation_urba_none"),
                    ("autorisation_urba_other", "autorisation_urba_other"),
                ],
                max_length=64,
                verbose_name="Key",
            ),
        ),
        migrations.AddConstraint(
            model_name="moulinettetemplate",
            constraint=models.UniqueConstraint(
                models.F("config"), models.F("key"), name="unique_template_config_key"
            ),
        ),
    ]
