# Generated by Django 4.2 on 2023-11-10 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0037_alter_moulinetteconfig_ddtm_water_police_email"),
        ("moulinette", "0038_alter_moulinettetemplate_key_and_more"),
    ]

    operations = []
