# Generated by Django 4.2 on 2023-11-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0039_merge_20231110_1426"),
    ]

    operations = [
        migrations.AddField(
            model_name="moulinetteconfig",
            name="dreal_department_unit_url",
            field=models.URLField(
                blank=True, verbose_name="Unité départementale de la DREAL"
            ),
        ),
        migrations.AlterField(
            model_name="moulinettetemplate",
            name="key",
            field=models.CharField(
                choices=[
                    ("autorisation_urba_pa", "autorisation_urba_pa"),
                    ("autorisation_urba_pc", "autorisation_urba_pc"),
                    (
                        "autorisation_urba_amenagement_dp",
                        "autorisation_urba_amenagement_dp",
                    ),
                    (
                        "autorisation_urba_construction_dp",
                        "autorisation_urba_construction_dp",
                    ),
                    ("autorisation_urba_none", "autorisation_urba_none"),
                    ("autorisation_urba_other", "autorisation_urba_other"),
                ],
                max_length=64,
                verbose_name="Key",
            ),
        ),
    ]
