# Generated by Django 4.2 on 2023-12-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0040_moulinetteconfig_dreal_department_unit_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moulinetteconfig",
            name="dreal_department_unit_url",
            field=models.URLField(blank=True, verbose_name="Url UD DREAL"),
        ),
    ]
