# Generated by Django 4.2 on 2023-12-04 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0041_alter_moulinetteconfig_dreal_department_unit_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="criterion",
            name="slug",
        ),
    ]
