# Generated by Django 4.2 on 2023-12-08 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0040_remove_perimeter_long_name_and_more"),
        ("moulinette", "0042_remove_criterion_slug"),
    ]

    operations = []
