# Generated by Django 4.2 on 2023-12-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0044_alter_perimeter_rules_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterion",
            name="evaluator_settings",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Evaluator settings"
            ),
        ),
    ]
