# Generated by Django 4.2 on 2024-01-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0045_criterion_evaluator_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criterion",
            name="evaluator_settings",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Evaluator settings"
            ),
        ),
        migrations.AlterField(
            model_name="moulinettetemplate",
            name="key",
            field=models.CharField(
                choices=[
                    ("autorisation_urba_pa", "autorisation_urba_pa"),
                    (
                        "autorisation_urba_pa_lotissement",
                        "autorisation_urba_pa_lotissement",
                    ),
                    ("autorisation_urba_pc", "autorisation_urba_pc"),
                    (
                        "autorisation_urba_amenagement_dp",
                        "autorisation_urba_amenagement_dp",
                    ),
                    (
                        "autorisation_urba_construction_dp",
                        "autorisation_urba_construction_dp",
                    ),
                    ("autorisation_urba_none", "autorisation_urba_none"),
                    ("autorisation_urba_other", "autorisation_urba_other"),
                ],
                max_length=64,
                verbose_name="Key",
            ),
        ),
    ]
