# Generated by Django 4.2 on 2024-03-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0047_moulinettetemplate_criterion_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="moulinettetemplate",
            name="unique_template_config_key",
        ),
        migrations.AddConstraint(
            model_name="moulinettetemplate",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("config__isnull", False), ("criterion", None)),
                    models.Q(("config", None), ("criterion__isnull", False)),
                    _connector="OR",
                ),
                name="relation_to_single_object",
            ),
        ),
        migrations.AddConstraint(
            model_name="moulinettetemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("config__isnull", False)),
                fields=("config", "key"),
                name="unique_template_config_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="moulinettetemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("criterion__isnull", False)),
                fields=("criterion", "key"),
                name="unique_template_criterion_key",
            ),
        ),
    ]
