# Generated by Django 4.2 on 2024-03-11 13:59

from django.db import migrations


def move_settings(apps, schema_editor):
    Criterion = apps.get_model("moulinette", "Criterion")
    MoulinetteConfig = apps.get_model("moulinette", "MoulinetteConfig")
    MoulinetteTemplate = apps.get_model("moulinette", "MoulinetteTemplate")

    criteria = Criterion.objects.filter(
        evaluator__in=[
            "envergo.moulinette.regulations.natura2000.AutorisationUrbanisme",
            "envergo.moulinette.regulations.natura2000.AutorisationUrbanismeExcLotissement",
        ]
    )
    for criterion in criteria:
        department = criterion.activation_map.departments[0]
        config = MoulinetteConfig.objects.get(department__department=department)
        criterion.evaluator_settings["result_code_matrix"] = (
            config.n2000_autorisation_urba_result
        )
        criterion.save()
        for template in config.templates.all():
            MoulinetteTemplate.objects.update_or_create(
                criterion=criterion,
                key=template.key,
                defaults={"content": template.content},
            )


class Migration(migrations.Migration):
    dependencies = [
        (
            "moulinette",
            "0048_remove_moulinettetemplate_unique_template_config_key_and_more",
        ),
    ]

    operations = [migrations.RunPython(move_settings, migrations.RunPython.noop)]
