# Generated by Django 4.2 on 2024-03-18 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0047_criterion_is_optional_alter_moulinettetemplate_key"),
        ("moulinette", "0049_move_n2000_settings"),
    ]

    operations = []
