# Generated by Django 4.2 on 2024-04-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0050_merge_20240318_1411"),
    ]

    operations = [
        migrations.AddField(
            model_name="moulinetteconfig",
            name="zh_doubt",
            field=models.BooleanField(
                default=False, verbose_name="Tout le département en ZH doute"
            ),
        ),
    ]
