# Generated by Django 4.2 on 2024-06-12 14:03

from django.db import migrations


AUTO_URBA_TEMPLATE_KEYS = [
    "autorisation_urba_pa",
    "autorisation_urba_pa_lotissement",
    "autorisation_urba_pc",
    "autorisation_urba_amenagement_dp",
    "autorisation_urba_construction_dp",
    "autorisation_urba_none",
    "autorisation_urba_other",
]


def remove_autorisation_urba_config_templates(apps, schema_editor):
    """Remove obsolete moulinette templates."""

    MoulinetteTemplate = apps.get_model("moulinette", "MoulinetteTemplate")
    templates = MoulinetteTemplate.objects.filter(config__isnull=False).filter(
        key__in=AUTO_URBA_TEMPLATE_KEYS
    )
    templates.delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "moulinette",
            "0052_remove_moulinetteconfig_n2000_autorisation_urba_result_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            remove_autorisation_urba_config_templates, migrations.RunPython.noop
        )
    ]
