# Generated by Django 4.2.13 on 2024-06-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0053_remove_autorisation_urba_config_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moulinetteconfig",
            name="criteria_values",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Valeurs des critères"
            ),
        ),
    ]
