# Generated by Django 4.2.13 on 2024-07-22 14:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_add_haie"),
        ("moulinette", "0055_alter_moulinettetemplate_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="regulation",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
        ),
        migrations.AlterField(
            model_name="moulinetteconfig",
            name="regulations_available",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("loi_sur_leau", "Loi sur l'eau"),
                        ("natura2000", "Natura 2000"),
                        ("eval_env", "Évaluation environnementale"),
                        ("sage", "Règlement de SAGE"),
                        (
                            "bcae8",
                            "Bonnes conditions agricoles et environnementales - Fiche VIII",
                        ),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="regulation",
            name="regulation",
            field=models.CharField(
                choices=[
                    ("loi_sur_leau", "Loi sur l'eau"),
                    ("natura2000", "Natura 2000"),
                    ("eval_env", "Évaluation environnementale"),
                    ("sage", "Règlement de SAGE"),
                    (
                        "bcae8",
                        "Bonnes conditions agricoles et environnementales - Fiche VIII",
                    ),
                ],
                max_length=64,
                verbose_name="Regulation",
            ),
        ),
    ]
