# Generated by Django 4.2.13 on 2024-07-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0055_alter_moulinettetemplate_key"),
        ("moulinette", "0055_criterion_perimeter_alter_moulinettetemplate_key"),
    ]

    operations = []
