# Generated by Django 4.2.13 on 2024-07-22 14:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_add_haie"),
        ("moulinette", "0057_set_criteria_perimeters"),
    ]

    operations = [
        migrations.AddField(
            model_name="regulation",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
        ),
    ]
