# Generated by Django 4.2.13 on 2024-07-25 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_add_haie"),
        ("moulinette", "0058_regulation_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulation",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="sites.site"
            ),
        ),
    ]
