# Generated by PY

import django.contrib.postgres.fields
from django.db import migrations, models, transaction
from django.db.models import Q


@transaction.atomic
def add_default_threshold(apps, schema_editor):
    Criterion = apps.get_model("moulinette", "Criterion")
    qs = Criterion.objects.filter(~Q(evaluator_settings__has_key="threshold"), evaluator="envergo.moulinette.regulations.natura2000.ZoneHumide" )
    to_update = []
    for criterion in qs.all():
        if not criterion.evaluator_settings:
            criterion.evaluator_settings = {}
        criterion.evaluator_settings["threshold"] = 100
        to_update.append(criterion)

    Criterion.objects.bulk_update(to_update, ["evaluator_settings"])


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0058_alter_moulinetteconfig_regulations_available_and_more"),
    ]

    operations = [
        migrations.RunPython(add_default_threshold, migrations.RunPython.noop),
    ]
