# Generated by Django 4.2.13 on 2024-10-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0059_alter_moulinettetemplate_key_haiedepartmentconfig"),
        ("moulinette", "0059_n2000_zh_criterion_add_threshold"),
    ]

    operations = []
