# Generated by Django 4.2.13 on 2024-10-07 12:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0016_alter_department_geometry"),
        ("moulinette", "0060_merge_20241007_1441"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HaieDepartmentConfig",
            new_name="ConfigHaie",
        ),
        migrations.RenameModel(
            old_name="MoulinetteConfig",
            new_name="ConfigAmenagement",
        ),
        migrations.AlterField(
            model_name="moulinettetemplate",
            name="config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="templates",
                to="moulinette.configamenagement",
                verbose_name="Config",
            ),
        ),
    ]
