# Generated by Django 4.2.13 on 2024-10-07 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0016_alter_department_geometry"),
        ("moulinette", "0061_rename_haiedepartmentconfig_confighaie_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configamenagement",
            options={
                "verbose_name": "Config amenagement",
                "verbose_name_plural": "Configs amenagement",
            },
        ),
        migrations.AlterModelOptions(
            name="confighaie",
            options={
                "verbose_name": "Config haie",
                "verbose_name_plural": "Configs haie",
            },
        ),
        migrations.AlterField(
            model_name="configamenagement",
            name="department",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s",
                to="geodata.department",
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="confighaie",
            name="department",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s",
                to="geodata.department",
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="confighaie",
            name="is_activated",
            field=models.BooleanField(
                default=False,
                help_text="Is the moulinette available for this department?",
                verbose_name="Is activated",
            ),
        ),
    ]
