# Generated by Django 4.2.13 on 2024-10-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0060_alter_moulinettetemplate_key"),
        ("moulinette", "0062_alter_configamenagement_options_and_more"),
    ]

    operations = []
