# Generated by Django 4.2.13 on 2025-01-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0066_confighaie_demarches_simplifiees_city_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configamenagement",
            name="ep_free_mention",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Espèces protégées > Paragraphe libre",
            ),
        ),
    ]
