# Generated by Django 4.2.13 on 2025-01-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0066_confighaie_demarches_simplifiees_city_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="confighaie",
            name="department_guichet_unique_url",
        ),
        migrations.AlterField(
            model_name="confighaie",
            name="contacts_and_links",
            field=models.TextField(blank=True, verbose_name="Champ html d’information"),
        ),
    ]
