# Generated by Django 4.2.13 on 2025-01-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0067_configamenagement_ep_free_mention"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configamenagement",
            name="criteria_values",
        ),
    ]
