# Generated by Django 4.2.13 on 2025-01-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0067_remove_confighaie_department_guichet_unique_url_and_more"),
        ("moulinette", "0068_remove_configamenagement_criteria_values"),
    ]

    operations = []
