# Generated by Django 4.2.19 on 2025-03-19 11:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0071_confighaie_regulations_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confighaie",
            name="regulations_available",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("loi_sur_leau", "Loi sur l'eau"),
                        ("natura2000", "Natura 2000"),
                        ("eval_env", "Évaluation environnementale"),
                        ("sage", "Règlement de SAGE"),
                        ("conditionnalite_pac", "Conditionnalité PAC"),
                        ("ep", "Espèces protégées"),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
