# Generated by Django 4.2.19 on 2025-04-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0073_alter_confighaie_contacts_and_links_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulation",
            name="has_perimeters",
            field=models.BooleanField(
                default=False,
                help_text="Cocher si l'affichage des résultats pour cette réglementation dépendde variables paramétrées dans le périmètre, par exemple personne decontact, lien internet…",
                verbose_name="Utilise des informations attachées à un périmètre ?",
            ),
        ),
    ]
