# Generated by Django 4.2.19 on 2025-04-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0073_confighaie_hedge_maintenance_html_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confighaie",
            name="contacts_and_links",
            field=models.TextField(
                blank=True, verbose_name="Champ html d’information fléchage"
            ),
        ),
        migrations.AlterField(
            model_name="confighaie",
            name="demarche_simplifiee_number",
            field=models.IntegerField(
                blank=True,
                help_text='Vous trouverez ce numéro en haut à droite de la carte de votre démarche dans la liste suivante : <a href="https://www.demarches-simplifiees.fr/admin/procedures" target="_blank" rel="noopener">https://www.demarches-simplifiees.fr/admin/procedures</a>',
                null=True,
                verbose_name="Numéro de la démarche DS",
            ),
        ),
        migrations.AlterField(
            model_name="confighaie",
            name="demarche_simplifiee_pre_fill_config",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="Configuration pré-remplissage DS",
            ),
        ),
        migrations.AlterField(
            model_name="confighaie",
            name="demarches_simplifiees_city_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name='Identifiant DS "Commune principale"',
            ),
        ),
        migrations.AlterField(
            model_name="confighaie",
            name="demarches_simplifiees_pacage_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name='Identifiant DS "numéro de PACAGE"',
            ),
        ),
        migrations.AlterField(
            model_name="confighaie",
            name="demarches_simplifiees_project_url_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name='Identifiant DS "Lien internet de la simulation réglementaire de votre projet"',
            ),
        ),
        migrations.AlterField(
            model_name="regulation",
            name="has_perimeters",
            field=models.BooleanField(
                default=False,
                help_text="Cocher si l'affichage des résultats pour cette réglementation dépend de variables paramétrées dans le périmètre, par exemple personne de contact, lien internet…",
                verbose_name="Utilise des informations attachées à un périmètre ?",
            ),
        ),
    ]
