# Generated by Django 4.2.19 on 2025-04-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0074_alter_regulation_has_perimeters"),
        ("moulinette", "0074_confighaie_hedge_maintenance_html_and_more"),
    ]

    operations = []
