# Generated by Django 4.2.19 on 2025-04-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0075_merge_20250408_1046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulation",
            name="has_perimeters",
            field=models.BooleanField(
                default=False,
                help_text="Le calcul du résultat dépend de la présence ou non de périmètres, en plus des résultats des critères",
                verbose_name="Réglementation liée aux périmètres ?",
            ),
        ),
    ]
