# Generated by Django 4.2.19 on 2025-04-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0078_regulation_map_factory_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="confighaie",
            name="hedge_to_plant_properties_form",
            field=models.CharField(
                choices=[
                    (
                        "envergo.hedges.forms.HedgeToPlantPropertiesForm",
                        "Caractéristiques de base",
                    ),
                    (
                        "envergo.hedges.forms.HedgeToPlantPropertiesCalvadosForm",
                        "Caractéristiques du Calvados ( + talus, essences non bocagères, type de plantation)",
                    ),
                    (
                        "envergo.hedges.forms.HedgeToPlantPropertiesAisneForm",
                        "Caractéristiques de l'Aisne ( + proximité point d'eau, connexion boisement)",
                    ),
                ],
                default="envergo.hedges.forms.HedgeToPlantPropertiesForm",
                max_length=256,
                verbose_name="Caractéristiques demandées pour les haies à planter",
            ),
        ),
        migrations.AddField(
            model_name="confighaie",
            name="hedge_to_remove_properties_form",
            field=models.CharField(
                choices=[
                    (
                        "envergo.hedges.forms.HedgeToRemovePropertiesForm",
                        "Caractéristiques de base",
                    ),
                    (
                        "envergo.hedges.forms.HedgeToRemovePropertiesCalvadosForm",
                        "Caractéristiques du Calvados ( + talus, essences non bocagères, récemment plantée)",
                    ),
                    (
                        "envergo.hedges.forms.HedgeToRemovePropertiesAisneForm",
                        "Caractéristiques de l'Aisne ( + proximité point d'eau, connexion boisement)",
                    ),
                ],
                default="envergo.hedges.forms.HedgeToRemovePropertiesForm",
                max_length=256,
                verbose_name="Caractéristiques demandées pour les haies à détruire",
            ),
        ),
    ]
