# Generated by Django 4.2.19 on 2025-06-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0079_confighaie_hedge_to_plant_properties_form_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="confighaie",
            name="department_doctrine_html",
            field=models.TextField(
                blank=True, verbose_name="Champ html doctrine département"
            ),
        ),
    ]
