# Generated by Django 4.2.19 on 2025-06-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0080_alter_configamenagement_regulations_available_and_more"),
        ("moulinette", "0080_confighaie_department_doctrine_html_and_more"),
    ]

    operations = []
