# Generated by Django 4.2.19 on 2025-06-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0082_regulation_display_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perimeter",
            name="regulations",
            field=models.ManyToManyField(
                related_name="perimeters_m2m",
                to="moulinette.regulation",
                verbose_name="Regulations",
            ),
        ),
    ]
