# Generated by Django 4.2.19 on 2025-06-13 09:40

from django.db import migrations


def copy_perimeters(apps, schema_editor):
    Perimeter = apps.get_model("moulinette", "Perimeter")
    perimeters = Perimeter.objects.all()
    for perimeter in perimeters:
        perimeter.regulations.add(perimeter.regulation)
        perimeter.save()


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0083_perimeter_regulations"),
    ]

    operations = [migrations.RunPython(copy_perimeters, migrations.RunPython.noop)]
