# Generated by Django 4.2.19 on 2025-06-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0084_copy_perimeters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perimeter",
            name="regulation",
        ),
        migrations.AlterField(
            model_name="perimeter",
            name="regulations",
            field=models.ManyToManyField(
                related_name="perimeters",
                to="moulinette.regulation",
                verbose_name="Regulations",
            ),
        ),
    ]
