# Generated by Django 4.2.21 on 2025-07-08 09:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0085_remove_perimeter_regulation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configamenagement",
            name="regulations_available",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("loi_sur_leau", "Loi sur l'eau"),
                        ("natura2000", "Natura 2000"),
                        ("natura2000_haie", "Natura 2000 Haie"),
                        ("eval_env", "Évaluation environnementale"),
                        ("sage", "Règlement de SAGE"),
                        ("conditionnalite_pac", "Conditionnalité PAC"),
                        ("ep", "Espèces protégées"),
                        ("alignement_arbres", "Alignements d'arbres (L350-3)"),
                        ("urbanisme_haie", "Urbanisme haie"),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="confighaie",
            name="regulations_available",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("loi_sur_leau", "Loi sur l'eau"),
                        ("natura2000", "Natura 2000"),
                        ("natura2000_haie", "Natura 2000 Haie"),
                        ("eval_env", "Évaluation environnementale"),
                        ("sage", "Règlement de SAGE"),
                        ("conditionnalite_pac", "Conditionnalité PAC"),
                        ("ep", "Espèces protégées"),
                        ("alignement_arbres", "Alignements d'arbres (L350-3)"),
                        ("urbanisme_haie", "Urbanisme haie"),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="regulation",
            name="regulation",
            field=models.CharField(
                choices=[
                    ("loi_sur_leau", "Loi sur l'eau"),
                    ("natura2000", "Natura 2000"),
                    ("natura2000_haie", "Natura 2000 Haie"),
                    ("eval_env", "Évaluation environnementale"),
                    ("sage", "Règlement de SAGE"),
                    ("conditionnalite_pac", "Conditionnalité PAC"),
                    ("ep", "Espèces protégées"),
                    ("alignement_arbres", "Alignements d'arbres (L350-3)"),
                    ("urbanisme_haie", "Urbanisme haie"),
                ],
                max_length=64,
                verbose_name="Regulation",
            ),
        ),
    ]
