# Generated by Django 4.2.20 on 2025-07-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0085_remove_perimeter_regulation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="confighaie",
            name="demarches_simplifiees_organization_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name='Identifiant DS "Nom de votre structure"',
            ),
        ),
    ]
