# Generated by Django 4.2.23 on 2025-07-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0086_alter_configamenagement_regulations_available_and_more"),
        ("moulinette", "0086_confighaie_demarches_simplifiees_organization_id"),
    ]

    operations = []
