# Generated by Django 4.2.23 on 2025-09-15 13:14
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def change_casse_envergo(apps, schema_editor):
    MoulinetteTemplate = apps.get_model("moulinette", "MoulinetteTemplate")

    moulinette_templates_with_envergo = MoulinetteTemplate.objects.filter(
        content__contains="EnvErgo"
    )

    count_templates = moulinette_templates_with_envergo.count()
    if count_templates == 0:
        logger.info("No MoulinetteTemplate found with 'EnvErgo'")
    else:
        for moulinette_template in moulinette_templates_with_envergo:
            moulinette_template_new_content = moulinette_template.content.replace(
                "EnvErgo", "Envergo"
            )
            moulinette_templates_with_envergo.update(
                content=moulinette_template_new_content
            )

        logger.info(
            f"Successfully replaced 'EnvErgo' by 'Envergo' in {count_templates} templates"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0088_alter_configamenagement_regulations_available_and_more"),
    ]

    operations = [
        migrations.RunPython(change_casse_envergo, migrations.RunPython.noop)
    ]
