# Generated by Django 4.2.23 on 2025-10-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0089_change_casse_envergo_moulinettetemplate_objects"),
    ]

    operations = [
        migrations.AddField(
            model_name="confighaie",
            name="single_procedure",
            field=models.BooleanField(
                default=False,
                help_text="Le régime unique s'applique dans ce département",
                verbose_name="Régime unique",
            ),
        ),
    ]
