# Generated by Django 4.2.23 on 2025-10-07 13:50

from django.db import migrations
import envergo.moulinette.fields


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0090_confighaie_single_procedure"),
    ]

    operations = [
        migrations.AddField(
            model_name="regulation",
            name="evaluator",
            field=envergo.moulinette.fields.RegulationEvaluatorChoiceField(
                choices=[],
                default="envergo.moulinette.regulations.RegulationEvaluator",
                verbose_name="Evaluator",
            ),
            preserve_default=False,
        ),
    ]
