# Generated by Django 4.2.23 on 2025-11-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0091_regulation_evaluator"),
    ]

    operations = [
        migrations.AddField(
            model_name="confighaie",
            name="demarches_simplifiees_display_config",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
