# Generated by Django 4.2.23 on 2025-10-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0090_criterion_actions_to_take_map_and_more"),
        ("moulinette", "0091_regulation_evaluator"),
    ]

    operations = []
