# Generated by Django 4.2.23 on 2025-11-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0092_alter_moulinettetemplate_key"),
        ("moulinette", "0092_confighaie_demarches_simplifiees_display_fields_and_more"),
    ]

    operations = []
