# Generated by Django 4.2.23 on 2025-11-14 09:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0092_alter_moulinettetemplate_key"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE evaluations_evaluationaction
            RENAME TO moulinette_actiontotake;
            """,
            reverse_sql="""
                ALTER TABLE moulinette_actiontotake
                RENAME TO evaluations_evaluationaction;
                """
        ),
    ]
