# Generated by Django 4.2.23 on 2025-11-14 10:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0093_evaluationaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionToTake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            (
                                "mention_arrete_lse",
                                "Mentionner dans l’arrêté le différé de réalisation des travaux",
                            ),
                            (
                                "depot_pac_lse",
                                "Déposer un porter-à-connaissance auprès de la DDT(M)",
                            ),
                            ("depot_dossier_lse", "Déposer un dossier Loi sur l'eau"),
                            (
                                "etude_zh_lse",
                                "LSE > Réaliser un inventaire zones humides",
                            ),
                            ("etude_zi_lse", "LSE > Réaliser une étude hydraulique"),
                            (
                                "etude_2150",
                                "Réaliser une étude de gestion des eaux pluviales",
                            ),
                            (
                                "depot_etude_impact",
                                "Déposer un dossier d'évaluation environnementale",
                            ),
                            (
                                "depot_cas_par_cas",
                                "Déposer une demande d’examen au cas par cas",
                            ),
                            (
                                "depot_ein",
                                "Réaliser une évaluation des incidences Natura\xa02000",
                            ),
                            (
                                "etude_zh_n2000",
                                "Natura\xa02000 > Réaliser un inventaire zones humides",
                            ),
                            (
                                "etude_zi_n2000",
                                "Natura\xa02000 > Réaliser une étude hydraulique",
                            ),
                            (
                                "pc_cas_par_cas",
                                "L’arrêté préfectoral portant décision suite à l’examen au cas par cas",
                            ),
                            ("pc_ein", "L’évaluation des incidences Natura\xa02000"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Référence de l'action",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("action", "Action"), ("pc", "Pièce complémentaire")],
                        max_length=20,
                        verbose_name="Type d'action",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("instructor", "Un service instruction urbanisme"),
                            ("petitioner", "Un porteur de projet ou maître d'œuvre"),
                        ],
                        max_length=20,
                        verbose_name="Cible",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Ordre")),
                (
                    "label",
                    models.TextField(
                        help_text="Texte de niveau 1", verbose_name="Titre affiché"
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        help_text="Texte de niveau 2, contenu HTML évalué comme un template.",
                        verbose_name="Détails",
                    ),
                ),
                (
                    "documents_to_attach",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        help_text="Valeurs séparées par des virgules sans espace",
                        size=None,
                        verbose_name="référence des pièces complémentaires",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action à mener",
                "verbose_name_plural": "Actions à mener",
                "ordering": ["order"],
            },
        ),
    ]


    # Override database operations to do nothing
    def apply(self, project_state, schema_editor=None, collect_sql=False):
        # only update state, skip database operations
        for op in self.operations:
            op.state_forwards(self.app_label, project_state)
        return project_state

    def unapply(self, project_state, schema_editor=None, collect_sql=False):
        # do nothing
        return project_state
