# Generated by Django 4.2.23 on 2025-11-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0094_confighaie_single_procedure_settings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confighaie",
            name="single_procedure_settings",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Paramètres du régime unique"
            ),
        ),
    ]
