# Generated by Django 4.2.23 on 2025-11-14 10:33

from django.db import migrations, models


def inline_to_templates(apps, schema_editor):
    ActionToTake = apps.get_model("moulinette", "ActionToTake")
    actions = [
        ("mention_arrete_lse", "mention_arrete_lse"),
        ("depot_pac_lse", "depot_pac_lse"),
        ("depot_cas_par_cas", "depot_cas_par_cas"),
        ("depot_dossier_lse", "depot_dossier_lse"),
        ("depot_ein", "depot_ein"),
        ("depot_etude_impact", "depot_etude_impact"),
        ("etude_2150", "etude_2150"),
        ("etude_zh_lse", "etude_zh_lse"),
        ("etude_zi_lse", "etude_zi_lse"),
        ("pc_ein", "pc_ein"),
    ]
    for slug, template in actions:
        ActionToTake.objects.filter(slug=slug).update(
            details=f"moulinette/actions_to_take/{template}.html"
        )

class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0094_actiontotake"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontotake",
            name="details",
            field=models.CharField(
                help_text="Texte de niveau 2, choisir le template correspondant.",
                max_length=255,
                verbose_name="Détails",
            ),
        ),
        migrations.RunPython(inline_to_templates, migrations.RunPython.noop)
    ]
