# Generated by Django 4.2.23 on 2025-11-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0093_merge_20251110_1039"),
        ("moulinette", "0095_alter_actiontotake_details"),
    ]

    operations = []
