# Generated by Django 4.2.23 on 2025-12-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0095_alter_confighaie_single_procedure_settings"),
        ("moulinette", "0096_merge_20251117_1023"),
    ]

    operations = []
