# Generated by Django 4.2.23 on 2025-11-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0094_confighaie_single_procedure_settings_and_more"),
        ("moulinette", "0096_merge_20251117_1023"),
    ]

    operations = []
