# Generated by Django 4.2.23 on 2025-12-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0097_alter_configamenagement_regulations_available_and_more"),
        ("moulinette", "0097_merge_20251201_0636"),
    ]

    operations = []
