# Generated by Django 4.2.23 on 2025-11-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0095_alter_confighaie_single_procedure_settings"),
        ("moulinette", "0097_merge_20251121_1230"),
    ]

    operations = []
