# Generated by Django 4.2.23 on 2025-11-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0097_alter_configamenagement_regulations_available_and_more"),
        ("moulinette", "0098_merge_20251125_1008"),
    ]

    operations = []
