# Generated by Django 4.2.23 on 2025-12-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0098_merge_20251209_1055"),
        ("moulinette", "0099_merge_20251128_1157"),
    ]

    operations = []
