# Generated by Django 4.2.23 on 2026-01-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0099_alter_configamenagement_regulations_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configamenagement",
            name="valid_from",
            field=models.DateField(
                blank=True,
                help_text="Start date (inclusive). Empty = no start limit.",
                null=True,
                verbose_name="Valid from",
            ),
        ),
        migrations.AddField(
            model_name="configamenagement",
            name="valid_until",
            field=models.DateField(
                blank=True,
                help_text="End date (exclusive). Empty = no end limit.",
                null=True,
                verbose_name="Valid until",
            ),
        ),
        migrations.AddField(
            model_name="confighaie",
            name="valid_from",
            field=models.DateField(
                blank=True,
                help_text="Start date (inclusive). Empty = no start limit.",
                null=True,
                verbose_name="Valid from",
            ),
        ),
        migrations.AddField(
            model_name="confighaie",
            name="valid_until",
            field=models.DateField(
                blank=True,
                help_text="End date (exclusive). Empty = no end limit.",
                null=True,
                verbose_name="Valid until",
            ),
        ),
        migrations.AlterField(
            model_name="configamenagement",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="geodata.department",
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="confighaie",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="geodata.department",
                verbose_name="Department",
            ),
        ),
    ]
