# Generated by Django 4.2.23 on 2026-01-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0099_alter_configamenagement_regulations_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterion",
            name="validity_date_end",
            field=models.DateField(
                blank=True, default="", verbose_name="Validity date end"
            ),
        ),
        migrations.AddField(
            model_name="criterion",
            name="validity_date_start",
            field=models.DateField(
                blank=True, default="", verbose_name="Validity date start"
            ),
        ),
    ]
