# Generated by Django 4.2.23 on 2026-01-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0099_alter_configamenagement_regulations_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterion",
            name="validity_date_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de fin de validité"
            ),
        ),
        migrations.AddField(
            model_name="criterion",
            name="validity_date_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de début de validité"
            ),
        ),
    ]
