# Generated by Django 4.2.23 on 2026-01-23 10:14

import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models

from envergo.moulinette.utils import DateRange


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0100_config_validity_dates"),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddConstraint(
            model_name="configamenagement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("valid_from__isnull", True),
                    ("valid_until__isnull", True),
                    ("valid_from__lt", models.F("valid_until")),
                    _connector="OR",
                ),
                name="configamenagement_valid_dates_order",
                violation_error_message="La date de début doit être antérieure à la date de fin.",
            ),
        ),
        migrations.AddConstraint(
            model_name="configamenagement",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("department", "="),
                    (
                        DateRange("valid_from", "valid_until", models.Value("[)")),
                        "&&",
                    ),
                ],
                name="configamenagement_no_overlapping_validity",
                violation_error_message="Cette configuration chevauche une configuration existante pour ce département.",
            ),
        ),
        migrations.AddConstraint(
            model_name="confighaie",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("valid_from__isnull", True),
                    ("valid_until__isnull", True),
                    ("valid_from__lt", models.F("valid_until")),
                    _connector="OR",
                ),
                name="confighaie_valid_dates_order",
                violation_error_message="La date de début doit être antérieure à la date de fin.",
            ),
        ),
        migrations.AddConstraint(
            model_name="confighaie",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("department", "="),
                    (
                        DateRange("valid_from", "valid_until", models.Value("[)")),
                        "&&",
                    ),
                ],
                name="confighaie_no_overlapping_validity",
                violation_error_message="Cette configuration chevauche une configuration existante pour ce département.",
            ),
        ),
    ]
