# Generated by Django 4.2.23 on 2025-12-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0099_alter_configamenagement_regulations_available_and_more"),
        ("moulinette", "0100_merge_20251210_0947"),
    ]

    operations = []
