# Generated by Django 4.2.27 on 2026-01-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0100_criterion_validity_date_end_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="criterion",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("validity_date_start__isnull", True),
                    ("validity_date_end__isnull", True),
                    ("validity_date_end__gte", models.F("validity_date_start")),
                    _connector="OR",
                ),
                name="validity_date_end_gte_start",
            ),
        ),
    ]
