# Generated by Django 4.2.27 on 2026-01-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0100_criterion_validity_date_end_and_more"),
        ("moulinette", "0101_merge_20251219_1145"),
    ]

    operations = []
