# Generated by Django 4.2.27 on 2026-01-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0101_criterion_validity_date_end_gte_start"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="criterion",
            name="validity_date_end_gte_start",
        ),
        migrations.AlterField(
            model_name="criterion",
            name="validity_date_end",
            field=models.DateField(
                blank=True,
                help_text="Date exclue : le critère ne sera plus valide ce jour là.",
                null=True,
                verbose_name="Date de fin de validité",
            ),
        ),
        migrations.AlterField(
            model_name="criterion",
            name="validity_date_start",
            field=models.DateField(
                blank=True,
                help_text="Date incluse : le critère est valide dés ce jour-là.",
                null=True,
                verbose_name="Date de début de validité",
            ),
        ),
        migrations.AddConstraint(
            model_name="criterion",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("validity_date_start__isnull", True),
                    ("validity_date_end__isnull", True),
                    ("validity_date_end__gt", models.F("validity_date_start")),
                    _connector="OR",
                ),
                name="validity_date_end_gt_start",
            ),
        ),
    ]
