# Generated by Django 4.2.27 on 2026-01-28 10:30

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0102_remove_criterion_validity_date_end_gte_start_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="criterion",
            name="validity_date_end_gt_start",
        ),
        migrations.RemoveField(
            model_name="criterion",
            name="validity_date_end",
        ),
        migrations.RemoveField(
            model_name="criterion",
            name="validity_date_start",
        ),
        migrations.AddField(
            model_name="criterion",
            name="validity_range",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                blank=True, null=True, verbose_name="Dates de validité"
            ),
        ),
        migrations.AlterField(
            model_name="criterion",
            name="is_optional",
            field=models.BooleanField(
                default=False,
                help_text="Ne s'applique que sur activation expresse de l'utilisateur (questions «\xa0optionnelles\xa0»)",
                verbose_name="Is optional",
            ),
        ),
        migrations.AddConstraint(
            model_name="criterion",
            constraint=models.CheckConstraint(
                check=models.Q(("validity_range__isempty", False)),
                name="validity_range_non_empty",
                violation_error_message="La date de fin de validité doit être supérieure à la date de début",
            ),
        ),
    ]
