# Generated by Django 4.2.27 on 2026-01-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0101_criterion_validity_date_end_gte_start"),
        ("moulinette", "0102_merge_20260116_0820"),
    ]

    operations = []
