# Generated by Django 4.2.27 on 2026-02-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0103_remove_criterion_validity_date_end_gt_start_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontotake",
            name="slug",
            field=models.CharField(
                choices=[
                    (
                        "mention_arrete_lse",
                        "Mentionner dans l’arrêté le différé de réalisation des travaux",
                    ),
                    (
                        "depot_pac_lse",
                        "Déposer un porter-à-connaissance auprès de la DDT(M)",
                    ),
                    ("depot_dossier_lse", "Déposer un dossier Loi sur l'eau"),
                    ("etude_zh_lse", "LSE > Réaliser un inventaire zones humides"),
                    ("etude_zi_lse", "LSE > Réaliser une étude hydraulique"),
                    ("etude_2150", "Réaliser une étude de gestion des eaux pluviales"),
                    (
                        "depot_etude_impact",
                        "Déposer un dossier d'évaluation environnementale",
                    ),
                    (
                        "depot_cas_par_cas",
                        "Déposer une demande d’examen au cas par cas",
                    ),
                    (
                        "depot_ein",
                        "Réaliser une évaluation des incidences Natura\xa02000",
                    ),
                    (
                        "etude_zh_n2000",
                        "Natura\xa02000 > Réaliser un inventaire zones humides",
                    ),
                    (
                        "etude_zi_n2000",
                        "Natura\xa02000 > Réaliser une étude hydraulique",
                    ),
                    (
                        "pc_cas_par_cas",
                        "L’arrêté préfectoral portant décision suite à l’examen au cas par cas",
                    ),
                    ("pc_ein", "L’évaluation des incidences Natura\xa02000"),
                    ("pc_etude_impact", "L'étude d'impact"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Référence de l'action",
            ),
        ),
    ]
