# Generated by Django 4.2.27 on 2026-01-27 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0102_remove_criterion_validity_date_end_gte_start_and_more"),
        ("moulinette", "0103_merge_20260123_1016"),
    ]

    operations = []
