# Generated by Django 4.2.28 on 2026-02-16 08:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0104_alter_actiontotake_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontotake",
            name="slug",
            field=models.CharField(
                choices=[
                    ("mention_arrete_lse", "Mention arrêté LSE"),
                    ("depot_pac_lse", "Dépôt PAC LSE"),
                    ("depot_dossier_lse", "Dépôt dossier LSE"),
                    ("etude_zh", "Étude ZH"),
                    ("etude_zi_lse", "Étude ZI LSE"),
                    ("etude_2150", "Étude 2150"),
                    ("depot_etude_impact", "Dépôt étude impact"),
                    ("depot_cas_par_cas", "Dépôt cas par cas"),
                    ("depot_ein", "Dépôt EIN"),
                    ("etude_zi_n2000", "Étude ZI Natura\xa02000"),
                    ("interdit_sage", "Interdit SAGE"),
                    ("pc_cas_par_cas", "PC cas par cas"),
                    ("pc_ein", "PC EIN"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Référence de l'action",
            ),
        ),
    ]
