# Generated by Django 4.2.28 on 2026-02-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0104_alter_actiontotake_slug"),
        ("moulinette", "0104_config_validity_range"),
    ]

    operations = []
