# Generated by Django 4.2.27 on 2026-01-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0103_remove_criterion_validity_date_end_gt_start_and_more"),
        ("moulinette", "0104_merge_20260127_0917"),
    ]

    operations = []
