# Generated by Django 4.2.28 on 2026-02-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0105_alter_actiontotake_slug_and_more"),
        ("moulinette", "0105_merge_20260219_1028"),
    ]

    operations = []
