# Generated by Django 4.2.27 on 2026-02-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0104_alter_actiontotake_slug"),
        ("moulinette", "0105_merge_20260128_1145"),
    ]

    operations = []
