# Generated by Django 4.2.23 on 2026-02-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0104_config_validity_range"),
        ("moulinette", "0106_merge_20260206_1007"),
    ]

    operations = []
