# Generated by Django 4.2.27 on 2026-02-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0104_alter_actiontotake_slug_and_more"),
        ("moulinette", "0107_merge_20260206_1657"),
    ]

    operations = []
