# Generated by Django 4.2.28 on 2026-03-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0106_merge_20260224_1127"),
        ("moulinette", "0107_alter_configamenagement_regulations_available_and_more"),
    ]

    operations = []
