# Generated by Django 4.2.28 on 2026-02-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0105_alter_actiontotake_slug_and_more"),
        ("moulinette", "0108_merge_20260212_1216"),
    ]

    operations = []
