# Generated by Django 4.2.28 on 2026-03-18 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "moulinette",
            "0106_remove_confighaie_single_procedure_requires_coeff_compensation_and_more",
        ),
        ("moulinette", "0108_merge_20260317_1225"),
    ]

    operations = []
