# Generated by Django 4.2.28 on 2026-02-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0105_merge_20260219_1028"),
        ("moulinette", "0109_merge_20260216_0952"),
    ]

    operations = []
