# Generated by Django 4.2.28 on 2026-03-20 09:25

import django.contrib.postgres.fields
from django.db import migrations, models

def switch_base_to_ru(apps, schema_editor):
    ConfigHaie = apps.get_model("moulinette", "ConfigHaie")
    (ConfigHaie.objects
     .filter(hedge_to_plant_properties_form="envergo.hedges.forms.HedgeToPlantPropertiesForm")
     .update(hedge_to_plant_properties_form="envergo.hedges.forms.HedgeToPlantPropertiesRegimeUniqueForm"))

    (ConfigHaie.objects
     .filter(hedge_to_remove_properties_form="envergo.hedges.forms.HedgeToRemovePropertiesForm")
     .update(hedge_to_remove_properties_form="envergo.hedges.forms.HedgeToRemovePropertiesRegimeUniqueForm"))

def switch_proximite_point_eau_to_ripisylve(apps, schema_editor):
    schema_editor.execute(
        'UPDATE hedges_hedgedata '
        'SET data = REPLACE(data::text, \'"proximite_point_eau"\', \'"ripisylve"\')::jsonb '
        'WHERE data::text LIKE \'%%proximite_point_eau%%\''
    )


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0109_merge_20260318_0620"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontotake",
            name="slug",
            field=models.CharField(
                choices=[
                    ("mention_arrete_lse", "Mention arrêté LSE"),
                    ("depot_pac_lse", "Dépôt PAC LSE"),
                    ("depot_dossier_lse", "Dépôt dossier LSE"),
                    ("etude_zh", "Étude ZH"),
                    ("etude_zi_lse", "Étude ZI LSE"),
                    ("etude_2150", "Étude 2150"),
                    ("depot_etude_impact", "Dépôt étude impact"),
                    ("depot_cas_par_cas", "Dépôt cas par cas"),
                    ("depot_ein", "Dépôt EIN"),
                    ("etude_zi_n2000", "Étude ZI Natura\xa02000"),
                    ("interdit_sage", "Interdit SAGE"),
                    ("pc_cas_par_cas", "PC cas par cas"),
                    ("pc_ein", "PC EIN"),
                    ("pc_etude_impact", "PC étude impact"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Référence de l'action",
            ),
        ),
        migrations.AlterField(
            model_name="configamenagement",
            name="regulations_available",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("loi_sur_leau", "Loi sur l'eau"),
                        ("natura2000", "Natura 2000"),
                        ("natura2000_haie", "Natura 2000 Haie"),
                        ("eval_env", "Évaluation environnementale"),
                        ("sage", "Règlement de SAGE"),
                        ("conditionnalite_pac", "Conditionnalité PAC"),
                        ("ep", "Espèces protégées"),
                        ("alignement_arbres", "Alignements d'arbres (L350-3)"),
                        ("urbanisme_haie", "Urbanisme haie"),
                        ("reserves_naturelles", "Réserves naturelles"),
                        ("code_rural_haie", "Code rural"),
                        ("regime_unique_haie", "Régime unique haie"),
                        ("sites_proteges_haie", "Sites protégés"),
                        ("sites_inscrits_haie", "Sites inscrits"),
                        ("sites_classes_haie", "Sites classés"),
                        ("protection_captages", "Protection de captages"),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="confighaie",
            name="hedge_to_plant_properties_form",
            field=models.CharField(
                choices=[
                    (
                        "envergo.hedges.forms.HedgeToPlantPropertiesRegimeUniqueForm",
                        "Régime unique",
                    ),
                    (
                        "envergo.hedges.forms.HedgeToPlantPropertiesCalvadosForm",
                        "Calvados avant r.u. (interchamp, talus, essences non bocagères, type de plantation)",
                    ),
                    (
                        "envergo.hedges.forms.HedgeToPlantPropertiesAisneForm",
                        "Aisne avant r.u. (connexion boisement)",
                    ),
                ],
                default="envergo.hedges.forms.HedgeToPlantPropertiesRegimeUniqueForm",
                max_length=256,
                verbose_name="Caractéristiques demandées pour les haies à planter",
            ),
        ),
        migrations.AlterField(
            model_name="confighaie",
            name="hedge_to_remove_properties_form",
            field=models.CharField(
                choices=[
                    (
                        "envergo.hedges.forms.HedgeToRemovePropertiesRegimeUniqueForm",
                        "Régime unique",
                    ),
                    (
                        "envergo.hedges.forms.HedgeToRemovePropertiesCalvadosForm",
                        "Calvados avant r.u. (interchamp, talus, essences non bocagères, type de plantation)",
                    ),
                    (
                        "envergo.hedges.forms.HedgeToRemovePropertiesAisneForm",
                        "Aisne avant r.u. (connexion boisement)",
                    ),
                ],
                default="envergo.hedges.forms.HedgeToRemovePropertiesRegimeUniqueForm",
                max_length=256,
                verbose_name="Caractéristiques demandées pour les haies à détruire",
            ),
        ),
        migrations.AlterField(
            model_name="confighaie",
            name="regulations_available",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("loi_sur_leau", "Loi sur l'eau"),
                        ("natura2000", "Natura 2000"),
                        ("natura2000_haie", "Natura 2000 Haie"),
                        ("eval_env", "Évaluation environnementale"),
                        ("sage", "Règlement de SAGE"),
                        ("conditionnalite_pac", "Conditionnalité PAC"),
                        ("ep", "Espèces protégées"),
                        ("alignement_arbres", "Alignements d'arbres (L350-3)"),
                        ("urbanisme_haie", "Urbanisme haie"),
                        ("reserves_naturelles", "Réserves naturelles"),
                        ("code_rural_haie", "Code rural"),
                        ("regime_unique_haie", "Régime unique haie"),
                        ("sites_proteges_haie", "Sites protégés"),
                        ("sites_inscrits_haie", "Sites inscrits"),
                        ("sites_classes_haie", "Sites classés"),
                        ("protection_captages", "Protection de captages"),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="moulinettetemplate",
            name="key",
            field=models.CharField(
                choices=[
                    ("autorisation_urba_pa", "autorisation_urba_pa"),
                    (
                        "autorisation_urba_pa_lotissement",
                        "autorisation_urba_pa_lotissement",
                    ),
                    ("autorisation_urba_pc", "autorisation_urba_pc"),
                    (
                        "autorisation_urba_amenagement_dp",
                        "autorisation_urba_amenagement_dp",
                    ),
                    (
                        "autorisation_urba_construction_dp",
                        "autorisation_urba_construction_dp",
                    ),
                    ("autorisation_urba_none", "autorisation_urba_none"),
                    ("autorisation_urba_other", "autorisation_urba_other"),
                    (
                        "alignement_arbres/alignement_arbres_non_soumis.html",
                        "alignement_arbres/alignement_arbres_non_soumis.html",
                    ),
                    (
                        "alignement_arbres/alignement_arbres_soumis_autorisation.html",
                        "alignement_arbres/alignement_arbres_soumis_autorisation.html",
                    ),
                    (
                        "alignement_arbres/alignement_arbres_soumis_esthetique.html",
                        "alignement_arbres/alignement_arbres_soumis_esthetique.html",
                    ),
                    (
                        "alignement_arbres/alignement_arbres_soumis_securite.html",
                        "alignement_arbres/alignement_arbres_soumis_securite.html",
                    ),
                    (
                        "alignement_arbres/result_non_active.html",
                        "alignement_arbres/result_non_active.html",
                    ),
                    (
                        "alignement_arbres/result_non_disponible.html",
                        "alignement_arbres/result_non_disponible.html",
                    ),
                    (
                        "code_rural_haie/code_rural_a_verifier.html",
                        "code_rural_haie/code_rural_a_verifier.html",
                    ),
                    (
                        "code_rural_haie/result_non_active.html",
                        "code_rural_haie/result_non_active.html",
                    ),
                    (
                        "code_rural_haie/result_non_disponible.html",
                        "code_rural_haie/result_non_disponible.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_dispense_petit.html",
                        "conditionnalite_pac/bcae8_dispense_petit.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_interdit_amelioration_culture.html",
                        "conditionnalite_pac/bcae8_interdit_amelioration_culture.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_interdit_amelioration_ecologique.html",
                        "conditionnalite_pac/bcae8_interdit_amelioration_ecologique.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_interdit_amenagement.html",
                        "conditionnalite_pac/bcae8_interdit_amenagement.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_interdit_autre.html",
                        "conditionnalite_pac/bcae8_interdit_autre.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_interdit_chemin_acces.html",
                        "conditionnalite_pac/bcae8_interdit_chemin_acces.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_interdit_embellissement.html",
                        "conditionnalite_pac/bcae8_interdit_embellissement.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_interdit_meilleur_emplacement.html",
                        "conditionnalite_pac/bcae8_interdit_meilleur_emplacement.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_interdit_securite.html",
                        "conditionnalite_pac/bcae8_interdit_securite.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_interdit_transfert_parcelles.html",
                        "conditionnalite_pac/bcae8_interdit_transfert_parcelles.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_non_soumis.html",
                        "conditionnalite_pac/bcae8_non_soumis.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_soumis_amenagement.html",
                        "conditionnalite_pac/bcae8_soumis_amenagement.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_soumis_chemin_acces.html",
                        "conditionnalite_pac/bcae8_soumis_chemin_acces.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_soumis_fosse.html",
                        "conditionnalite_pac/bcae8_soumis_fosse.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_soumis_incendie.html",
                        "conditionnalite_pac/bcae8_soumis_incendie.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_soumis_maladie.html",
                        "conditionnalite_pac/bcae8_soumis_maladie.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_soumis_meilleur_emplacement.html",
                        "conditionnalite_pac/bcae8_soumis_meilleur_emplacement.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_soumis_remplacement.html",
                        "conditionnalite_pac/bcae8_soumis_remplacement.html",
                    ),
                    (
                        "conditionnalite_pac/bcae8_soumis_transfert_parcelles.html",
                        "conditionnalite_pac/bcae8_soumis_transfert_parcelles.html",
                    ),
                    (
                        "conditionnalite_pac/result_non_active.html",
                        "conditionnalite_pac/result_non_active.html",
                    ),
                    (
                        "conditionnalite_pac/result_non_disponible.html",
                        "conditionnalite_pac/result_non_disponible.html",
                    ),
                    (
                        "ep/ep_aisne_derogation_inventaire.html",
                        "ep/ep_aisne_derogation_inventaire.html",
                    ),
                    (
                        "ep/ep_aisne_derogation_simplifiee.html",
                        "ep/ep_aisne_derogation_simplifiee.html",
                    ),
                    ("ep/ep_aisne_interdit.html", "ep/ep_aisne_interdit.html"),
                    (
                        "ep/ep_normandie_a_verifier_L350.html",
                        "ep/ep_normandie_a_verifier_L350.html",
                    ),
                    (
                        "ep/ep_normandie_derogation_simplifiee.html",
                        "ep/ep_normandie_derogation_simplifiee.html",
                    ),
                    ("ep/ep_normandie_dispense.html", "ep/ep_normandie_dispense.html"),
                    (
                        "ep/ep_normandie_dispense_10m.html",
                        "ep/ep_normandie_dispense_10m.html",
                    ),
                    (
                        "ep/ep_normandie_dispense_20m.html",
                        "ep/ep_normandie_dispense_20m.html",
                    ),
                    (
                        "ep/ep_normandie_dispense_L350.html",
                        "ep/ep_normandie_dispense_L350.html",
                    ),
                    (
                        "ep/ep_normandie_dispense_coupe_a_blanc.html",
                        "ep/ep_normandie_dispense_coupe_a_blanc.html",
                    ),
                    ("ep/ep_normandie_interdit.html", "ep/ep_normandie_interdit.html"),
                    ("ep/ep_simple_soumis.html", "ep/ep_simple_soumis.html"),
                    ("ep/result_non_active.html", "ep/result_non_active.html"),
                    ("ep/result_non_disponible.html", "ep/result_non_disponible.html"),
                    (
                        "eval_env/aire_de_stationnement_cas_par_cas.html",
                        "eval_env/aire_de_stationnement_cas_par_cas.html",
                    ),
                    (
                        "eval_env/aire_de_stationnement_non_soumis.html",
                        "eval_env/aire_de_stationnement_non_soumis.html",
                    ),
                    (
                        "eval_env/autres_rubriques_non_disponible.html",
                        "eval_env/autres_rubriques_non_disponible.html",
                    ),
                    (
                        "eval_env/camping_cas_par_cas.html",
                        "eval_env/camping_cas_par_cas.html",
                    ),
                    (
                        "eval_env/camping_non_soumis.html",
                        "eval_env/camping_non_soumis.html",
                    ),
                    (
                        "eval_env/camping_systematique.html",
                        "eval_env/camping_systematique.html",
                    ),
                    (
                        "eval_env/clause_filet_clause_filet.html",
                        "eval_env/clause_filet_clause_filet.html",
                    ),
                    (
                        "eval_env/defrichement_deboisement_cas_par_cas.html",
                        "eval_env/defrichement_deboisement_cas_par_cas.html",
                    ),
                    (
                        "eval_env/defrichement_deboisement_non_soumis.html",
                        "eval_env/defrichement_deboisement_non_soumis.html",
                    ),
                    (
                        "eval_env/emprise_cas_par_cas.html",
                        "eval_env/emprise_cas_par_cas.html",
                    ),
                    (
                        "eval_env/emprise_non_soumis.html",
                        "eval_env/emprise_non_soumis.html",
                    ),
                    (
                        "eval_env/emprise_systematique.html",
                        "eval_env/emprise_systematique.html",
                    ),
                    (
                        "eval_env/photovoltaique_cas_par_cas_ombriere.html",
                        "eval_env/photovoltaique_cas_par_cas_ombriere.html",
                    ),
                    (
                        "eval_env/photovoltaique_cas_par_cas_sol.html",
                        "eval_env/photovoltaique_cas_par_cas_sol.html",
                    ),
                    (
                        "eval_env/photovoltaique_cas_par_cas_toiture.html",
                        "eval_env/photovoltaique_cas_par_cas_toiture.html",
                    ),
                    (
                        "eval_env/photovoltaique_non_soumis.html",
                        "eval_env/photovoltaique_non_soumis.html",
                    ),
                    (
                        "eval_env/photovoltaique_non_soumis_ombriere.html",
                        "eval_env/photovoltaique_non_soumis_ombriere.html",
                    ),
                    (
                        "eval_env/photovoltaique_non_soumis_toiture.html",
                        "eval_env/photovoltaique_non_soumis_toiture.html",
                    ),
                    (
                        "eval_env/photovoltaique_systematique_sol.html",
                        "eval_env/photovoltaique_systematique_sol.html",
                    ),
                    (
                        "eval_env/photovoltaique_systematique_toiture.html",
                        "eval_env/photovoltaique_systematique_toiture.html",
                    ),
                    (
                        "eval_env/piste_cyclable_cas_par_cas.html",
                        "eval_env/piste_cyclable_cas_par_cas.html",
                    ),
                    (
                        "eval_env/piste_cyclable_non_soumis.html",
                        "eval_env/piste_cyclable_non_soumis.html",
                    ),
                    (
                        "eval_env/premier_boisement_cas_par_cas.html",
                        "eval_env/premier_boisement_cas_par_cas.html",
                    ),
                    (
                        "eval_env/premier_boisement_non_soumis.html",
                        "eval_env/premier_boisement_non_soumis.html",
                    ),
                    (
                        "eval_env/result_cas_par_cas.html",
                        "eval_env/result_cas_par_cas.html",
                    ),
                    (
                        "eval_env/result_non_active.html",
                        "eval_env/result_non_active.html",
                    ),
                    (
                        "eval_env/result_non_disponible.html",
                        "eval_env/result_non_disponible.html",
                    ),
                    (
                        "eval_env/result_non_soumis.html",
                        "eval_env/result_non_soumis.html",
                    ),
                    (
                        "eval_env/result_systematique.html",
                        "eval_env/result_systematique.html",
                    ),
                    (
                        "eval_env/route_publique_cas_par_cas.html",
                        "eval_env/route_publique_cas_par_cas.html",
                    ),
                    (
                        "eval_env/route_publique_non_soumis.html",
                        "eval_env/route_publique_non_soumis.html",
                    ),
                    (
                        "eval_env/route_publique_systematique.html",
                        "eval_env/route_publique_systematique.html",
                    ),
                    (
                        "eval_env/sport_loisir_culture_cas_par_cas.html",
                        "eval_env/sport_loisir_culture_cas_par_cas.html",
                    ),
                    (
                        "eval_env/sport_loisir_culture_non_soumis.html",
                        "eval_env/sport_loisir_culture_non_soumis.html",
                    ),
                    (
                        "eval_env/sport_loisir_culture_non_soumis_lt1000.html",
                        "eval_env/sport_loisir_culture_non_soumis_lt1000.html",
                    ),
                    (
                        "eval_env/surface_plancher_cas_par_cas.html",
                        "eval_env/surface_plancher_cas_par_cas.html",
                    ),
                    (
                        "eval_env/surface_plancher_non_soumis.html",
                        "eval_env/surface_plancher_non_soumis.html",
                    ),
                    (
                        "eval_env/terrain_assiette_cas_par_cas.html",
                        "eval_env/terrain_assiette_cas_par_cas.html",
                    ),
                    (
                        "eval_env/terrain_assiette_non_concerne.html",
                        "eval_env/terrain_assiette_non_concerne.html",
                    ),
                    (
                        "eval_env/terrain_assiette_non_soumis.html",
                        "eval_env/terrain_assiette_non_soumis.html",
                    ),
                    (
                        "eval_env/terrain_assiette_systematique.html",
                        "eval_env/terrain_assiette_systematique.html",
                    ),
                    (
                        "eval_env/voie_privee_cas_par_cas.html",
                        "eval_env/voie_privee_cas_par_cas.html",
                    ),
                    (
                        "eval_env/voie_privee_non_soumis.html",
                        "eval_env/voie_privee_non_soumis.html",
                    ),
                    (
                        "loi_sur_leau/autres_rubriques_non_disponible.html",
                        "loi_sur_leau/autres_rubriques_non_disponible.html",
                    ),
                    (
                        "loi_sur_leau/ecoulement_avec_bv_action_requise.html",
                        "loi_sur_leau/ecoulement_avec_bv_action_requise.html",
                    ),
                    (
                        "loi_sur_leau/ecoulement_avec_bv_action_requise_probable_1ha.html",
                        "loi_sur_leau/ecoulement_avec_bv_action_requise_probable_1ha.html",
                    ),
                    (
                        "loi_sur_leau/ecoulement_avec_bv_action_requise_pv_sol.html",
                        "loi_sur_leau/ecoulement_avec_bv_action_requise_pv_sol.html",
                    ),
                    (
                        "loi_sur_leau/ecoulement_avec_bv_non_soumis.html",
                        "loi_sur_leau/ecoulement_avec_bv_non_soumis.html",
                    ),
                    (
                        "loi_sur_leau/ecoulement_avec_bv_non_soumis_pv_sol.html",
                        "loi_sur_leau/ecoulement_avec_bv_non_soumis_pv_sol.html",
                    ),
                    (
                        "loi_sur_leau/ecoulement_avec_bv_soumis.html",
                        "loi_sur_leau/ecoulement_avec_bv_soumis.html",
                    ),
                    (
                        "loi_sur_leau/ecoulement_avec_bv_soumis_ou_pac.html",
                        "loi_sur_leau/ecoulement_avec_bv_soumis_ou_pac.html",
                    ),
                    (
                        "loi_sur_leau/ecoulement_sans_bv_action_requise.html",
                        "loi_sur_leau/ecoulement_sans_bv_action_requise.html",
                    ),
                    (
                        "loi_sur_leau/ecoulement_sans_bv_action_requise_pv_sol.html",
                        "loi_sur_leau/ecoulement_sans_bv_action_requise_pv_sol.html",
                    ),
                    (
                        "loi_sur_leau/ecoulement_sans_bv_non_soumis.html",
                        "loi_sur_leau/ecoulement_sans_bv_non_soumis.html",
                    ),
                    (
                        "loi_sur_leau/ecoulement_sans_bv_non_soumis_pv_sol.html",
                        "loi_sur_leau/ecoulement_sans_bv_non_soumis_pv_sol.html",
                    ),
                    (
                        "loi_sur_leau/ecoulement_sans_bv_soumis.html",
                        "loi_sur_leau/ecoulement_sans_bv_soumis.html",
                    ),
                    (
                        "loi_sur_leau/ecoulement_sans_bv_soumis_ou_pac.html",
                        "loi_sur_leau/ecoulement_sans_bv_soumis_ou_pac.html",
                    ),
                    (
                        "loi_sur_leau/result_action_requise.html",
                        "loi_sur_leau/result_action_requise.html",
                    ),
                    (
                        "loi_sur_leau/result_non_active.html",
                        "loi_sur_leau/result_non_active.html",
                    ),
                    (
                        "loi_sur_leau/result_non_disponible.html",
                        "loi_sur_leau/result_non_disponible.html",
                    ),
                    (
                        "loi_sur_leau/result_non_soumis.html",
                        "loi_sur_leau/result_non_soumis.html",
                    ),
                    (
                        "loi_sur_leau/result_soumis.html",
                        "loi_sur_leau/result_soumis.html",
                    ),
                    (
                        "loi_sur_leau/result_soumis_ou_pac.html",
                        "loi_sur_leau/result_soumis_ou_pac.html",
                    ),
                    (
                        "loi_sur_leau/zone_humide_action_requise.html",
                        "loi_sur_leau/zone_humide_action_requise.html",
                    ),
                    (
                        "loi_sur_leau/zone_humide_action_requise_dans_doute.html",
                        "loi_sur_leau/zone_humide_action_requise_dans_doute.html",
                    ),
                    (
                        "loi_sur_leau/zone_humide_action_requise_proche.html",
                        "loi_sur_leau/zone_humide_action_requise_proche.html",
                    ),
                    (
                        "loi_sur_leau/zone_humide_action_requise_tout_dpt.html",
                        "loi_sur_leau/zone_humide_action_requise_tout_dpt.html",
                    ),
                    (
                        "loi_sur_leau/zone_humide_non_concerne.html",
                        "loi_sur_leau/zone_humide_non_concerne.html",
                    ),
                    (
                        "loi_sur_leau/zone_humide_non_soumis.html",
                        "loi_sur_leau/zone_humide_non_soumis.html",
                    ),
                    (
                        "loi_sur_leau/zone_humide_soumis.html",
                        "loi_sur_leau/zone_humide_soumis.html",
                    ),
                    (
                        "loi_sur_leau/zone_inondable_action_requise.html",
                        "loi_sur_leau/zone_inondable_action_requise.html",
                    ),
                    (
                        "loi_sur_leau/zone_inondable_action_requise_dans_doute.html",
                        "loi_sur_leau/zone_inondable_action_requise_dans_doute.html",
                    ),
                    (
                        "loi_sur_leau/zone_inondable_non_concerne.html",
                        "loi_sur_leau/zone_inondable_non_concerne.html",
                    ),
                    (
                        "loi_sur_leau/zone_inondable_non_soumis.html",
                        "loi_sur_leau/zone_inondable_non_soumis.html",
                    ),
                    (
                        "loi_sur_leau/zone_inondable_soumis.html",
                        "loi_sur_leau/zone_inondable_soumis.html",
                    ),
                    (
                        "loi_sur_leau/zone_inondable_soumis_ou_pac.html",
                        "loi_sur_leau/zone_inondable_soumis_ou_pac.html",
                    ),
                    (
                        "natura2000/autorisation_urba_a_verifier.html",
                        "natura2000/autorisation_urba_a_verifier.html",
                    ),
                    (
                        "natura2000/autorisation_urba_non_soumis.html",
                        "natura2000/autorisation_urba_non_soumis.html",
                    ),
                    (
                        "natura2000/autorisation_urba_non_soumis_lotissement.html",
                        "natura2000/autorisation_urba_non_soumis_lotissement.html",
                    ),
                    (
                        "natura2000/autorisation_urba_soumis.html",
                        "natura2000/autorisation_urba_soumis.html",
                    ),
                    (
                        "natura2000/eval_env_non_soumis.html",
                        "natura2000/eval_env_non_soumis.html",
                    ),
                    (
                        "natura2000/eval_env_soumis_cas_par_cas.html",
                        "natura2000/eval_env_soumis_cas_par_cas.html",
                    ),
                    (
                        "natura2000/eval_env_soumis_systematique.html",
                        "natura2000/eval_env_soumis_systematique.html",
                    ),
                    (
                        "natura2000/iota_iota_a_verifier.html",
                        "natura2000/iota_iota_a_verifier.html",
                    ),
                    (
                        "natura2000/iota_non_soumis.html",
                        "natura2000/iota_non_soumis.html",
                    ),
                    ("natura2000/iota_soumis.html", "natura2000/iota_soumis.html"),
                    (
                        "natura2000/result_a_verifier.html",
                        "natura2000/result_a_verifier.html",
                    ),
                    (
                        "natura2000/result_action_requise.html",
                        "natura2000/result_action_requise.html",
                    ),
                    (
                        "natura2000/result_iota_a_verifier.html",
                        "natura2000/result_iota_a_verifier.html",
                    ),
                    (
                        "natura2000/result_non_active.html",
                        "natura2000/result_non_active.html",
                    ),
                    (
                        "natura2000/result_non_concerne.html",
                        "natura2000/result_non_concerne.html",
                    ),
                    (
                        "natura2000/result_non_disponible.html",
                        "natura2000/result_non_disponible.html",
                    ),
                    (
                        "natura2000/result_non_soumis.html",
                        "natura2000/result_non_soumis.html",
                    ),
                    ("natura2000/result_soumis.html", "natura2000/result_soumis.html"),
                    (
                        "natura2000/zone_humide_action_requise_dans_doute.html",
                        "natura2000/zone_humide_action_requise_dans_doute.html",
                    ),
                    (
                        "natura2000/zone_humide_action_requise_proche.html",
                        "natura2000/zone_humide_action_requise_proche.html",
                    ),
                    (
                        "natura2000/zone_humide_non_concerne.html",
                        "natura2000/zone_humide_non_concerne.html",
                    ),
                    (
                        "natura2000/zone_humide_non_soumis.html",
                        "natura2000/zone_humide_non_soumis.html",
                    ),
                    (
                        "natura2000/zone_humide_non_soumis_dans_doute.html",
                        "natura2000/zone_humide_non_soumis_dans_doute.html",
                    ),
                    (
                        "natura2000/zone_humide_non_soumis_proche.html",
                        "natura2000/zone_humide_non_soumis_proche.html",
                    ),
                    (
                        "natura2000/zone_humide_soumis.html",
                        "natura2000/zone_humide_soumis.html",
                    ),
                    (
                        "natura2000/zone_inondable_non_concerne.html",
                        "natura2000/zone_inondable_non_concerne.html",
                    ),
                    (
                        "natura2000/zone_inondable_non_soumis.html",
                        "natura2000/zone_inondable_non_soumis.html",
                    ),
                    (
                        "natura2000/zone_inondable_soumis.html",
                        "natura2000/zone_inondable_soumis.html",
                    ),
                    (
                        "natura2000_haie/natura2000_haie_non_soumis.html",
                        "natura2000_haie/natura2000_haie_non_soumis.html",
                    ),
                    (
                        "natura2000_haie/natura2000_haie_non_soumis_aa.html",
                        "natura2000_haie/natura2000_haie_non_soumis_aa.html",
                    ),
                    (
                        "natura2000_haie/natura2000_haie_soumis.html",
                        "natura2000_haie/natura2000_haie_soumis.html",
                    ),
                    (
                        "natura2000_haie/result_non_active.html",
                        "natura2000_haie/result_non_active.html",
                    ),
                    (
                        "natura2000_haie/result_non_concerne.html",
                        "natura2000_haie/result_non_concerne.html",
                    ),
                    (
                        "natura2000_haie/result_non_disponible.html",
                        "natura2000_haie/result_non_disponible.html",
                    ),
                    (
                        "protection_captages/result_a_verifier.html",
                        "protection_captages/result_a_verifier.html",
                    ),
                    (
                        "protection_captages/result_non_active.html",
                        "protection_captages/result_non_active.html",
                    ),
                    (
                        "protection_captages/result_non_concerne.html",
                        "protection_captages/result_non_concerne.html",
                    ),
                    (
                        "protection_captages/result_non_disponible.html",
                        "protection_captages/result_non_disponible.html",
                    ),
                    (
                        "regime_unique_haie/regime_unique_haie_non_concerne.html",
                        "regime_unique_haie/regime_unique_haie_non_concerne.html",
                    ),
                    (
                        "regime_unique_haie/regime_unique_haie_non_concerne_aa.html",
                        "regime_unique_haie/regime_unique_haie_non_concerne_aa.html",
                    ),
                    (
                        "regime_unique_haie/regime_unique_haie_soumis.html",
                        "regime_unique_haie/regime_unique_haie_soumis.html",
                    ),
                    (
                        "regime_unique_haie/result_non_active.html",
                        "regime_unique_haie/result_non_active.html",
                    ),
                    (
                        "regime_unique_haie/result_non_disponible.html",
                        "regime_unique_haie/result_non_disponible.html",
                    ),
                    (
                        "reserves_naturelles/reserves_naturelles_soumis_autorisation.html",
                        "reserves_naturelles/reserves_naturelles_soumis_autorisation.html",
                    ),
                    (
                        "reserves_naturelles/reserves_naturelles_soumis_declaration.html",
                        "reserves_naturelles/reserves_naturelles_soumis_declaration.html",
                    ),
                    (
                        "reserves_naturelles/result_non_active.html",
                        "reserves_naturelles/result_non_active.html",
                    ),
                    (
                        "reserves_naturelles/result_non_concerne.html",
                        "reserves_naturelles/result_non_concerne.html",
                    ),
                    (
                        "reserves_naturelles/result_non_disponible.html",
                        "reserves_naturelles/result_non_disponible.html",
                    ),
                    (
                        "sage/interdiction_impact_zh_action_requise_dans_doute_interdit.html",
                        "sage/interdiction_impact_zh_action_requise_dans_doute_interdit.html",
                    ),
                    (
                        "sage/interdiction_impact_zh_action_requise_interdit.html",
                        "sage/interdiction_impact_zh_action_requise_interdit.html",
                    ),
                    (
                        "sage/interdiction_impact_zh_action_requise_proche_interdit.html",
                        "sage/interdiction_impact_zh_action_requise_proche_interdit.html",
                    ),
                    (
                        "sage/interdiction_impact_zh_action_requise_tout_dpt_interdit.html",
                        "sage/interdiction_impact_zh_action_requise_tout_dpt_interdit.html",
                    ),
                    (
                        "sage/interdiction_impact_zh_interdit.html",
                        "sage/interdiction_impact_zh_interdit.html",
                    ),
                    (
                        "sage/interdiction_impact_zh_iota_a_verifier.html",
                        "sage/interdiction_impact_zh_iota_a_verifier.html",
                    ),
                    (
                        "sage/interdiction_impact_zh_iota_action_requise_dans_doute_interdit.html",
                        "sage/interdiction_impact_zh_iota_action_requise_dans_doute_interdit.html",
                    ),
                    (
                        "sage/interdiction_impact_zh_iota_action_requise_interdit.html",
                        "sage/interdiction_impact_zh_iota_action_requise_interdit.html",
                    ),
                    (
                        "sage/interdiction_impact_zh_iota_action_requise_proche_interdit.html",
                        "sage/interdiction_impact_zh_iota_action_requise_proche_interdit.html",
                    ),
                    (
                        "sage/interdiction_impact_zh_iota_action_requise_tout_dpt_interdit.html",
                        "sage/interdiction_impact_zh_iota_action_requise_tout_dpt_interdit.html",
                    ),
                    (
                        "sage/interdiction_impact_zh_iota_interdit.html",
                        "sage/interdiction_impact_zh_iota_interdit.html",
                    ),
                    (
                        "sage/interdiction_impact_zh_iota_non_soumis.html",
                        "sage/interdiction_impact_zh_iota_non_soumis.html",
                    ),
                    (
                        "sage/interdiction_impact_zh_iota_non_soumis_dehors.html",
                        "sage/interdiction_impact_zh_iota_non_soumis_dehors.html",
                    ),
                    (
                        "sage/interdiction_impact_zh_non_soumis.html",
                        "sage/interdiction_impact_zh_non_soumis.html",
                    ),
                    (
                        "sage/interdiction_impact_zh_non_soumis_dehors.html",
                        "sage/interdiction_impact_zh_non_soumis_dehors.html",
                    ),
                    ("sage/result_a_verifier.html", "sage/result_a_verifier.html"),
                    (
                        "sage/result_a_verifier_single_perimeter.html",
                        "sage/result_a_verifier_single_perimeter.html",
                    ),
                    (
                        "sage/result_action_requise.html",
                        "sage/result_action_requise.html",
                    ),
                    (
                        "sage/result_action_requise_single_perimeter.html",
                        "sage/result_action_requise_single_perimeter.html",
                    ),
                    ("sage/result_interdit.html", "sage/result_interdit.html"),
                    (
                        "sage/result_interdit_single_perimeter.html",
                        "sage/result_interdit_single_perimeter.html",
                    ),
                    ("sage/result_non_active.html", "sage/result_non_active.html"),
                    ("sage/result_non_concerne.html", "sage/result_non_concerne.html"),
                    (
                        "sage/result_non_disponible.html",
                        "sage/result_non_disponible.html",
                    ),
                    (
                        "sage/result_non_disponible_single_perimeter.html",
                        "sage/result_non_disponible_single_perimeter.html",
                    ),
                    ("sage/result_non_soumis.html", "sage/result_non_soumis.html"),
                    (
                        "sage/result_non_soumis_single_perimeter.html",
                        "sage/result_non_soumis_single_perimeter.html",
                    ),
                    (
                        "sites_classes_haie/result_non_active.html",
                        "sites_classes_haie/result_non_active.html",
                    ),
                    (
                        "sites_classes_haie/result_non_concerne.html",
                        "sites_classes_haie/result_non_concerne.html",
                    ),
                    (
                        "sites_classes_haie/result_non_disponible.html",
                        "sites_classes_haie/result_non_disponible.html",
                    ),
                    (
                        "sites_classes_haie/result_soumis.html",
                        "sites_classes_haie/result_soumis.html",
                    ),
                    (
                        "sites_inscrits_haie/result_non_active.html",
                        "sites_inscrits_haie/result_non_active.html",
                    ),
                    (
                        "sites_inscrits_haie/result_non_concerne.html",
                        "sites_inscrits_haie/result_non_concerne.html",
                    ),
                    (
                        "sites_inscrits_haie/result_non_disponible.html",
                        "sites_inscrits_haie/result_non_disponible.html",
                    ),
                    (
                        "sites_inscrits_haie/result_soumis.html",
                        "sites_inscrits_haie/result_soumis.html",
                    ),
                    (
                        "sites_proteges_haie/result_non_active.html",
                        "sites_proteges_haie/result_non_active.html",
                    ),
                    (
                        "sites_proteges_haie/result_non_concerne.html",
                        "sites_proteges_haie/result_non_concerne.html",
                    ),
                    (
                        "sites_proteges_haie/result_non_disponible.html",
                        "sites_proteges_haie/result_non_disponible.html",
                    ),
                    (
                        "sites_proteges_haie/result_soumis.html",
                        "sites_proteges_haie/result_soumis.html",
                    ),
                    (
                        "urbanisme_haie/urbanisme_haie_a_verifier.html",
                        "urbanisme_haie/urbanisme_haie_a_verifier.html",
                    ),
                ],
                max_length=512,
                verbose_name="Key",
            ),
        ),
        migrations.AlterField(
            model_name="regulation",
            name="regulation",
            field=models.CharField(
                choices=[
                    ("loi_sur_leau", "Loi sur l'eau"),
                    ("natura2000", "Natura 2000"),
                    ("natura2000_haie", "Natura 2000 Haie"),
                    ("eval_env", "Évaluation environnementale"),
                    ("sage", "Règlement de SAGE"),
                    ("conditionnalite_pac", "Conditionnalité PAC"),
                    ("ep", "Espèces protégées"),
                    ("alignement_arbres", "Alignements d'arbres (L350-3)"),
                    ("urbanisme_haie", "Urbanisme haie"),
                    ("reserves_naturelles", "Réserves naturelles"),
                    ("code_rural_haie", "Code rural"),
                    ("regime_unique_haie", "Régime unique haie"),
                    ("sites_proteges_haie", "Sites protégés"),
                    ("sites_inscrits_haie", "Sites inscrits"),
                    ("sites_classes_haie", "Sites classés"),
                    ("protection_captages", "Protection de captages"),
                ],
                max_length=64,
                verbose_name="Regulation",
            ),
        ),
        migrations.RunPython(
            switch_base_to_ru,
            migrations.RunPython.noop
        ),
        migrations.RunPython(
            switch_proximite_point_eau_to_ripisylve,
            migrations.RunPython.noop
        ),
    ]
