# Generated by Django 4.2.28 on 2026-03-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0110_alter_actiontotake_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="confighaie",
            name="contacts_info",
            field=models.TextField(
                blank=True, verbose_name="Champ html des informations de contact"
            ),
        ),
    ]
