# Generated by Django 4.2.28 on 2026-02-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0106_merge_20260224_1127"),
        ("moulinette", "0110_merge_20260219_1138"),
    ]

    operations = []
