# Generated by Django 4.2.28 on 2026-03-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "moulinette",
            "0106_remove_confighaie_single_procedure_requires_coeff_compensation_and_more",
        ),
        ("moulinette", "0111_merge_20260225_0949"),
    ]

    operations = []
