# Generated by Django 4.2.28

from django.db import migrations


def remove_replantation_coefficient(apps, schema_editor):
    Criterion = apps.get_model("moulinette", "Criterion")

    qs = Criterion.objects.filter(
        evaluator_settings__has_key="replantation_coefficient",
    )

    to_update = []
    for criterion in qs:
        del criterion.evaluator_settings["replantation_coefficient"]
        to_update.append(criterion)

    Criterion.objects.bulk_update(to_update, ["evaluator_settings"])


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0111_confighaie_contacts_info"),
    ]

    operations = [
        migrations.RunPython(
            remove_replantation_coefficient,
            migrations.RunPython.noop,
        ),
    ]
