# Generated by Django 4.2.28 on 2026-04-21 07:16

from django.db import migrations


def move_dn_id_fields_to_display_fields(apps, schema_editor):
    """Move DN fields ids to DN display fields JSON."""
    Model = apps.get_model("moulinette", "ConfigHaie")
    for config in Model.objects.all():
        config.demarches_simplifiees_display_fields.update(
            {
                "city": config.demarches_simplifiees_city_id,
                "organization": config.demarches_simplifiees_organization_id,
                "pacage": config.demarches_simplifiees_pacage_id,
                "project_url": config.demarches_simplifiees_project_url_id,
            }
        )
        config.save()


def move_dn_display_fields_to_id_fields(apps, schema_editor):
    """Move DN display fields JSON to DN fields ids."""
    Model = apps.get_model("moulinette", "ConfigHaie")
    for config in Model.objects.all():
        config.demarches_simplifiees_city_id = (
            config.demarches_simplifiees_display_fields["city"]
        )
        config.demarches_simplifiees_organization_id = (
            config.demarches_simplifiees_display_fields["organization"]
        )
        config.demarches_simplifiees_pacage_id = (
            config.demarches_simplifiees_display_fields["pacage"]
        )
        config.demarches_simplifiees_project_url_id = (
            config.demarches_simplifiees_display_fields["project_url"]
        )
        config.save()


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0111_confighaie_contacts_info"),
    ]

    operations = [
        migrations.RunPython(
            move_dn_id_fields_to_display_fields, move_dn_display_fields_to_id_fields
        ),
    ]
