# Generated by Django 4.2.28 on 2026-03-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0106_alter_configamenagement_is_activated_and_more"),
        ("moulinette", "0112_merge_20260306_1438"),
    ]

    operations = []
