# Generated by Django 4.2.28 on 2026-04-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0112_confighaie_aa_l3503_fields"),
        ("moulinette", "0112_remove_replantation_coefficient_setting"),
    ]

    operations = []
