# Generated by Django 4.2.28 on 2026-04-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0111_confighaie_contacts_info"),
        ("moulinette", "0112_migrate_coeff_compensation_format"),
    ]

    operations = []
