# Generated by Django 4.2.28 on 2026-04-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0113_merge_20260413_1454"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="confighaie",
            name="single_procedure_requires_coeff_compensation",
        ),
        migrations.AddField(
            model_name="confighaie",
            name="has_ru_zonage",
            field=models.BooleanField(
                default=False,
                help_text="Activer si un zonage spécifique au régime unique est défini pour ce département.",
                verbose_name="Zonage RU",
            ),
        ),
        migrations.AddConstraint(
            model_name="confighaie",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("single_procedure", False),
                    models.Q(
                        ("has_ru_zonage", True),
                        ("single_procedure_settings__has_key", "coeff_compensation"),
                    ),
                    models.Q(
                        ("has_ru_zonage", False),
                        ("single_procedure_settings__has_key", "coeff_compensation"),
                        (
                            "single_procedure_settings__coeff_compensation__has_key",
                            "default",
                        ),
                        (
                            "single_procedure_settings__coeff_compensation__default__has_key",
                            "X_densite",
                        ),
                        (
                            "single_procedure_settings__coeff_compensation__default__has_key",
                            "R1_non_arboree_HD",
                        ),
                        (
                            "single_procedure_settings__coeff_compensation__default__has_key",
                            "R2_non_arboree_LD",
                        ),
                        (
                            "single_procedure_settings__coeff_compensation__default__has_key",
                            "R3_arboree_HD",
                        ),
                        (
                            "single_procedure_settings__coeff_compensation__default__has_key",
                            "R4_arboree_LD",
                        ),
                    ),
                    _connector="OR",
                ),
                name="single_procedure_requires_coeff_compensation",
                violation_error_message="Les paramètres de régime unique doivent comporter une clé 'coeff_compensation'. Sans zonage, une entrée 'default' avec X_densite, R1_non_arboree_HD, R2_non_arboree_LD, R3_arboree_HD, R4_arboree_LD est requise.",
            ),
        ),
        migrations.AddConstraint(
            model_name="confighaie",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("has_ru_zonage", False),
                    ("single_procedure", True),
                    _connector="OR",
                ),
                name="ru_zonage_requires_single_procedure",
                violation_error_message="Le zonage RU ne peut être activé que si le régime unique est activé.",
            ),
        ),
    ]
