# Generated by Django 4.2.28 on 2026-04-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0113_migrate_dn_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="confighaie",
            name="project_url_id_required_if_demarche_number",
        ),
        migrations.RemoveField(
            model_name="confighaie",
            name="demarches_simplifiees_city_id",
        ),
        migrations.RemoveField(
            model_name="confighaie",
            name="demarches_simplifiees_organization_id",
        ),
        migrations.RemoveField(
            model_name="confighaie",
            name="demarches_simplifiees_pacage_id",
        ),
        migrations.RemoveField(
            model_name="confighaie",
            name="demarches_simplifiees_project_url_id",
        ),
        migrations.AddConstraint(
            model_name="confighaie",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("demarche_simplifiee_number__isnull", True),
                    (
                        "demarches_simplifiees_display_fields__project_url__isnull",
                        False,
                    ),
                    _connector="OR",
                ),
                name="project_url_id_required_if_demarche_number",
            ),
        ),
    ]
