# Generated by Django 4.2.28 on 2026-04-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0112_confighaie_aa_l3503_fields"),
        ("moulinette", "0114_add_has_ru_zonage"),
    ]

    operations = []
