# Generated by Django 4.2.28 on 2026-04-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0112_remove_replantation_coefficient_setting"),
        ("moulinette", "0115_merge_20260417_1047"),
    ]

    operations = []
