# Generated by Django 4.2.28 on 2026-04-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0114_criterion_is_staff_only_alter_moulinettetemplate_key"),
        ("moulinette", "0115_merge_20260428_1037"),
    ]

    operations = []
