# Generated by Django 4.2.28 on 2026-06-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0116_merge_20260504"),
    ]

    operations = [
        migrations.RenameField(
            model_name="confighaie",
            old_name="demarches_simplifiees_display_fields",
            new_name="demarche_numerique_display_fields",
        ),
        migrations.RenameField(
            model_name="confighaie",
            old_name="demarche_simplifiee_number",
            new_name="demarche_numerique_number",
        ),
        migrations.RenameField(
            model_name="confighaie",
            old_name="demarche_simplifiee_pre_fill_config",
            new_name="demarche_numerique_pre_fill_config",
        ),
        migrations.RemoveConstraint(
            model_name="confighaie",
            name="demarche_simplifiee_number_required_if_activated",
        ),
        migrations.RemoveConstraint(
            model_name="confighaie",
            name="project_url_id_required_if_demarche_number",
        ),
        migrations.AddConstraint(
            model_name="confighaie",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_activated", False),
                    ("demarche_numerique_number__isnull", False),
                    _connector="OR",
                ),
                name="demarche_numerique_number_required_if_activated",
            ),
        ),
        migrations.AddConstraint(
            model_name="confighaie",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("demarche_numerique_number__isnull", True),
                    ("demarche_numerique_display_fields__project_url__isnull", False),
                    _connector="OR",
                ),
                name="project_url_id_required_if_demarche_number",
            ),
        ),
        migrations.AlterField(
            model_name="confighaie",
            name="demarche_numerique_number",
            field=models.IntegerField(
                blank=True,
                help_text='Vous trouverez ce numéro en haut à droite de la carte de votre démarche dans la liste suivante : <a href="https://demarche.numerique.gouv.fr/admin/procedures" target="_blank" rel="noopener">https://demarche.numerique.gouv.fr/admin/procedures</a>',
                null=True,
                verbose_name="Numéro de la « Démarche numérique »",
            ),
        ),
        migrations.AlterField(
            model_name="confighaie",
            name="demarche_numerique_pre_fill_config",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="Configuration pré-remplissage sur « Démarche numérique »",
            ),
        ),
    ]
