# Generated by Django 4.2.28 on 2026-04-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "moulinette",
            "0114_remove_confighaie_project_url_id_required_if_demarche_number_and_more",
        ),
        ("moulinette", "0116_merge_20260420_1647"),
    ]

    operations = []
