# Generated by Django 4.2.28 on 2026-04-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0117_merge_20260423_1537"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterion",
            name="is_staff_only",
            field=models.BooleanField(
                default=False,
                help_text="Ne s'affiche et ne s'applique que pour les utilisateurs staff",
                verbose_name="Is staff only",
            ),
        ),
    ]
