# Generated by Django 4.2.28 on 2026-05-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0116_merge_20260504"),
        ("moulinette", "0117_alter_moulinettetemplate_key"),
    ]

    operations = []
