# Generated by Django 4.2.28 on 2026-04-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0113_merge_20260427_1504"),
        ("moulinette", "0117_merge_20260423_1537"),
    ]

    operations = []
