# Generated by Django 4.2.28 on 2026-04-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moulinette', '0114_criterion_is_staff_only_alter_moulinettetemplate_key'),
        ('moulinette', '0118_merge_20260427_1544'),
    ]

    operations = [
    ]
