# Generated by Django 4.2.28 on 2026-04-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0115_merge_20260428_1037"),
        ("moulinette", "0119_merge_20260427_1700"),
    ]

    operations = []
