# Generated by Django 4.2.28 on 2026-05-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0116_merge_20260429_1200"),
        ("moulinette", "0120_merge_20260429_1509"),
    ]

    operations = []
