# Generated by Django 4.2.28 on 2026-05-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0116_merge_20260504"),
        ("moulinette", "0121_merge_20260504_0859"),
    ]

    operations = []
