# Generated by Django 4.2.28 on 2026-05-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0121_create_icpe_instructor_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontotake",
            name="slug",
            field=models.CharField(
                choices=[
                    ("mention_arrete_lse", "Mention arrêté LSE"),
                    ("depot_pac_lse", "Dépôt PAC LSE"),
                    ("depot_dossier_lse", "Dépôt dossier LSE"),
                    ("etude_zh", "Étude ZH"),
                    ("etude_zi_lse", "Étude ZI LSE"),
                    ("etude_2150", "Étude 2150"),
                    ("depot_etude_impact", "Dépôt étude impact"),
                    ("depot_cas_par_cas", "Dépôt cas par cas"),
                    ("depot_ein", "Dépôt EIN"),
                    ("etude_zi_n2000", "Étude ZI Natura\xa02000"),
                    ("interdit_sage", "Interdit SAGE"),
                    ("pc_cas_par_cas", "PC cas par cas"),
                    ("pc_ein", "PC EIN"),
                    ("pc_etude_impact", "PC étude impact"),
                    ("pc_icpe_d", "PC ICPE déclaration"),
                    ("pc_icpe_e", "PC ICPE enregistrement"),
                    ("pc_icpe_inconnu", "PC ICPE régime inconnu"),
                    ("mention_arrete_icpe_e", "Mention arrêté ICPE E"),
                    ("suspension_delai_icpe", "Suspension délai ICPE"),
                    ("depot_dossier_icpe", "Dépôt dossier ICPE"),
                    ("depot_pac_icpe", "Dépôt PAC ICPE"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Référence de l'action",
            ),
        ),
    ]
