# Generated by Django 4.2.28 on 2026-05-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0118_merge_20260508_0936"),
        ("moulinette", "0122_merge_0116_merge_20260504_0121_merge_20260504_0859"),
    ]

    operations = []
