# Generated by Django 4.2.28 on 2026-05-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0121_create_icpe_instructor_actions"),
        ("moulinette", "0123_merge_20260508_0957"),
    ]

    operations = []
