# Generated by Django 4.2.28 on 2026-05-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0123_create_depot_pac_icpe"),
        ("moulinette", "0124_merge_20260513_1547"),
    ]

    operations = []
