# Generated by Django 4.2.28 on 2026-05-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0125_merge_20260518_1554"),
        ("moulinette", "0125_update_icpe_actions_data"),
    ]

    operations = []
