# Generated by Django 4.2.28 on 2026-05-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0126_merge_20260521_1458"),
        ("moulinette", "0128_alter_moulinettetemplate_key"),
    ]

    operations = []
