# Generated by Django 4.2.28 on 2026-06-22 08:06
from datetime import date

from django.db import migrations
import logging

from psycopg.types.range import DateRange

logger = logging.getLogger(__name__)

def classpath(klass):
    return "{}.{}".format(klass.__module__, klass.__name__)

SWITCHES = [
    (
        "envergo.moulinette.regulations.urbanisme_haie.UrbanismeHaie",
        "envergo.moulinette.regulations.urbanisme_haie.UrbanismeHaieHru",
        "envergo.moulinette.regulations.urbanisme_haie.UrbanismeHaieRu",
        "envergo.moulinette.regulations.urbanisme_haie.UrbanismeHaieL3503",
    ),
    (
        "envergo.moulinette.regulations.protection_captages.ProtectionCaptagesHaie",
        "envergo.moulinette.regulations.protection_captages.ProtectionCaptagesHaieHru",
        "envergo.moulinette.regulations.protection_captages.ProtectionCaptagesHaieRu",
        "envergo.moulinette.regulations.protection_captages.ProtectionCaptagesHaieL3503",
    ),
    (
        "envergo.moulinette.regulations.alignementarbres.AlignementsArbres",
        "envergo.moulinette.regulations.alignementarbres.AlignementsArbresCalvadosBeforeRu",
        None,
        "envergo.moulinette.regulations.alignementarbres.AlignementsArbresL3503",
    ),
    (
        "envergo.moulinette.regulations.regime_unique_haie.RegimeUniqueHaie",
        None,
        "envergo.moulinette.regulations.regime_unique_haie.RegimeUniqueHaieRu",
        None,
    ),
    (
        "envergo.moulinette.regulations.conditionnalitepac.Bcae8",
        "envergo.moulinette.regulations.conditionnalitepac.Bcae8Hru",
        "envergo.moulinette.regulations.conditionnalitepac.Bcae8Ru",
        None,
    ),
]


def switch_to_categorized_evaluator(apps, schema_editor):
    Criterion = apps.get_model("moulinette", "Criterion")

    for old, hru, ru, l350_3 in SWITCHES:
        existing_criteria = Criterion.objects.filter(evaluator=old)

        logger.info("Migrating criterion %s: %s found", old, existing_criteria.count())
        for criterion in existing_criteria:
            backend_title = criterion.backend_title
            if hru:
                criterion.backend_title = f"{backend_title} - Hors régime unique"
                criterion.evaluator = hru
                if "AlignementsArbresCalvadosBeforeRu" in hru:
                    criterion.backend_title = f"{backend_title} - Calvados avant régime unique"
                    criterion.validity_range = DateRange(None, date(2026, 9, 1))
            elif ru:
                criterion.backend_title = f"{backend_title} - Régime unique"
                criterion.evaluator = ru
            else:
                raise NotImplementedError()

            logger.info("Update: %s => %s", backend_title, criterion.backend_title)
            criterion.save()

            if ru and hru:
                # if there is no HRU, RU will have replaced the existing one.
                criterion.pk = None
                criterion.validity_range = None
                criterion.evaluator = ru
                criterion.backend_title = f"{backend_title} - Régime unique"
                logger.info("Create: %s from %s", criterion.backend_title, backend_title)
                criterion.save()

            if l350_3:
                criterion.pk = None
                criterion.validity_range = None
                criterion.evaluator = l350_3
                criterion.backend_title = f"{backend_title} - L350-3"
                logger.info("Create: %s from %s", criterion.backend_title, backend_title)
                criterion.save()


def reverse(apps, schema_editor):
    Criterion = apps.get_model("moulinette", "Criterion")

    for old, hru, ru, l350_3 in SWITCHES:
        existing_criteria = Criterion.objects.filter(evaluator__in=[x for x in [hru, ru, l350_3] if x is not None])
        logger.info("Reverse migration for criteria %s: %s found", [hru, ru, l350_3], existing_criteria.count())
        for criterion in existing_criteria:
            if classpath(criterion.evaluator) == hru and hru is not None:
                criterion.evaluator = old
                backend_title = criterion.backend_title
                criterion.validity_range = None
                criterion.backend_title =  criterion.backend_title.rsplit(" - ", 1)[0]
                logger.info("Update: %s => %s", backend_title, criterion.backend_title)
                criterion.save()
            elif classpath(criterion.evaluator) == ru and hru is None:
                criterion.evaluator = old
                backend_title = criterion.backend_title
                criterion.validity_range = None
                criterion.backend_title =  criterion.backend_title.rsplit(" - ", 1)[0]
                logger.info("Update: %s => %s", backend_title, criterion.backend_title)
                criterion.save()
            else:
                logger.info("Remove: %s", criterion.backend_title)
                criterion.delete()

class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0128_alter_moulinettetemplate_key"),
    ]

    operations = [
        migrations.RunPython(switch_to_categorized_evaluator, reverse),
    ]

