# Generated by Django 4.2.28 on 2026-06-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0129_merge_20260527_2107"),
        ("moulinette", "0129_multi_categories_criteria"),
    ]

    operations = []
