# Generated by Django 4.2.28 on 2026-07-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0130_merge_20260623_1202"),
        (
            "moulinette",
            "0130_rename_demarches_simplifiees_fields_to_demarche_numerique_and_more",
        ),
    ]

    operations = []
