# Generated by Django 4.2.28 on 2026-07-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0130_alter_configamenagement_regulations_available_and_more"),
        (
            "moulinette",
            "0130_rename_demarches_simplifiees_fields_to_demarche_numerique_and_more",
        ),
    ]

    operations = []
