# Generated by Django 4.2.28 on 2026-07-24 06:05

from django.db import migrations, models


def _convert_zone_forward(zone):
    """Split the two non_arboree coefficients into buissonnante + arbustive."""
    if not isinstance(zone, dict) or "R1_non_arboree_HD" not in zone:
        return None

    non_arboree_hd = zone["R1_non_arboree_HD"]
    non_arboree_ld = zone["R2_non_arboree_LD"]
    converted = {
        "X_densite": zone.get("X_densite", 60),
        "R1_buissonnante_HD": non_arboree_hd,
        "R2_buissonnante_LD": non_arboree_ld,
        "R3_arbustive_HD": non_arboree_hd,
        "R4_arbustive_LD": non_arboree_ld,
        "R5_arboree_HD": zone["R3_arboree_HD"],
        "R6_arboree_LD": zone["R4_arboree_LD"],
    }
    # Preserve any extra keys we don't know about.
    for key, value in zone.items():
        converted.setdefault(key, value)
    for old_key in (
        "R1_non_arboree_HD",
        "R2_non_arboree_LD",
        "R3_arboree_HD",
        "R4_arboree_LD",
    ):
        converted.pop(old_key, None)
    return converted


def _convert_zone_backward(zone):
    """Collapse buissonnante + arbustive back into a single non_arboree value.

    The old format had no buissonnante/arbustive distinction; we keep the
    buissonnante value as the representative non_arboree coefficient.
    """
    if not isinstance(zone, dict) or "R1_buissonnante_HD" not in zone:
        return None

    converted = {
        "X_densite": zone.get("X_densite", 60),
        "R1_non_arboree_HD": zone["R1_buissonnante_HD"],
        "R2_non_arboree_LD": zone["R2_buissonnante_LD"],
        "R3_arboree_HD": zone["R5_arboree_HD"],
        "R4_arboree_LD": zone["R6_arboree_LD"],
    }
    for key, value in zone.items():
        converted.setdefault(key, value)
    for new_key in (
        "R1_buissonnante_HD",
        "R2_buissonnante_LD",
        "R3_arbustive_HD",
        "R4_arbustive_LD",
        "R5_arboree_HD",
        "R6_arboree_LD",
    ):
        converted.pop(new_key, None)
    return converted


def _migrate(apps, convert):
    ConfigHaie = apps.get_model("moulinette", "ConfigHaie")
    for config in ConfigHaie.objects.filter(single_procedure=True):
        settings = config.single_procedure_settings or {}
        coeff = settings.get("coeff_compensation")
        if not isinstance(coeff, dict):
            continue

        changed = False
        for zone_id, zone in coeff.items():
            converted = convert(zone)
            if converted is not None:
                coeff[zone_id] = converted
                changed = True

        if changed:
            config.single_procedure_settings = settings
            config.save(update_fields=["single_procedure_settings"])


def migrate_forward(apps, schema_editor):
    _migrate(apps, _convert_zone_forward)


def migrate_backward(apps, schema_editor):
    _migrate(apps, _convert_zone_backward)


class Migration(migrations.Migration):

    dependencies = [
        (
            "moulinette",
            "0130_rename_demarches_simplifiees_fields_to_demarche_numerique_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="confighaie",
            name="single_procedure_requires_coeff_compensation",
        ),
        migrations.RunPython(migrate_forward, migrate_backward),
        migrations.AddConstraint(
            model_name="confighaie",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("single_procedure", False),
                    models.Q(
                        ("has_ru_zonage", True),
                        ("single_procedure_settings__has_key", "coeff_compensation"),
                    ),
                    models.Q(
                        ("has_ru_zonage", False),
                        ("single_procedure_settings__has_key", "coeff_compensation"),
                        (
                            "single_procedure_settings__coeff_compensation__has_key",
                            "default",
                        ),
                        (
                            "single_procedure_settings__coeff_compensation__default__has_key",
                            "X_densite",
                        ),
                        (
                            "single_procedure_settings__coeff_compensation__default__has_key",
                            "R1_buissonnante_HD",
                        ),
                        (
                            "single_procedure_settings__coeff_compensation__default__has_key",
                            "R2_buissonnante_LD",
                        ),
                        (
                            "single_procedure_settings__coeff_compensation__default__has_key",
                            "R3_arbustive_HD",
                        ),
                        (
                            "single_procedure_settings__coeff_compensation__default__has_key",
                            "R4_arbustive_LD",
                        ),
                        (
                            "single_procedure_settings__coeff_compensation__default__has_key",
                            "R5_arboree_HD",
                        ),
                        (
                            "single_procedure_settings__coeff_compensation__default__has_key",
                            "R6_arboree_LD",
                        ),
                    ),
                    _connector="OR",
                ),
                name="single_procedure_requires_coeff_compensation",
                violation_error_message="Les paramètres de régime unique doivent comporter une clé 'coeff_compensation'. Sans zonage, une entrée 'default' avec X_densite, R1_buissonnante_HD, R2_buissonnante_LD, R3_arbustive_HD, R4_arbustive_LD, R5_arboree_HD, R6_arboree_LD est requise.",
            ),
        ),
    ]
