# Generated by Django 4.2.28 on 2026-07-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0131_merge_20260710_0750"),
        ("moulinette", "0131_migrate_coeff_compensation_hedge_types"),
    ]

    operations = []
