# Generated by Django 4.2.28 on 2026-07-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0132_merge_20260724_1105"),
        ("moulinette", "0132_merge_20260729_1142"),
    ]

    operations = []
