# Generated by Django 4.2.28 on 2026-09-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0133_alter_moulinettetemplate_key"),
        ("moulinette", "0133_merge_20260729_1147"),
    ]

    operations = []
