# Generated by Django 4.2.28 on 2026-09-07 14:34

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0133_alter_moulinettetemplate_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="confighaie",
            name="guh_address",
            field=models.TextField(blank=True, verbose_name="Adresse GUH"),
        ),
        migrations.AddField(
            model_name="confighaie",
            name="guh_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email GUH"
            ),
        ),
        migrations.AddField(
            model_name="confighaie",
            name="guh_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="Téléphone GUH"
            ),
        ),
        migrations.AddField(
            model_name="confighaie",
            name="guh_service_name",
            field=models.CharField(blank=True, verbose_name="Nom du service GUH"),
        ),
        migrations.AddField(
            model_name="confighaie",
            name="guh_structure",
            field=models.CharField(
                default="Direction Départementale des Territoires (DDT)",
                verbose_name="Structure GUH (DDT ou DDTM)",
            ),
        ),
    ]
