# Generated by Django 4.2.28 on 2026-09-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0134_bcae8_regime_unique_criteria"),
        ("moulinette", "0134_merge_20260910_1511"),
    ]

    operations = []
