# Generated by Django 4.2.28 on 2026-09-07 14:37

from django.db import migrations
import re

catch_service_name = re.compile(r"<strong>((?:Services?|Pole) [^<]+)<\/strong>")
catch_email = re.compile(r"mailto:([^\"]+)\"")
catch_phone = re.compile(r"(0\d(?:\.| )\d\d(?:\.| )\d\d(?:\.| )\d\d(?:\.| )\d\d)")
catch_structure = re.compile(r"au sein de la (\w+)")

def extract_structured_data_from_contact_info(contact_info: str) -> dict:
    service_name = ""
    email = ""
    phone = ""
    structure = "Direction Départementale des Territoires (DDT)"

    service_name_match = catch_service_name.search(contact_info)
    if service_name_match is not None:
        service_name = service_name_match[1]

    email_match = catch_email.search(contact_info)
    if email_match is not None:
        email = email_match[1]

    phone_match = catch_phone.search(contact_info)
    if phone_match is not None:
        phone = phone_match[1].replace(".", " ")

    structure_match = catch_structure.search(contact_info)
    if structure_match is not None:
        structure = structure_match[1]

    result = {
        "guh_service_name": service_name,
        "guh_email": email,
        "guh_phone": phone,
        "guh_structure": structure,
    }

    return result

def create_contact_info_from_structured_data(config_haie) -> str:
    if not config_haie.guh_email and not config_haie.guh_phone:
        return f"<address>Nous ne disposons pas d’information sur le point de contact privilégié au sein de la {config_haie.guh_structure}</address>"

    address_rows = ["<strong>Guichet unique de la haie</strong>"]
    if config_haie.guh_service_name:
        address_rows.append(f"<strong>{config_haie.guh_service_name}</strong>")
    if config_haie.guh_email:
        address_rows.append(f'Email : <a href="mailto:{config_haie.guh_email}">{config_haie.guh_email}</a>')
    if config_haie.guh_phone:
        address_rows.append(f'Téléphone : <a href="tel:{config_haie.guh_phone}">{config_haie.guh_phone.as_national}</a>')

    return f"<address>{'<br>'.join(address_rows)}</address>"

def migrate_forward(apps, schema_editor):
    ConfigHaie = apps.get_model("moulinette", "ConfigHaie")
    for config_haie in ConfigHaie.objects.all():
        structured_data = extract_structured_data_from_contact_info(config_haie.contacts_info)
        for key, value in structured_data.items():
            config_haie.__setattr__(key, value)
        config_haie.save()

def migrate_backward(apps, schema_editor):
    ConfigHaie = apps.get_model("moulinette", "ConfigHaie")
    for config_haie in ConfigHaie.objects.all():
        config_haie.contacts_info = create_contact_info_from_structured_data(config_haie)
        config_haie.save()

class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0134_confighaie_guh_address_confighaie_guh_email_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
    ]
