# Generated by Django 4.2.28 on 2026-09-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0135_migrate_contact_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="confighaie",
            name="contacts_info",
        ),
    ]
