# Generated by Django 4.2.28 on 2026-09-14 08:19

from django.db import migrations


def migrate_forward(apps, schema_editor):
    ConfigHaie = apps.get_model("moulinette", "ConfigHaie")
    maritime_departments = "06,11,13,14,17,22,27,29,30,33,34,35,40,44,50,56,59,62,64,66,76,80,83,85"

    ConfigHaie.objects.filter(department__department__in=maritime_departments.split(",")).update(
        guh_structure="Direction Départementale des Territoires et de la Mer (DDTM)")


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0136_remove_confighaie_contacts_info"),
    ]

    operations = [
        migrations.RunPython(migrate_forward, migrations.RunPython.noop),
    ]
