# Generated by Django 4.2.28 on 2026-09-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0135_merge_20260911_0941"),
        ("moulinette", "0136_remove_confighaie_contacts_info"),
    ]

    operations = []
