# Generated by Django 4.2.28 on 2026-09-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0134_code_rural_multi_category_criteria"),
        ("moulinette", "0137_merge_20260911_1007"),
    ]

    operations = []
