# Generated by Django 4.2.28 on 2026-09-15 14:53

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0137_change_guh_structure_for_maritime_departments"),
    ]

    operations = [
        migrations.AddField(
            model_name="confighaie",
            name="prohibition_range",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                blank=True,
                null=True,
                verbose_name="Période d’interdiction de destruction de haies",
            ),
        ),
        migrations.AddConstraint(
            model_name="confighaie",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            ("prohibition_range__startswith__isnull", False),
                            ("prohibition_range__endswith__isnull", False),
                        ),
                        models.Q(
                            ("prohibition_range__startswith__isnull", True),
                            ("prohibition_range__endswith__isnull", True),
                        ),
                        _connector="OR",
                    )
                ),
                name="confighaie_prohibition_range_both_or_no_value",
                violation_error_message="Période d’interdiction : précisez à la fois une date de début et une date de fin, ou aucune date.",
            ),
        ),
    ]
