# Generated by Django 4.2.28 on 2026-09-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0134_bcae8_regime_unique_criteria"),
        ("moulinette", "0137_change_guh_structure_for_maritime_departments"),
    ]

    operations = []
