# Generated by Django 4.2.28 on 2026-09-17 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0134_bcae8_regime_unique_criteria"),
        ("moulinette", "0138_reserves_naturelles_multi_category_criteria"),
    ]

    operations = []
