# Generated by Django 4.2.28 on 2026-09-23 09:16

import django.core.validators
from django.db import migrations, models


def migrate_forward(apps, schema_editor):
    """Calvados historically used a 2.0 replantation coefficient.

    Every other department keeps the new field's default of 1.
    """
    ConfigHaie = apps.get_model("moulinette", "ConfigHaie")
    ConfigHaie.objects.filter(department__department="14").update(
        aa_l3503_authorization_coefficient=2.0
    )


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0138_alignement_arbres_multi_category_criteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="confighaie",
            name="aa_l3503_authorization_coefficient",
            field=models.FloatField(
                default=1,
                help_text="Coefficient multiplicateur appliqué au linéaire à planter lorsque le résultat est « soumis à autorisation » (L350-3).",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Coefficient de replantation - autorisation L350-3",
            ),
        ),
        migrations.AddConstraint(
            model_name="confighaie",
            constraint=models.CheckConstraint(
                check=models.Q(("aa_l3503_authorization_coefficient__gte", 1)),
                name="aa_l3503_authorization_coefficient_gte_1",
                violation_error_message="Le coefficient d'autorisation L350-3 doit être supérieur ou égal à 1.",
            ),
        ),
        migrations.RunPython(migrate_forward, migrations.RunPython.noop),
    ]
