# Generated by Django 4.2.28 on 2026-09-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0134_code_rural_multi_category_criteria"),
        ("moulinette", "0138_merge_20260922_0824"),
    ]

    operations = []
