# Generated by Django 4.2.28 on 2026-09-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0137_change_guh_structure_for_maritime_departments"),
        ("moulinette", "0138_merge_20260911_1202"),
    ]

    operations = []
