# Generated by Django 4.2.28 on 2026-09-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0138_confighaie_prohibition_range_and_more"),
        ("moulinette", "0139_merge_20260922_1018"),
    ]

    operations = []
