# Generated by Django 4.2.28 on 2026-09-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0139_confighaie_l350_3_authorization_coefficient_and_more"),
        ("moulinette", "0140_merge_20260922_1445"),
    ]

    operations = []
