# Generated by Django 4.2.28 on 2026-09-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0138_sites_proteges_multi_category_criteria"),
        ("moulinette", "0140_merge_20260922_1445"),
    ]

    operations = []
