# Generated by Django 4.2.28 on 2026-09-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0139_merge_20260917_0647"),
        ("moulinette", "0140_merge_20260922_1445"),
    ]

    operations = []
