# Generated by Django 4.2.28 on 2026-09-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0138_regime_unique_haie_multi_category_criteria"),
        ("moulinette", "0138_sites_classes_multi_category_criteria"),
        ("moulinette", "0138_sites_inscrits_multi_category_criteria"),
        ("moulinette", "0138_sites_proteges_multi_category_criteria"),
        ("moulinette", "0141_merge_20260917_1101"),
    ]

    operations = []
