# Generated by Django 4.2.28 on 2026-09-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0141_merge_20260923_0908"),
        ("moulinette", "0141_merge_20260925_1056"),
    ]

    operations = []
