# Generated by Django 4.2.28 on 2026-09-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0138_natura2000_haie_multi_category_criteria"),
        ("moulinette", "0141_merge_20260923_0908"),
    ]

    operations = []
