# Generated by Django 4.2.28 on 2026-09-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0138_regime_unique_haie_multi_category_criteria"),
        ("moulinette", "0138_sites_classes_multi_category_criteria"),
        ("moulinette", "0138_sites_inscrits_multi_category_criteria"),
        ("moulinette", "0142_ep_regime_unique_multi_category_criteria"),
        ("moulinette", "0142_merge_20260928_1359"),
        ("moulinette", "0142_merge_20260928_1751"),
    ]

    operations = []
