# Generated by Django 4.2.28 on 2026-09-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0138_merge_20260922_0824"),
        ("moulinette", "0142_merge_20260921_1200"),
    ]

    operations = []
