# Generated by Django 4.2.28 on 2026-09-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0141_merge_20260923_0908"),
        ("moulinette", "0143_merge_20260922_0920"),
    ]

    operations = []
