# Generated by Django 4.2.28 on 2026-09-29 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0144_alter_moulinettetemplate_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemarcheNumerique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "demarche_numerique_number",
                    models.IntegerField(
                        help_text='Vous trouverez ce numéro en haut à droite de la carte de votre démarche dans la liste suivante : <a href="https://demarche.numerique.gouv.fr/admin/procedures" target="_blank" rel="noopener">https://demarche.numerique.gouv.fr/admin/procedures</a>',
                        unique=True,
                        verbose_name="Numéro de la «\xa0Démarche numérique\xa0»",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Pour affichage dans l’administration Django uniquement",
                        null=True,
                        verbose_name="Nom de la démarche",
                    ),
                ),
                (
                    "pre_fill_config",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Configuration pré-remplissage sur «\xa0Démarche numérique\xa0»",
                    ),
                ),
                ("display_fields", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Démarche Numérique",
                "verbose_name_plural": "Démarches Numériques",
            },
        ),
        migrations.RemoveConstraint(
            model_name="confighaie",
            name="project_url_id_required_if_demarche_number",
        ),
        migrations.RemoveConstraint(
            model_name="confighaie",
            name="demarche_numerique_number_required_if_activated",
        ),
        migrations.AddConstraint(
            model_name="demarchenumerique",
            constraint=models.CheckConstraint(
                check=models.Q(("display_fields__project_url__isnull", False)),
                name="project_url_id_required",
            ),
        ),
        migrations.AddField(
            model_name="confighaie",
            name="demarche_numerique",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="moulinette.demarchenumerique",
                verbose_name="Démarche numérique",
            ),
        ),
    ]
