# Generated by Django 4.2.28 on 2026-09-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("demarchenumerique", "0001_initial"),
        ("moulinette", "0144_alter_moulinettetemplate_key"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="confighaie",
            name="demarche_numerique_number_required_if_activated",
        ),
        migrations.RemoveConstraint(
            model_name="confighaie",
            name="project_url_id_required_if_demarche_number",
        ),
        migrations.AddField(
            model_name="confighaie",
            name="demarche_numerique_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="demarchenumerique.demarcheconfig",
                verbose_name="Démarche numérique",
            ),
        ),
    ]
