# Generated by Django 4.2.28 on 2026-09-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0139_confighaie_l350_3_authorization_coefficient_and_more"),
        ("moulinette", "0144_merge_20260923_0940"),
    ]

    operations = []
