# Generated by Django 4.2.28 on 2026-09-25 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0142_ep_regime_unique_multi_category_criteria"),
        ("moulinette", "0145_merge_20260923_1127"),
    ]

    operations = []
