# Generated by Django 4.2.28 on 2026-09-29 07:14

from django.db import migrations


def forwards_create_demarchenumerique_from_confighaie(apps, schema_editor):
    DemarcheNumerique = apps.get_model("moulinette", "DemarcheNumerique")
    ConfigHaie = apps.get_model("moulinette", "ConfigHaie")

    for config_haie in (
        ConfigHaie.objects.filter(demarche_numerique_number__isnull=False)
        .select_related("department")
        .defer("department__geometry")
        .all()
    ):
        dn, _ = DemarcheNumerique.objects.get_or_create(
            demarche_numerique_number=config_haie.demarche_numerique_number,
            defaults={
                "pre_fill_config": config_haie.demarche_numerique_pre_fill_config,
                "display_fields": config_haie.demarche_numerique_display_fields,
                "display_name": f"Démarche Numérique importée du département {config_haie.department.department}",
            },
        )
        config_haie.demarche_numerique = dn
        config_haie.save()


def backwards_fill_confighaie_from_demarchenumerique(apps, schema_editor):
    ConfigHaie = apps.get_model("moulinette", "ConfigHaie")

    for config_haie in (
        ConfigHaie.objects.filter(demarche_numerique__isnull=False)
        .select_related("demarche_numerique")
        .all()
    ):
        config_haie.demarche_numerique_number = (
            config_haie.demarche_numerique.demarche_numerique_number
        )
        config_haie.demarche_numerique_pre_fill_config = (
            config_haie.demarche_numerique.pre_fill_config
        )
        config_haie.demarche_numerique_display_fields = (
            config_haie.demarche_numerique.display_fields
        )

        config_haie.save()


class Migration(migrations.Migration):
    dependencies = [
        ("moulinette", "0145_demarchenumerique_and_more"),
    ]

    operations = [
        migrations.RunPython(
            forwards_create_demarchenumerique_from_confighaie,
            backwards_fill_confighaie_from_demarchenumerique,
        ),
    ]
