# Generated by Django 4.2.28 on 2026-09-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moulinette", "0146_fill_demarchenumerique_from_confighaie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="confighaie",
            name="demarche_numerique_display_fields",
        ),
        migrations.RemoveField(
            model_name="confighaie",
            name="demarche_numerique_number",
        ),
        migrations.RemoveField(
            model_name="confighaie",
            name="demarche_numerique_pre_fill_config",
        ),
        migrations.AddConstraint(
            model_name="confighaie",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_activated", False),
                    ("demarche_numerique__isnull", False),
                    _connector="OR",
                ),
                name="demarche_numerique_required_if_activated",
            ),
        ),
    ]
