# Generated by Django 4.2.28 on 2026-09-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemarcheConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "demarche_numerique_number",
                    models.IntegerField(
                        help_text='Vous trouverez ce numéro en haut à droite de la carte de votre démarche dans la liste suivante : <a href="https://demarche.numerique.gouv.fr/admin/procedures" target="_blank" rel="noopener">https://demarche.numerique.gouv.fr/admin/procedures</a>',
                        unique=True,
                        verbose_name="Numéro de la «\xa0Démarche numérique\xa0»",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Pour affichage dans l’administration Django uniquement",
                        null=True,
                        verbose_name="Nom de la démarche",
                    ),
                ),
                (
                    "pre_fill_config",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Configuration pré-remplissage sur «\xa0Démarche numérique\xa0»",
                    ),
                ),
                ("display_fields", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Démarche",
                "verbose_name_plural": "Démarches",
            },
        ),
        migrations.AddConstraint(
            model_name="demarcheconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(("display_fields__project_url__isnull", False)),
                name="project_url_id_required",
            ),
        ),
    ]
