# Generated by Django 4.2.28 on 2026-09-30 12:12


from django.db import migrations


def forwards_create_demarcheconfig_from_confighaie(apps, schema_editor):
    DemarcheConfig = apps.get_model("demarchenumerique", "DemarcheConfig")
    ConfigHaie = apps.get_model("moulinette", "ConfigHaie")

    for config_haie in (
        ConfigHaie.objects.filter(demarche_numerique_number__isnull=False)
        .select_related("department")
        .defer("department__geometry")
        .all()
    ):
        dn_config, _ = DemarcheConfig.objects.get_or_create(
            demarche_numerique_number=config_haie.demarche_numerique_number,
            defaults={
                "pre_fill_config": config_haie.demarche_numerique_pre_fill_config,
                "display_fields": config_haie.demarche_numerique_display_fields,
                "display_name": f"Démarche Numérique importée du département {config_haie.department.department}",
            },
        )
        config_haie.demarche_numerique_config = dn_config
        config_haie.save()


def backwards_fill_confighaie_from_demarchenumerique(apps, schema_editor):
    ConfigHaie = apps.get_model("moulinette", "ConfigHaie")

    for config_haie in (
        ConfigHaie.objects.filter(demarche_numerique_config__isnull=False)
        .select_related("demarche_numerique_config")
        .all()
    ):
        config_haie.demarche_numerique_number = (
            config_haie.demarche_numerique_config.demarche_numerique_number
        )
        config_haie.demarche_numerique_pre_fill_config = (
            config_haie.demarche_numerique_config.pre_fill_config
        )
        config_haie.demarche_numerique_display_fields = (
            config_haie.demarche_numerique_config.display_fields
        )

        config_haie.save()


class Migration(migrations.Migration):
    dependencies = [
        ("demarchenumerique", "0001_initial"),
        (
            "moulinette",
            "0145_remove_confighaie_demarche_numerique_number_required_if_activated_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            forwards_create_demarcheconfig_from_confighaie,
            backwards_fill_confighaie_from_demarchenumerique,
        )
    ]
