# Generated by Django 4.2.13 on 2024-07-26 07:59

from django.db import migrations, models
import envergo.urlmappings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UrlMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default=envergo.urlmappings.models.generate_key,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
    ]
