# Generated by Django 4.2.13 on 2024-07-29 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("urlmappings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlmapping",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date created"
            ),
        ),
    ]
