# Generated by Django 4.2.13 on 2024-10-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urlmappings", "0002_urlmapping_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urlmapping",
            name="url",
            field=models.URLField(max_length=2048),
        ),
    ]
