# Generated by Django 4.2.28 on 2026-03-31 11:51
from urllib.parse import parse_qs, urlencode, urlsplit, urlunsplit

from django.db import migrations

def add_contexte_non(apps, schema_editor):
    UrlMapping = apps.get_model("urlmappings", "UrlMapping")

    def add_param(url):
        if not url:
            return url
        bits = urlsplit(url)
        query = parse_qs(bits.query)
        if "contexte" not in query or query["contexte"] == ["inconnu"]:
            query["contexte"] = ["non"]
            new_bits = bits._replace(query=urlencode(query, doseq=True))
            return urlunsplit(new_bits)
        return url

    mappings_to_update = []
    for mapping in UrlMapping.objects.filter(url__contains="://haie.").filter(url__contains="element=").all():
        new_url = add_param(mapping.url)
        if new_url != mapping.url:
            mapping.url = new_url
            mappings_to_update.append(mapping)
    UrlMapping.objects.bulk_update(mappings_to_update, ["url"])

class Migration(migrations.Migration):

    dependencies = [
        ('urlmappings', '0003_alter_urlmapping_url'),
    ]

    operations = [
        migrations.RunPython(add_contexte_non, migrations.RunPython.noop),
    ]
