# Generated by Django 4.2.28 on 2026-09-03 06:46
from urllib.parse import urlsplit, parse_qs, urlencode, urlunsplit

from django.db import migrations
from django.db.models import Subquery, OuterRef

def update_qs(url, params):
    """Update an url query string with new parameters."""

    bits = urlsplit(url)
    query = parse_qs(bits.query)
    query.update(params)
    new_query = urlencode(query, doseq=True)
    new_bits = bits._replace(query=new_query)
    return urlunsplit(new_bits)

def alternative_to_project_reference(apps, schema_editor):
    UrlMapping = apps.get_model("urlmappings", "UrlMapping")
    Simulation = apps.get_model("petitions", "Simulation")

    qs = UrlMapping.objects.filter(url__contains='alternative').annotate(
        project_reference=Subquery(
            Simulation.objects.select_related("project").filter(
                moulinette_url=OuterRef("url")
            ).values("project__reference")[:1]
        )
    ).filter(
        project_reference__isnull=False
    )
    to_update=[]
    for mapping in qs:
        mapping.url = update_qs(mapping.url, {"project_reference": mapping.project_reference})
        to_update.append(mapping)

    UrlMapping.objects.bulk_update(to_update, ["url"])



class Migration(migrations.Migration):

    dependencies = [
        ("urlmappings", "0005_delete_external_url_mappings"),
    ]

    operations = [
        migrations.RunPython(alternative_to_project_reference, migrations.RunPython.noop),
    ]
