import os
from argparse import ArgumentTypeError
from pathlib import Path

from django.contrib.gis.gdal import GDALRaster
from django.core.management.base import BaseCommand

from envergo.geodata.models import CatchmentAreaTile


def dir_path(path):
    if os.path.isdir(path):
        return Path(path)
    else:
        raise ArgumentTypeError(f"{path} is not a valid path.")


class Command(BaseCommand):
    """Imports catchment area data from tif files.

    This script is made to import to db raster files that were generated by the
    `mass_carto_creation.py` script then processed and converted to tif files,
    as described in the README file of the `bassins_versants` directory.
    """

    help = "Importe les rasters des zones de captage."

    def add_arguments(self, parser):
        parser.add_argument("dir_path", type=dir_path)

    def handle(self, *args, **options):
        dir = options["dir_path"]
        tif_files = list(dir.glob("*.tif"))
        for tif_file in tif_files:
            self.stdout.write(f"Importing {tif_file}")
            self.import_file(tif_file)

    def import_file(self, file):
        raster = GDALRaster(file, write=True)
        tile = CatchmentAreaTile(filename=file.name, rast=raster)
        tile.save()
