# Generated by Django 4.2 on 2024-01-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "setting",
                    models.CharField(
                        choices=[
                            (
                                "evalreq_confirmation_email_delay_mention",
                                "E-mail de confirmation de demande d'éval., mention de la délai de réponse",
                            )
                        ],
                        max_length=256,
                        unique=True,
                        verbose_name="Setting",
                    ),
                ),
                ("value", models.TextField(max_length=256, verbose_name="Value")),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
            },
        ),
    ]
