# Generated by Django 4.2.13 on 2024-08-22 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_add_haie"),
        ("confs", "0003_topbar_site_alter_setting_setting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topbar",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
        ),
    ]
