# Generated by Django 4.2.13 on 2024-10-07 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("confs", "0004_alter_topbar_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="setting",
            field=models.CharField(
                choices=[
                    (
                        "evalreq_confirmation_email_delay_mention",
                        "Accusé de réception demande d’AR, mention délai réponse",
                    )
                ],
                max_length=256,
                unique=True,
                verbose_name="Setting",
            ),
        ),
        migrations.CreateModel(
            name="HostedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="hosted_files/", verbose_name="File"),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date created"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hosted file",
                "verbose_name_plural": "Hosted files",
            },
        ),
    ]
