# Generated by Django 4.2.13 on 2024-10-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("confs", "0004_alter_topbar_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="setting",
            field=models.CharField(
                choices=[
                    (
                        "evalreq_confirmation_email_delay_mention",
                        "Accusé de réception demande d’AR, mention délai réponse",
                    )
                ],
                max_length=256,
                unique=True,
                verbose_name="Setting",
            ),
        ),
    ]
