# Generated by Django 4.2.13 on 2024-10-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("confs", "0005_alter_setting_setting"),
        ("confs", "0005_alter_setting_setting_hostedfile"),
    ]

    operations = []
