# Generated by Django 4.2.19 on 2025-04-07 09:46

from django.db import migrations, models
import envergo.confs.models


class Migration(migrations.Migration):

    dependencies = [
        ("confs", "0006_merge_20241008_1517"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostedfile",
            name="file",
            field=models.FileField(
                upload_to="f",
                validators=[envergo.confs.models.max_file_size],
                verbose_name="File",
            ),
        ),
    ]
