# Generated by Django 4.2.28 on 2026-08-20 09:58

from django.db import migrations, models
import envergo.confs.models
import envergo.utils.storages


class Migration(migrations.Migration):

    dependencies = [
        ("confs", "0007_alter_hostedfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostedfile",
            name="file",
            field=models.FileField(
                storage=envergo.utils.storages.get_public_storage,
                upload_to="documents",
                validators=[envergo.confs.models.max_file_size],
                verbose_name="File",
            ),
        ),
    ]
