# Generated by Django 4.2.13 on 2024-12-16 10:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "common_name",
                    models.CharField(max_length=255, verbose_name="Nom commun"),
                ),
                (
                    "scientific_name",
                    models.CharField(max_length=255, verbose_name="Nom scientifique"),
                ),
                (
                    "hedge_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("degradee", "Haie dégradée ou résiduelle basse"),
                                ("buissonnante", "Haie buissonnante basse"),
                                ("arbustive", "Haie arbustive"),
                                ("alignement", "Alignement d'arbres"),
                                ("mixte", "Haie mixte"),
                            ],
                            max_length=32,
                        ),
                        size=None,
                        verbose_name="Types de haies considérés",
                    ),
                ),
                (
                    "proximite_mare",
                    models.BooleanField(verbose_name="Mare à moins de 200\xa0m"),
                ),
                (
                    "proximite_point_eau",
                    models.BooleanField(
                        verbose_name="Mare ou ruisseau à moins de 10\xa0m"
                    ),
                ),
                (
                    "connexion_boisement",
                    models.BooleanField(
                        verbose_name="Connectée à un boisement ou à une autre haie"
                    ),
                ),
                (
                    "vieil_arbre",
                    models.BooleanField(
                        verbose_name="Contient un ou plusieurs vieux arbres, fissurés ou avec cavités"
                    ),
                ),
            ],
            options={
                "verbose_name": "Espèce",
                "verbose_name_plural": "Espèces",
            },
        ),
    ]
