# Generated by Django 4.2.13 on 2024-12-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0002_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="group",
            field=models.CharField(
                choices=[
                    ("amphibiens", "Amphibiens"),
                    ("chauves-souris", "Chauves-souris"),
                    ("flore", "Flore"),
                    ("insectes", "Insectes"),
                    ("mammifères-terrestres", "Mammifères terrestres"),
                    ("oiseaux", "Oiseaux"),
                    ("reptile", "Reptile"),
                ],
                default="flore",
                max_length=64,
                verbose_name="Groupe",
            ),
            preserve_default=False,
        ),
    ]
