# Generated by Django 4.2.13 on 2025-01-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0003_species_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="highly_sentitive",
            field=models.BooleanField(
                default=False, verbose_name="Particulièrement sensible"
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="level_of_concern",
            field=models.CharField(
                choices=[
                    ("faible", "Faible"),
                    ("moyen", "Moyen"),
                    ("fort", "Fort"),
                    ("tres_fort", "Très fort"),
                    ("majeur", "Majeur"),
                ],
                default="moyen",
                max_length=16,
                verbose_name="Niveau d'enjeu",
            ),
            preserve_default=False,
        ),
    ]
