# Generated by Django 4.2.13 on 2025-01-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0004_species_highly_sentitive_species_level_of_concern"),
    ]

    operations = [
        migrations.RenameField(
            model_name="species",
            old_name="highly_sentitive",
            new_name="highly_sensitive",
        ),
    ]
