# Generated by Django 4.2.13 on 2025-01-13 13:31
import csv

from django.db import migrations
from django.template.defaultfilters import slugify

HEDGE_TYPES = dict(
    (
        ("degradee", "Haie dégradée ou résiduelle basse"),
        ("buissonnante", "Haie buissonnante basse"),
        ("arbustive", "Haie arbustive"),
        ("alignement", "Alignement d'arbres"),
        ("mixte", "Haie mixte"),
    )
).keys()


def import_aisne_species(apps, schema_editor):
    Species = apps.get_model("hedges", "Species")
    with open("envergo/hedges/migrations/ep_aisne.csv") as f:
        reader = csv.DictReader(f)
        for row in reader:
            hedges = []
            for key in HEDGE_TYPES:
                if row[key] == "True":
                    hedges.append(key)
            Species.objects.create(
                group=slugify(row["group"]),
                common_name=row["common_name"],
                scientific_name=row["scientific_name"],
                level_of_concern=row["level_of_concern"],
                highly_sensitive=row["highly_sensitive"] == "True",
                proximite_mare=row["proximite_mare"] == "True",
                proximite_point_eau=row["proximite_point_eau"] == "True",
                connexion_boisement=row["connexion_boisement"] == "True",
                vieil_arbre=row["vieil_arbre"] == "True",
                hedge_types=hedges,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0005_rename_highly_sentitive_species_highly_sensitive"),
    ]

    operations = [
        migrations.RunPython(
            import_aisne_species, reverse_code=migrations.RunPython.noop
        )
    ]
