# Generated by Django 4.2.13 on 2025-01-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0006_import_aisne_species"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="group",
            field=models.CharField(
                choices=[
                    ("amphibiens", "Amphibiens"),
                    ("chauves-souris", "Chauves-souris"),
                    ("flore", "Flore"),
                    ("insectes", "Insectes"),
                    ("mammiferes-terrestres", "Mammifères terrestres"),
                    ("oiseaux", "Oiseaux"),
                    ("reptile", "Reptile"),
                ],
                max_length=64,
                verbose_name="Groupe",
            ),
        ),
    ]
