# Generated by Django 4.2.13 on 2025-01-22 08:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0007_alter_species_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="taxref_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                null=True,
                size=None,
                verbose_name="Ids TaxRef (cd_nom)",
            ),
        ),
    ]
