# Generated by Django 4.2.17 on 2025-01-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0008_species_taxref_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="scientific_name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Nom scientifique"
            ),
        ),
    ]
