# Generated by Django 4.2.17 on 2025-01-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0009_alter_species_scientific_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="kingdom",
            field=models.CharField(
                blank=True,
                choices=[
                    ("animalia", "Animalia"),
                    ("archaea", "Archaea"),
                    ("bacteria", "Bacteria"),
                    ("chromista", "Chromista"),
                    ("fungi", "Fungi"),
                    ("plantae", "Plantae"),
                    ("protozoa", "Protozoa"),
                ],
                max_length=32,
                verbose_name="Règne",
            ),
        ),
    ]
