# Generated by Django 4.2.19 on 2025-02-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0010_species_kingdom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="group",
            field=models.CharField(
                choices=[
                    ("amphibiens", "Amphibiens"),
                    ("chauves-souris", "Chauves-souris"),
                    ("flore", "Flore"),
                    ("insectes", "Insectes"),
                    ("mammiferes-terrestres", "Mammifères terrestres"),
                    ("oiseaux", "Oiseaux"),
                    ("reptiles", "Reptiles"),
                ],
                max_length=64,
                verbose_name="Groupe",
            ),
        ),
    ]
