# Generated by Django 4.2.19 on 2025-02-18 10:49

from django.db import migrations


def update_reptiles(apps, schema_editor):
    Species = apps.get_model("hedges", "Species")
    Species.objects.filter(group="reptile").update(group="reptiles")


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0011_alter_species_group"),
    ]

    operations = [
        migrations.RunPython(update_reptiles, reverse_code=migrations.RunPython.noop)
    ]
