# Generated by Django 4.2.19 on 2025-04-14 09:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0018_alter_map_map_type"),
        ("hedges", "0012_update_reptiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeciesMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hedge_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("degradee", "Haie dégradée ou résiduelle basse"),
                                ("buissonnante", "Haie buissonnante basse"),
                                ("arbustive", "Haie arbustive"),
                                ("alignement", "Alignement d'arbres"),
                                ("mixte", "Haie mixte"),
                            ],
                            max_length=32,
                        ),
                        size=None,
                        verbose_name="Types de haies considérés",
                    ),
                ),
                (
                    "proximite_mare",
                    models.BooleanField(verbose_name="Mare à moins de 200\xa0m"),
                ),
                (
                    "proximite_point_eau",
                    models.BooleanField(
                        verbose_name="Mare ou ruisseau à moins de 10\xa0m"
                    ),
                ),
                (
                    "connexion_boisement",
                    models.BooleanField(
                        verbose_name="Connectée à un boisement ou à une autre haie"
                    ),
                ),
                (
                    "vieil_arbre",
                    models.BooleanField(
                        verbose_name="Contient un ou plusieurs vieux arbres, fissurés ou avec cavités"
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_maps",
                        to="geodata.map",
                        verbose_name="Carte",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_maps",
                        to="hedges.species",
                        verbose_name="Espèce",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carte d'espèce",
                "verbose_name_plural": "Cartes d'espèces",
            },
        ),
    ]
