# Generated by Django 4.2.19 on 2025-05-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0013_hedges_data_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="hedgedata",
            name="density",
            field=models.JSONField(
                default=dict,
                verbose_name="Densité de haies existantes autour des haies à détruire",
            ),
        ),
    ]
