# Generated by Django 4.2.19 on 2025-04-17 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0018_alter_map_map_type"),
        ("hedges", "0013_speciesmap"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeciesMapFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="species_maps/", verbose_name="Fichier"),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="geodata.map",
                        verbose_name="Carte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fichier de carte d'espèces",
                "verbose_name_plural": "Fichiers de carte d'espèces",
            },
        ),
    ]
