# Generated by Django 4.2.19 on 2025-04-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0014_speciesmapfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciesmapfile",
            name="name",
            field=models.CharField(
                default="",
                help_text="Nom pense-bête",
                max_length=255,
                verbose_name="Nom",
            ),
            preserve_default=False,
        ),
    ]
