# Generated by Django 4.2.19 on 2025-04-17 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0015_speciesmapfile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciesmap",
            name="species_map_file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="species_maps",
                to="hedges.speciesmapfile",
                verbose_name="Importé par",
            ),
        ),
        migrations.AddField(
            model_name="speciesmapfile",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Créé le"
            ),
        ),
        migrations.AddField(
            model_name="speciesmapfile",
            name="import_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date du dernier import"
            ),
        ),
        migrations.AddField(
            model_name="speciesmapfile",
            name="import_error_msg",
            field=models.TextField(blank=True, verbose_name="Message d'erreur import"),
        ),
        migrations.AddField(
            model_name="speciesmapfile",
            name="import_status",
            field=models.CharField(
                choices=[
                    ("success", "Succès"),
                    ("partial_success", "Succès partiel"),
                    ("failure", "Échec"),
                ],
                max_length=32,
                null=True,
                verbose_name="Statut d'import",
            ),
        ),
        migrations.AddField(
            model_name="speciesmapfile",
            name="task_id",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Celery task id"
            ),
        ),
    ]
