# Generated by Django 4.2.19 on 2025-04-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0018_alter_map_map_type"),
        ("hedges", "0016_speciesmap_species_map_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speciesmapfile",
            name="import_error_msg",
        ),
        migrations.AddField(
            model_name="speciesmapfile",
            name="import_log",
            field=models.TextField(blank=True, verbose_name="Log d'import"),
        ),
        migrations.AlterUniqueTogether(
            name="speciesmap",
            unique_together={("species", "map")},
        ),
    ]
