# Generated by Django 4.2.19 on 2025-05-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0013_hedges_data_schema"),
        ("hedges", "0017_remove_speciesmapfile_import_error_msg_and_more"),
    ]

    operations = []
