# Generated by Django 4.2.19 on 2025-05-05 08:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0018_merge_20250502_1216"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="species",
            name="connexion_boisement",
        ),
        migrations.RemoveField(
            model_name="species",
            name="hedge_types",
        ),
        migrations.RemoveField(
            model_name="species",
            name="proximite_mare",
        ),
        migrations.RemoveField(
            model_name="species",
            name="proximite_point_eau",
        ),
        migrations.RemoveField(
            model_name="species",
            name="vieil_arbre",
        ),
        migrations.RemoveField(
            model_name="speciesmap",
            name="connexion_boisement",
        ),
        migrations.RemoveField(
            model_name="speciesmap",
            name="proximite_mare",
        ),
        migrations.RemoveField(
            model_name="speciesmap",
            name="proximite_point_eau",
        ),
        migrations.RemoveField(
            model_name="speciesmap",
            name="vieil_arbre",
        ),
        migrations.AddField(
            model_name="speciesmap",
            name="hedge_properties",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("proximite_mare", "Mare à moins de 200\xa0m"),
                        ("proximite_point_eau", "Mare ou ruisseau à moins de 10\xa0m"),
                        (
                            "connexion_boisement",
                            "Connectée à un boisement ou à une autre haie",
                        ),
                        (
                            "vieil_arbre",
                            "Contient un ou plusieurs vieux arbres, fissurés ou avec cavités",
                        ),
                    ],
                    max_length=32,
                ),
                default=list,
                help_text="Propriétés requises par l'espèce",
                size=None,
                verbose_name="Propriétés de la haie",
            ),
            preserve_default=False,
        ),
    ]
