# Generated by Django 4.2.19 on 2025-05-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0019_remove_species_connexion_boisement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hedgedata",
            name="_density",
            field=models.JSONField(default=None, null=True),
        ),
    ]
