# Generated by Django 4.2.19 on 2025-05-26 15:15

from django.db import migrations
from tqdm import tqdm

def update_hedges_data_json_schema(apps, schema_editor):
    HedgeData = apps.get_model("hedges", "HedgeData")
    qs = HedgeData.objects.filter(data__isnull=False)
    total = qs.count()
    batch_size = 1000
    i = 0
    with tqdm(total=total) as pbar:
        while i < total:
            models = qs[i: i + batch_size].iterator()  # noqa
            to_update = []
            for model in models:
                if not model.data:
                    continue

                for hedge in model.data:
                    data = hedge.get("additionalData", {})
                    position = data.pop("position", None)

                    if position == "interchamp":
                        data["interchamp"] = True
                    else:
                        data["interchamp"] = False

                    if position == "bord_route":
                        data["bord_voie"] = True
                    else:
                        data["bord_voie"] = False

                    hedge["additionalData"] = data
                to_update.append(model)

            HedgeData.objects.bulk_update(to_update, ["data"])
            i += batch_size
            pbar.update(batch_size)


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0019_remove_species_connexion_boisement_and_more"),
    ]

    operations = [
        migrations.RunPython(update_hedges_data_json_schema, migrations.RunPython.noop),
    ]
