# Generated by Django 4.2.19 on 2025-05-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0018_merge_20250417_1514"),
        ("hedges", "0019_remove_species_connexion_boisement_and_more"),
    ]

    operations = []
