# Generated by Django 4.2.19 on 2025-05-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0020_hedgedata_density"),
        ("hedges", "0020_merge_20250505_1508"),
    ]

    operations = []
