# Generated by Django 4.2.19 on 2025-06-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0020_hedgedata_density"),
        ("hedges", "0020_hedges_data_schema"),
    ]

    operations = []
