# Generated by Django 4.2.23 on 2025-08-07 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0021_merge_0020_hedgedata_density_0020_hedges_data_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pacage",
            fields=[
                (
                    "pacage",
                    models.CharField(
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.RegexValidator("[0-9]{9}")],
                        verbose_name="Numéro de PACAGE",
                    ),
                ),
                (
                    "exploitation_density",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Densité de l'exploitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Infos Pacage",
                "verbose_name_plural": "Infos Pacage",
            },
        ),
    ]
