# Generated by Django 4.2.19 on 2025-06-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0021_merge_0020_hedgedata_density_0020_hedges_data_schema"),
        ("hedges", "0021_merge_0020_hedgedata_density_0020_merge_20250505_1508"),
    ]

    operations = []
