# Generated by Django 4.2.23 on 2025-08-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0022_pacage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pacage",
            old_name="pacage",
            new_name="pacage_num",
        ),
    ]
