# Generated by Django 4.2.28 on 2026-02-12 16:50
from django.contrib.gis.geos import MultiLineString
from django.db import migrations


def update_hedges_density_with_density_inside_buffer(apps, schema_editor):
    HedgeData = apps.get_model("hedges", "HedgeData")
    hedges = HedgeData.objects.filter(_density__isnull=False)

    to_update = []
    for hedge in hedges:
        if not hedge._density:
            continue
        if "density_around_centroid" not in hedge._density:
            hedge._density.update(
                {
                    "density_around_centroid": {
                        "length_200": hedge._density.pop("length_200"),
                        "length_5000": hedge._density.pop("length_5000"),
                        "area_200_ha": hedge._density.pop("area_200_ha"),
                        "area_5000_ha": hedge._density.pop("area_5000_ha"),
                        "density_200": hedge._density.pop("density_200"),
                        "density_5000": hedge._density.pop("density_5000"),
                    }
                }
            )

        to_update.append(hedge)

    HedgeData.objects.bulk_update(to_update, ["_density"])


def reverse_hedges_density(apps, schema_editor):
    HedgeData = apps.get_model("hedges", "HedgeData")
    hedges = HedgeData.objects.filter(_density__isnull=False)

    to_update = []
    for hedge in hedges:
        if not hedge._density:
            continue
        if "density_around_centroid" in hedge._density:
            hedge._density.update(
                {
                    "length_200": hedge._density["density_around_centroid"].pop(
                        "length_200"
                    ),
                    "length_5000": hedge._density["density_around_centroid"].pop(
                        "length_5000"
                    ),
                    "area_200_ha": hedge._density["density_around_centroid"].pop(
                        "area_200_ha"
                    ),
                    "area_5000_ha": hedge._density["density_around_centroid"].pop(
                        "area_5000_ha"
                    ),
                    "density_200": hedge._density["density_around_centroid"].pop(
                        "density_200"
                    ),
                    "density_5000": hedge._density["density_around_centroid"].pop(
                        "density_5000"
                    ),
                }
            )
            del hedge._density["density_around_centroid"]
        if "density_inside_buffer" in hedge._density:
            del hedge._density["density_inside_buffer"]

        to_update.append(hedge)

    HedgeData.objects.bulk_update(to_update, ["_density"])


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0023_rename_pacage_pacage_pacage_num"),
    ]

    operations = [
        migrations.RunPython(
            update_hedges_density_with_density_inside_buffer, reverse_hedges_density
        ),
    ]
