# Generated by Django 4.2.28 on 2026-02-12 16:50
from django.contrib.gis.geos import MultiLineString
from django.db import migrations
from tqdm import tqdm

from envergo.geodata.utils import EPSG_WGS84, compute_hedge_density_around_lines
from envergo.hedges.models import HedgeList, Hedge


def update_hedges_density_inside_buffer_to_inside_line(apps, schema_editor):
    HedgeData = apps.get_model("hedges", "HedgeData")
    qs = HedgeData.objects.filter(_density__isnull=False)

    total = qs.count()
    batch_size = 1000
    i = 0
    with tqdm(total=total) as pbar:
        while i < total:
            models = qs[i : i + batch_size].iterator()  # noqa
            to_update = []
            for model in models:
                if not model._density:
                    continue
                if "density_around_centroid" in model._density:
                    model._density.update(
                        {
                            "around_centroid": model._density.pop(
                                "density_around_centroid"
                            ),
                        }
                    )
                if "density_inside_buffer" in model._density:
                    model._density.update(
                        {
                            "around_lines": model._density.pop("density_inside_buffer"),
                        }
                    )

                to_update.append(model)

            HedgeData.objects.bulk_update(to_update, ["_density"])
            i += batch_size
            pbar.update(batch_size)


def reverse_hedges_density(apps, schema_editor):
    HedgeData = apps.get_model("hedges", "HedgeData")
    qs = HedgeData.objects.filter(_density__isnull=False)

    total = qs.count()
    batch_size = 1000
    i = 0
    with tqdm(total=total) as pbar:
        while i < total:
            models = qs[i : i + batch_size].iterator()  # noqa
            to_update = []
            for model in models:
                if not model._density:
                    continue
                if "around_centroid" in model._density:
                    model._density.update(
                        {
                            "density_around_centroid": model._density.pop(
                                "around_centroid"
                            ),
                        }
                    )
                if "around_lines" in model._density:
                    model._density.update(
                        {
                            "density_inside_buffer": model._density.pop("around_lines"),
                        }
                    )

                to_update.append(model)

            HedgeData.objects.bulk_update(to_update, ["_density"])
            i += batch_size
            pbar.update(batch_size)


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0023_rename_pacage_pacage_pacage_num"),
    ]

    operations = [
        migrations.RunPython(
            update_hedges_density_with_density_inside_buffer, reverse_hedges_density
        ),
    ]
