# Generated by Django 4.2.28 on 2026-02-12 16:50
from django.contrib.gis.geos import MultiLineString
from django.db import migrations


def update_hedges_density_inside_buffer_to_inside_line(apps, schema_editor):
    HedgeData = apps.get_model("hedges", "HedgeData")
    hedges = HedgeData.objects.filter(_density__isnull=False)

    to_update = []
    for hedge in hedges:
        if not hedge._density:
            continue
        if "density_around_centroid" in hedge._density:
            hedge._density.update(
                {
                    "around_centroid": hedge._density.pop("density_around_centroid"),
                }
            )
        if "density_inside_buffer" in hedge._density:
            hedge._density.update(
                {
                    "around_lines": hedge._density.pop("density_inside_buffer"),
                }
            )

        to_update.append(hedge)

    HedgeData.objects.bulk_update(to_update, ["_density"])


def reverse_hedges_density(apps, schema_editor):
    HedgeData = apps.get_model("hedges", "HedgeData")
    hedges = HedgeData.objects.filter(_density__isnull=False)

    to_update = []
    for hedge in hedges:
        if not hedge._density:
            continue
        if "around_centroid" in hedge._density:
            hedge._density.update(
                {
                    "density_around_centroid": hedge._density.pop("around_centroid"),
                }
            )
        if "around_lines" in hedge._density:
            hedge._density.update(
                {
                    "density_inside_buffer": hedge._density.pop("around_lines"),
                }
            )

        to_update.append(hedge)

    HedgeData.objects.bulk_update(to_update, ["_density"])


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0024_update_hedgedata_density"),
    ]

    operations = [
        migrations.RunPython(
            update_hedges_density_inside_buffer_to_inside_line, reverse_hedges_density
        ),
    ]
