# Generated by Django 4.2.28 on 2026-03-24 13:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0025_update_hedgedata_density_bis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciesmap",
            name="hedge_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("degradee", "Haie dégradée ou résiduelle basse"),
                        ("buissonnante", "Haie buissonnante basse"),
                        ("arbustive", "Haie arbustive"),
                        ("mixte", "Haie mixte"),
                        ("alignement", "Alignement d'arbres"),
                    ],
                    max_length=32,
                ),
                size=None,
                verbose_name="Types de haies considérés",
            ),
        ),
    ]
