# Generated by Django 4.2.28 on 2026-04-10 05:08

import django.contrib.postgres.fields
from django.db import migrations, models


def compute_hedge_length(latLngs, hedge_type, filter_type):
    from pyproj import Geod
    from shapely.geometry import LineString

    if hedge_type != filter_type:
        return 0.0

    coords = [(float(p["lng"]), float(p["lat"])) for p in latLngs]
    geod = Geod(ellps="WGS84")
    return geod.geometry_length(LineString(coords))


def populate_lengths(apps, schema_editor):
    HedgeData = apps.get_model("hedges", "HedgeData")

    for obj in HedgeData.objects.all():
        length_to_plant = 0.0
        length_to_remove = 0.0
        failed = False

        for hedge in obj.data:
            try:
                length_to_plant += compute_hedge_length(
                    hedge["latLngs"], hedge["type"], "TO_PLANT"
                )
                length_to_remove += compute_hedge_length(
                    hedge["latLngs"], hedge["type"], "TO_REMOVE"
                )
            except (ValueError, TypeError, KeyError):
                # Old data may have malformed coordinates (e.g. string lat/lng values)
                # Leave the fields as None for those rows
                failed = True
                break

        if not failed:
            obj._length_to_plant = length_to_plant
            obj._length_to_remove = length_to_remove
            obj.save(update_fields=["_length_to_plant", "_length_to_remove"])

class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0027_rename_proximite_point_eau_to_ripisylve"),
    ]

    operations = [
        migrations.AddField(
            model_name="hedgedata",
            name="_length_to_remove",
            field=models.FloatField(default=None, null=True, verbose_name="Longueur détruite"),
        ),
        migrations.AddField(
            model_name="hedgedata",
            name="_length_to_plant",
            field=models.FloatField(default=None, null=True, verbose_name="Longueur plantée"),
        ),
        migrations.RunPython(populate_lengths, migrations.RunPython.noop),

        migrations.AlterField(
            model_name="speciesmap",
            name="hedge_properties",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("proximite_mare", "Mare à moins de 200\xa0m"),
                        (
                            "ripisylve",
                            "En bordure de cours d'eau ou de plan d'eau (haie ripisylve)",
                        ),
                        (
                            "connexion_boisement",
                            "Connectée à un boisement ou à une autre haie",
                        ),
                        (
                            "vieil_arbre",
                            "Contient un ou plusieurs vieux arbres, fissurés ou avec cavités",
                        ),
                    ],
                    max_length=32,
                ),
                help_text="Propriétés requises par l'espèce",
                size=None,
                verbose_name="Propriétés de la haie",
            ),
        ),
    ]
