# Generated by Django 4.2.28

from django.db import migrations


def add_concerne_aa_default(apps, schema_editor):
    Criterion = apps.get_model("moulinette", "Criterion")

    qs = Criterion.objects.filter(
        evaluator="envergo.moulinette.regulations.natura2000_haie.Natura2000Haie",
    ).exclude(evaluator_settings__has_key="concerne_aa")

    to_update = []
    for criterion in qs:
        if not criterion.evaluator_settings:
            criterion.evaluator_settings = {}
        criterion.evaluator_settings["concerne_aa"] = "non"
        to_update.append(criterion)

    Criterion.objects.bulk_update(to_update, ["evaluator_settings"])


def remove_concerne_aa(apps, schema_editor):
    Criterion = apps.get_model("moulinette", "Criterion")

    qs = Criterion.objects.filter(
        evaluator="envergo.moulinette.regulations.natura2000_haie.Natura2000Haie",
        evaluator_settings__has_key="concerne_aa",
    )

    to_update = []
    for criterion in qs:
        del criterion.evaluator_settings["concerne_aa"]
        to_update.append(criterion)

    Criterion.objects.bulk_update(to_update, ["evaluator_settings"])


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0028_hedgedata_length_fields"),
        ("moulinette", "0111_confighaie_contacts_info"),
    ]

    operations = [
        migrations.RunPython(
            add_concerne_aa_default,
            remove_concerne_aa,
        ),
    ]
