# Generated by Django 4.2.28 on 2026-04-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0029_empty"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="cd_ref",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="CD_REF TaxRef"
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="taxref_group",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Groupe TaxRef"
            ),
        ),
        migrations.AddField(
            model_name="speciesmap",
            name="level_of_concern",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non_documente", "Non documenté"),
                    ("faible", "Faible"),
                    ("moyen", "Moyen"),
                    ("fort", "Fort"),
                    ("tres_fort", "Très fort"),
                    ("majeur", "Majeur"),
                ],
                help_text="Niveau d'enjeu spécifique à cette carte/département.",
                max_length=16,
                null=True,
                verbose_name="Niveau d'enjeu local",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("amphibiens", "Amphibiens"),
                    ("chauves-souris", "Chauves-souris"),
                    ("flore", "Flore"),
                    ("insectes", "Insectes"),
                    ("mammiferes-terrestres", "Mammifères terrestres"),
                    ("oiseaux", "Oiseaux"),
                    ("reptiles", "Reptiles"),
                ],
                help_text="Classification ad-hoc obsolète. Utiliser le groupe TaxRef.",
                max_length=64,
                verbose_name="Groupe (obsolète)",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="level_of_concern",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non_documente", "Non documenté"),
                    ("faible", "Faible"),
                    ("moyen", "Moyen"),
                    ("fort", "Fort"),
                    ("tres_fort", "Très fort"),
                    ("majeur", "Majeur"),
                ],
                max_length=16,
                verbose_name="Niveau d'enjeu",
            ),
        ),
    ]
