# Generated by Django 4.2.28 on 2026-04-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0031_rename_species_fields_and_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="adhoc_group",
            field=models.CharField(
                blank=True,
                help_text="Classification ad-hoc obsolète. Utiliser le groupe TaxRef.",
                max_length=64,
                verbose_name="Groupe (obsolète)",
            ),
        ),
    ]
