# Generated by Django 4.2.28 on 2026-04-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0032_alter_species_adhoc_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="common_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nom commun"
            ),
        ),
    ]
