# Generated by Django 4.2.28 on 2026-04-29 14:42

from django.db import migrations


def clear_stubs(apps, schema_editor):
    Species = apps.get_model("hedges", "Species")
    Species.objects.filter(common_name__startswith="CD_REF_").update(common_name="")


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0033_alter_species_common_name"),
    ]

    operations = [
        migrations.RunPython(clear_stubs, migrations.RunPython.noop),
    ]
