# Generated by Django 4.2.28 on 2026-04-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0034_clear_common_name_stubs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="common_name",
            field=models.CharField(
                blank=True,
                help_text="Importé depuis le référentiel TaxRef",
                max_length=255,
                verbose_name="Nom commun",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="highly_sensitive",
            field=models.BooleanField(
                default=False,
                help_text="Seulement pour l'Aisne.",
                verbose_name="Particulièrement sensible",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="level_of_concern",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non_documente", "Non documenté"),
                    ("faible", "Faible"),
                    ("moyen", "Moyen"),
                    ("fort", "Fort"),
                    ("tres_fort", "Très fort"),
                    ("majeur", "Majeur"),
                ],
                help_text="Seulement pour l'Aisne. Cette valeur est désormais spécifiée dans le modèle Habitat d'espèce.",
                max_length=16,
                verbose_name="Niveau d'enjeu",
            ),
        ),
    ]
