# Generated by Django 4.2.28 on 2026-05-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0036_backfill_adhoc_group_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="highly_sensitive",
            field=models.BooleanField(
                default=False,
                help_text="Seulement pour l’Aisne avant le régime unique.",
                verbose_name="Particulièrement sensible",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="level_of_concern",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non_documente", "Non documenté"),
                    ("faible", "Faible"),
                    ("moyen", "Moyen"),
                    ("fort", "Fort"),
                    ("tres_fort", "Très fort"),
                    ("majeur", "Majeur"),
                ],
                help_text="Seulement pour l'Aisne avant régime unique. Pour le régime unique, l’enjeu est désormais spécifié dans le modèle Habitat d'espèce.",
                max_length=16,
                verbose_name="Niveau d'enjeu",
            ),
        ),
    ]
