# Generated by Django 4.2.28 on 2026-05-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0037_alter_species_highly_sensitive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="adhoc_group",
            field=models.CharField(
                blank=True,
                help_text="Classification ad-hoc issue du producteur de données.",
                max_length=64,
                verbose_name="Groupe simplifié",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="group",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Groupe (taxref)"
            ),
        ),
    ]
