# Generated by Django 4.2.28 on 2026-09-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0039_drop_legacy_density_cache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="level_of_concern",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non_documente", "Non documenté"),
                    ("faible", "Faible"),
                    ("moyen", "Moyen"),
                    ("fort", "Fort"),
                    ("tres_fort", "Très fort"),
                    ("majeur", "Majeur"),
                ],
                help_text="\nSeulement pour l'Aisne avant régime unique.\nPour le régime unique, l’enjeu est désormais spécifié dans le modèle Habitat d'espèce.\n",
                max_length=16,
                verbose_name="Niveau d'enjeu",
            ),
        ),
    ]
