# Generated by Django 4.2.28 on 2026-09-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0040_alter_species_level_of_concern"),
        ("hedges", "0040_remove_hedgedata_density"),
    ]

    operations = []
