# Generated by Django 4.2.28 on 2026-09-23 09:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedges", "0041_merge_20260908_1518"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specieshabitat",
            name="hedge_properties",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("proximite_mare", "Mare ou pièce d’eau à moins de 500\xa0m"),
                        (
                            "ripisylve",
                            "En bordure de cours d'eau ou de plan d'eau (haie ripisylve)",
                        ),
                        (
                            "connexion_boisement",
                            "Connectée à un boisement ou à une autre haie",
                        ),
                        (
                            "vieil_arbre",
                            "Contient un ou plusieurs vieux arbres, fissurés ou avec cavités",
                        ),
                    ],
                    max_length=32,
                ),
                help_text="Propriétés requises par l'espèce",
                size=None,
                verbose_name="Propriétés de la haie",
            ),
        ),
    ]
