# Generated by Django 3.1.12 on 2021-07-08 13:24

from django.db import migrations, models
import envergo.evaluations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=15, verbose_name='Application number')),
                ('evaluation_file', models.FileField(upload_to=envergo.evaluations.models.evaluation_file_format, verbose_name='Evaluation file')),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
            },
        ),
    ]
