# Generated by Django 3.1.12 on 2021-07-08 13:49

import django.core.validators
from django.db import migrations, models
import envergo.evaluations.models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_file',
            field=models.FileField(upload_to=envergo.evaluations.models.evaluation_file_format, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Evaluation file'),
        ),
    ]
