# Generated by Django 4.2 on 2023-08-22 07:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0003_rename_rr_mention_evaluation_rr_mention_html_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="contact_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                default=list,
                size=None,
                verbose_name="Contact e-mails",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="rr_mention_md",
            field=models.TextField(
                blank=True,
                help_text="Will be included in the RR email. Only simple markdown (bold, italic, links, newlines).",
                verbose_name="Regulatory reminder mention",
            ),
        ),
    ]
