# Generated by Django 3.1.12 on 2021-07-08 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_evaluation_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='id',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
