# Generated by Django 3.1.12 on 2021-07-09 10:59

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_auto_20210708_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='application_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='The application number format is invalid.', regex='^(PC|PA)(?P<department>\\d{3})(?P<commune>\\d{3})(?P<year>\\d{2})(?P<file>[\\w\\d]{5})$')], verbose_name='Application number'),
        ),
    ]
