# Generated by Django 4.2 on 2023-08-22 07:40

from django.db import migrations


def set_contact_emails(apps, schema_editor):
    Request = apps.get_model("evaluations", "Request")
    for request in Request.objects.all():
        if request.contact_email:
            request.contact_emails = [request.contact_email]
            request.save()

    Evaluation = apps.get_model("evaluations", "Evaluation")
    for evaluation in Evaluation.objects.all():
        if evaluation.contact_email:
            evaluation.contact_emails = [evaluation.contact_email]
            evaluation.save()


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0005_evaluation_contact_emails"),
    ]

    operations = [migrations.RunPython(set_contact_emails)]
