# Generated by Django 3.1.12 on 2021-08-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_auto_20210709_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='commune',
            field=models.CharField(default='', help_text='The name and postcode of the project commune', max_length=256, verbose_name='Commune'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='created_surface',
            field=models.IntegerField(default=0, help_text='In square meters', verbose_name='Created surface'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='existing_surface',
            field=models.IntegerField(blank=True, help_text='In square meters', null=True, verbose_name='Existing surface'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='flood_zone_impact',
            field=models.TextField(default='', verbose_name='Flood zone impact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='flood_zone_probability',
            field=models.IntegerField(choices=[(1, 'Unlikely'), (2, 'Possible'), (3, 'Likely'), (4, 'Very likely')], default=2, verbose_name='Flood zone probability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='global_probability',
            field=models.IntegerField(choices=[(1, 'Unlikely'), (2, 'Possible'), (3, 'Likely'), (4, 'Very likely')], default=2, verbose_name='Probability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='rainwater_runoff_impact',
            field=models.TextField(default='', verbose_name='Rainwater runoff impact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='rainwater_runoff_probability',
            field=models.IntegerField(choices=[(1, 'Unlikely'), (2, 'Possible'), (3, 'Likely'), (4, 'Very likely')], default=2, verbose_name='Rainwater runoff probability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='wetland_impact',
            field=models.TextField(default='', verbose_name='Wetland impact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='wetland_probability',
            field=models.IntegerField(choices=[(1, 'Unlikely'), (2, 'Possible'), (3, 'Likely'), (4, 'Very likely')], default=2, verbose_name='Wetland probability'),
            preserve_default=False,
        ),
    ]
