# Generated by Django 3.2.6 on 2021-08-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0008_criterion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='criterion',
            unique_together={('evaluation', 'criterion')},
        ),
    ]
