# Generated by Django 4.2 on 2023-09-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0008_alter_evaluation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulatorynoticelog",
            name="html_body",
            field=models.TextField(verbose_name="Html body"),
        ),
        migrations.AlterField(
            model_name="regulatorynoticelog",
            name="txt_body",
            field=models.TextField(verbose_name="Text body"),
        ),
    ]
