# Generated by Django 4.2 on 2023-09-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0009_alter_regulatorynoticelog_html_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="regulatorynoticelog",
            name="message_id",
            field=models.CharField(
                blank=True, max_length=1024, verbose_name="Message id"
            ),
        ),
    ]
