# Generated by Django 4.2 on 2023-09-06 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0010_regulatorynoticelog_message_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=64, verbose_name="Event")),
                ("date", models.DateTimeField(verbose_name="Date")),
                (
                    "recipient",
                    models.EmailField(max_length=254, verbose_name="Recipient"),
                ),
                ("subject", models.CharField(max_length=1024, verbose_name="Subject")),
                (
                    "regulatory_notice_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.regulatorynoticelog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mail log",
                "verbose_name_plural": "Mail logs",
                "ordering": ("-date",),
            },
        ),
    ]
