# Generated by Django 3.2.6 on 2021-08-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0011_rename_legend_criterion_legend_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='legend_html',
            field=models.TextField(blank=True, verbose_name='Legend (html)'),
        ),
    ]
