# Generated by Django 4.2 on 2023-09-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0012_alter_maillog_regulatory_notice_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maillog",
            name="subject",
            field=models.CharField(blank=True, max_length=1024, verbose_name="Subject"),
        ),
    ]
