# Generated by Django 3.2.6 on 2021-08-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0012_criterion_legend_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='contact_html',
            field=models.TextField(blank=True, verbose_name='Contact (html)'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='contact_md',
            field=models.TextField(blank=True, verbose_name='Contact'),
        ),
    ]
