# Generated by Django 3.2.6 on 2021-08-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0013_auto_20210824_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='flood_zone_impact',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='flood_zone_probability',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='rainwater_runoff_impact',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='rainwater_runoff_probability',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='wetland_impact',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='wetland_probability',
        ),
    ]
