# Generated by Django 3.2.6 on 2021-08-25 14:11

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields
import re


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0014_auto_20210825_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Address')),
                ('application_number', models.CharField(db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='The application number format is invalid.', regex='^(PC|PA)(?P<department>\\d{3})(?P<commune>\\d{3})(?P<year>\\d{2})(?P<file>[\\w\\d]{5})$')], verbose_name='Application number')),
                ('created_surface', models.IntegerField(help_text='In square meters', verbose_name='Created surface')),
                ('existing_surface', models.IntegerField(blank=True, help_text='In square meters', null=True, verbose_name='Existing surface')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region=None, verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'Evaluation request',
                'verbose_name_plural': 'Evaluation requests',
            },
        ),
    ]
