# Generated by Django 4.2 on 2023-09-15 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0009_copy_data_from_request_to_eval"),
        ("evaluations", "0017_delete_maillog"),
    ]

    operations = []
