# Generated by Django 3.2.6 on 2021-09-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0019_alter_request_application_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='other_contacts',
            field=models.TextField(blank=True, verbose_name='Other contacts'),
        ),
    ]
