# Generated by Django 4.2 on 2023-11-29 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0020_alter_evaluation_notice_log_cascade"),
        ("evaluations", "0020_evaluation_is_icpe_alter_evaluation_details_md_and_more"),
    ]

    operations = []
