# Generated by Django 3.2.6 on 2021-09-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0015_alter_evaluation_evaluation_file'),
        ('evaluations', '0020_request_other_contacts'),
    ]

    operations = [
    ]
