# Generated by Django 4.2 on 2023-11-30 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0021_merge_20231129_0837"),
        (
            "evaluations",
            "0021_recipientstatus_on_error_alter_evaluation_details_md_and_more",
        ),
    ]

    operations = []
