# Generated by Django 3.2.6 on 2021-09-24 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0021_merge_20210914_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='reference',
            field=models.CharField(max_length=64, null=True, verbose_name='Reference'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations.request', verbose_name='Request'),
        ),
        migrations.AddField(
            model_name='request',
            name='reference',
            field=models.CharField(max_length=64, null=True, verbose_name='Reference'),
        ),
    ]
