# Generated by Django 4.2 on 2023-12-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "evaluations",
            "0023_alter_evaluation_details_md_alter_evaluation_request_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="recipientstatus",
            name="reject_reason",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Reject reason"
            ),
        ),
    ]
