# Generated by Django 3.2.6 on 2021-09-24 08:28

from django.db import migrations, models
import envergo.evaluations.models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0023_set_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='reference',
            field=models.CharField(db_index=True, default=envergo.evaluations.models.generate_reference, max_length=64, unique=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='request',
            name='reference',
            field=models.CharField(db_index=True, default=envergo.evaluations.models.generate_reference, max_length=64, null=True, unique=True, verbose_name='Reference'),
        ),
    ]
