# Generated by Django 3.2.6 on 2021-10-04 13:27

import django.contrib.postgres.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0027_copy_app_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='phone_number', new_name='project_sponsor_phone_number',
        ),
        migrations.AddField(
            model_name='request',
            name='project_sponsor_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None, verbose_name='Project sponsor email(s)'),
        ),
        migrations.AddField(
            model_name='request',
            name='send_eval_to_sponsor',
            field=models.BooleanField(default=True, verbose_name='Send evaluation to project sponsor'),
        ),
    ]
