# Generated by Django 3.2.6 on 2021-10-05 09:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0028_auto_20211004_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='project_description',
            field=models.TextField(blank=True, verbose_name='Project description, comments'),
        ),
        migrations.AlterField(
            model_name='request',
            name='project_sponsor_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region=None, verbose_name='Project sponsor phone number'),
        ),
    ]
