# Generated by Django 4.2 on 2024-04-30 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0029_alter_evaluation_project_owner_emails_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="parcels",
        ),
    ]
