# Generated by Django 3.2.6 on 2021-10-06 12:44

import django.core.validators
from django.db import migrations, models
import envergo.evaluations.models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0030_request_additional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='additional_data',
            field=models.FileField(blank=True, null=True, upload_to=envergo.evaluations.models.additional_data_file_format, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip'])], verbose_name='Additional data'),
        ),
    ]
