# Generated by Django 4.2 on 2024-05-18 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("evaluations", "0032_evaluationversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationversion",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evaluation_versions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
            preserve_default=False,
        ),
    ]
