# Generated by Django 3.2.6 on 2021-10-11 13:25

from django.db import migrations


def copy_contact_email(apps, schema_editor):
    Evaluation = apps.get_model("evaluations", "Evaluation")
    evals = Evaluation.objects.exclude(request__isnull=True).select_related("request")

    for eval in evals:
        eval.contact_email = eval.request.contact_email
        eval.save()


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0032_evaluation_contact_email"),
    ]

    operations = [
        migrations.RunPython(copy_contact_email, migrations.RunPython.noop),
    ]
