# Generated by Django 4.2 on 2024-05-27 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0031_evaluation_project_owner_company"),
        ("evaluations", "0033_evaluationversion_created_by"),
    ]

    operations = []
