# Generated by Django 4.2 on 2024-05-31 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0035_remove_evaluation_contact_html_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Criterion",
        ),
    ]
