# Generated by Django 4.2.13 on 2024-06-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0036_delete_criterion"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="submitted",
            field=models.BooleanField(default=True, verbose_name="Submitted"),
        ),
    ]
