# Generated by Django 4.2.13 on 2024-06-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0037_request_submitted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="submitted",
            field=models.BooleanField(default=False, verbose_name="Submitted"),
        ),
    ]
