# Generated by Django 3.2.6 on 2021-10-26 08:55

from django.db import migrations


def copy_address_field(apps, *args):
    Evaluation = apps.get_model("evaluations", "Evaluation")
    evals = Evaluation.objects.all()
    for eval in evals:
        try:
            eval.address = eval.request.address
        except:
            eval.address = eval.commune

        eval.save()


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0037_alter_evaluation_application_number"),
    ]

    operations = [
        migrations.RunPython(copy_address_field, migrations.RunPython.noop),
    ]
