# Generated by Django 4.2.13 on 2024-07-18 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "evaluations",
            "0039_rename_contact_emails_evaluation_urbanism_department_emails_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="requestfile",
            name="uploaded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
