# Generated by Django 3.2.6 on 2021-12-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0041_auto_20211108_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created_surface',
            field=models.IntegerField(blank=True, help_text='In square meters', null=True, verbose_name='Created surface'),
        ),
    ]
