# Generated by Django 4.2.13 on 2024-10-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0042_evaluationversion_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationversion",
            name="message",
            field=models.CharField(
                default="Version initiale", max_length=1024, verbose_name="Message"
            ),
            preserve_default=False,
        ),
    ]
