# Generated by Django 3.2.6 on 2021-12-02 09:33

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import envergo.evaluations.models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0042_alter_request_created_surface'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage, upload_to=envergo.evaluations.models.request_file_format, verbose_name='File')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='additional_files', to='evaluations.request')),
            ],
        ),
    ]
