# Generated by Django 3.2.6 on 2021-12-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0043_requestfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestfile',
            options={'verbose_name': 'Request file', 'verbose_name_plural': 'Request files'},
        ),
        migrations.AddField(
            model_name='requestfile',
            name='name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Name'),
        ),
    ]
