# Generated by Django 3.2.11 on 2022-01-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0043_auto_20220111_0907'),
        ('evaluations', '0044_auto_20211202_0939'),
    ]

    operations = [
    ]
