# Generated by Django 4.2.13 on 2024-10-17 08:44

from django.db import migrations
from django.db.models import F


def set_updated_at(apps, schema_editor):
    Evaluation = apps.get_model("evaluations", "Evaluation")
    Evaluation.objects.update(updated_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0044_evaluation_updated_at"),
    ]

    operations = [migrations.RunPython(set_updated_at, migrations.RunPython.noop)]
