# Generated by Django 3.2.11 on 2022-01-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0045_merge_0043_auto_20220111_0907_0044_auto_20211202_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='required_action',
            field=models.TextField(blank=True, choices=[('not_in_zh', 'ne se situe pas en zone humide'), ('surface_lt_1000', 'a une emprise au sol —\xa0y compris travaux et remblais\xa0— de moins de 1\xa0000 m²'), ('surface_lt_400', 'a une emprise au sol —\xa0y compris travaux et remblais\xa0— de moins de 400 m²'), ('runoff_lt_10000', "capte une surface de ruissellement d'eau de pluie inférieure à 10\xa0000 m²")], verbose_name='Required action'),
        ),
    ]
