# Generated by Django 4.2.19 on 2025-04-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0046_alter_evaluation_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluationversion",
            name="message",
            field=models.CharField(
                help_text="This message will be displayed to users.",
                max_length=1024,
                verbose_name="Message",
            ),
        ),
    ]
