# Generated by Django 4.2.21 on 2025-07-11 09:45

from django.db import migrations, models
from django.db.models import Count


def remove_duplicate(apps, schema_editor):
    RecipientStatus = apps.get_model("evaluations", "RecipientStatus")
    statuses = (
        RecipientStatus.objects.values("regulatory_notice_log", "recipient")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )

    for status in statuses:
        duplicated_statuses = RecipientStatus.objects.filter(
            regulatory_notice_log=status["regulatory_notice_log"],
            recipient=status["recipient"],
        ).order_by("id")
        for duplicate in duplicated_statuses[1:]:
            duplicate.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0047_alter_evaluationversion_message"),
    ]

    operations = [
        migrations.RunPython(remove_duplicate, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="recipientstatus",
            constraint=models.UniqueConstraint(
                fields=("regulatory_notice_log", "recipient"), name="unique_index"
            ),
        ),
    ]
