# Generated by Django 4.2.23 on 2025-10-30 09:01

import django.contrib.postgres.fields
from django.db import migrations, models

def seed_actions(apps, schema_editor):
    EvaluationAction = apps.get_model("evaluations", "EvaluationAction")
    actions = [
        ("mention_arrete_lse", "action", "instructor", 1, "Mentionner dans l’arrêté le différé de réalisation des travaux", "Le projet est susceptible d’être soumis à la Loi sur l’eau. L’arrêté municipal doit faire référence au fait que les travaux ne peuvent pas commencer avant l'accord préfectoral (conformément au <a href='https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006819991' target='_blank'>R*424-6 du code de l’urbanisme</a>).", []),
        ("depot_pac_lse", "action", "petitioner", 1, "Déposer un porter-à-connaissance auprès de la DDT(M)", "… si le projet existant a déjà fait l’objet d’un dossier Loi sur l’eau.\n\nSi au contraire le projet n'a jamais fait l'objet d'un dossier Loi sur l’eau, il doit être remis en conformité : un dossier Loi sur l’eau portant sur l’ensemble du projet doit être déposé.<br/><a title='Voir le détail de la réglementation « Loi sur l&#39;eau »' href='#regulation_loi_sur_leau' class='fr-link fr-text--sm'>En savoir plus</a>", []),
        ("depot_dossier_lse", "action", "petitioner", 1, "Déposer un dossier Loi sur l'eau", "<a title='Voir le détail de la réglementation « Loi sur l&#39;eau »' href='#regulation_loi_sur_leau' class='fr-link fr-text--sm'>En savoir plus</a>", []),
        ("etude_zh_lse", "action", "petitioner", 11, "Réaliser un inventaire zones humides", "Si le projet détruit ou affecte le fonctionnement de plus de 1 000 m² de zones humides, il est soumis à déclaration Loi sur l’eau.<br/><a title='Voir le détail de l&#39;impact sur une zone humide' href='#criterion-loi_sur_leau__zone_humide' class='fr-link fr-text--sm'>En savoir plus</a>", []),
        ("etude_zi_lse", "action", "petitioner", 12, "Réaliser une étude hydraulique", "Si le projet soustrait plus de 400 m² à la zone d'expansion des crues d'un cours d'eau, il est soumis à déclaration Loi sur l’eau.<br/><a title='Voir le détail de l&#39;impact sur une zone inondable' href='#criterion-loi_sur_leau__zone_inondable' class='fr-link fr-text--sm'>En savoir plus</a>", []),
        ("etude_2150", "action", "petitioner", 13, "Réaliser une étude de gestion des eaux pluviales", "Si le projet intercepte les eaux pluviales d'une surface de plus de 1 ha et les rejette dans le milieu naturel, il est soumis à déclaration Loi sur l’eau.<br/><a title='Voir le détail de l&#39;impact sur l&#39;écoulement des eaux pluviales' href='#{% if moulinette.loi_sur_leau.ecoulement_avec_bv %}criterion-loi_sur_leau__ecoulement_avec_bv{% else %}criterion-loi_sur_leau__ecoulement_sans_bv{% endif %}' class='fr-link fr-text--sm'>En savoir plus</a>", []),
        ("depot_etude_impact", "action", "petitioner", 2, "Déposer un dossier d'évaluation environnementale", "<a title='Voir le détail de la réglementation « Évaluation environnementale »' href='#regulation_eval_env' class='fr-link fr-text--sm'>En savoir plus</a>", []),
        ("depot_cas_par_cas", "action", "petitioner", 2, "Déposer une demande d’examen au cas par cas", "<a title='Voir le détail de la réglementation « Évaluation environnementale »' href='#regulation_eval_env' class='fr-link fr-text--sm'>En savoir plus</a>", []),
        ("depot_ein", "action", "petitioner", 3, "Réaliser une évaluation des incidences Natura 2000", "Cette évaluation des incidences (EIN) doit être jointe{% if moulinette.natura2000.autorisation_urba.result == 'soumis' %} à la demande de PA, PC ou de DP.{% elif moulinette.loi_sur_leau.result == 'soumis' %} au dossier Loi sur l'eau.{% elif moulinette.loi_sur_leau.result == 'soumis_ou_pac' %}, si un dossier Loi sur l'eau est réalisé, à celui-ci.{% else %} directement à la DDT(M).{% endif %}<br/><a title='Voir le détail de la réglementation « Natura 2000 »' href='#regulation_natura2000' class='fr-link fr-text--sm'>En savoir plus</a>", []),
        ("etude_zh_n2000", "action", "petitioner", 15, "Réaliser un inventaire zones humides", "", []),
        ("etude_zi_n2000", "action", "petitioner", 16, "Réaliser une étude hydraulique", "", []),
        ("pc_cas_par_cas", "pc", "instructor", 1, "L’arrêté préfectoral portant décision suite à l’examen au cas par cas", "", ["PC11", "PA14"]),
        ("pc_ein", "pc", "instructor", 2, "L’évaluation des incidences Natura 2000", "{% if moulinette.natura2000.ein_out_of_n2000_site %}Ceci s’applique parce que le projet est soumis à la Loi sur l'eau ou à examen au cas par cas, et qu'il est donc soumis à évaluation des incidences Natura 2000 (EIN) <em>bien qu'il se situe hors d’un site Natura 2000</em>. L'EIN est une pièce obligatoire de la demande d'autorisation d'urbanisme – voir <a href='https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000046885095/2023-11-30/' target='_blank'>art. R414-19 I-2° et II du code de l’environnement</a>{% endif %}", ["PC11-2", "PA15-1"]),
    ]
    for slug, type_, target, order, label, details, documents in actions:
        EvaluationAction.objects.create(
            slug=slug,
            type=type_,
            target=target,
            order=order,
            label=label,
            details=details,
            documents_to_attach=documents,
        )



class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0048_recipientstatus_unique_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            (
                                "mention_arrete_lse",
                                "Mentionner dans l’arrêté le différé de réalisation des travaux",
                            ),
                            (
                                "depot_pac_lse",
                                "Déposer un porter-à-connaissance auprès de la DDT(M)",
                            ),
                            ("depot_dossier_lse", "Déposer un dossier Loi sur l'eau"),
                            (
                                "etude_zh_lse",
                                "LSE > Réaliser un inventaire zones humides",
                            ),
                            ("etude_zi_lse", "LSE > Réaliser une étude hydraulique"),
                            (
                                "etude_2150",
                                "Réaliser une étude de gestion des eaux pluviales",
                            ),
                            (
                                "depot_etude_impact",
                                "Déposer un dossier d'évaluation environnementale",
                            ),
                            (
                                "depot_cas_par_cas",
                                "Déposer une demande d’examen au cas par cas",
                            ),
                            (
                                "depot_ein",
                                "Réaliser une évaluation des incidences Natura\xa02000",
                            ),
                            (
                                "etude_zh_n2000",
                                "Natura 2000 > Réaliser un inventaire zones humides",
                            ),
                            (
                                "etude_zi_n2000",
                                "Natura 2000 > Réaliser une étude hydraulique",
                            ),
                            (
                                "pc_cas_par_cas",
                                "L’arrêté préfectoral portant décision suite à l’examen au cas par cas",
                            ),
                            ("pc_ein", "L’évaluation des incidences Natura 2000"),
                        ],
                        max_length=50,
                        verbose_name="Référence de l'action",
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("action", "Action"), ("pc", "Pièce complémentaire")],
                        max_length=20,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("instructor", "Un service instruction urbanisme"),
                            ("petitioner", "Un porteur de projet ou maître d'œuvre"),
                        ],
                        max_length=20,
                        verbose_name="Cible",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Order")),
                ("label", models.TextField(help_text="Texte de niveau 1")),
                ("details", models.TextField(help_text="Texte de niveau 2")),
                (
                    "documents_to_attach",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Action à mener",
                "verbose_name_plural": "Actions à mener",
            },
        ),

        migrations.RunPython(seed_actions, migrations.RunPython.noop)
    ]
