# Generated by Django 3.2.11 on 2022-01-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0049_alter_criterion_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='probability',
            field=models.IntegerField(choices=[(1, 'Unlikely'), (2, 'Possible'), (3, 'Likely'), (4, 'Very likely')], default=2, verbose_name='Probability'),
            preserve_default=False,
        ),
    ]
