# Generated by Django 4.2.23 on 2025-11-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0050_evaluation_display_actions_to_take"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evaluationaction",
            options={
                "ordering": ["order"],
                "verbose_name": "Action à mener",
                "verbose_name_plural": "Actions à mener",
            },
        ),
    ]
