# Generated by Django 3.2.11 on 2022-01-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0051_remove_evaluation_global_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='probability',
            field=models.IntegerField(choices=[(1, 'Unlikely'), (2, 'Possible'), (3, 'Likely'), (4, 'Very likely')], null=True, verbose_name='Probability'),
        ),
    ]
