# Generated by Django 4.2.23 on 2025-11-10 10:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0051_alter_evaluationaction_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluationaction",
            name="details",
            field=models.TextField(
                help_text="Texte de niveau 2, contenu HTML évalué comme un template.",
                verbose_name="Détails",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationaction",
            name="documents_to_attach",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="Valeurs séparées par des virgules sans espace",
                size=None,
                verbose_name="référence des pièces complémentaires",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationaction",
            name="label",
            field=models.TextField(
                help_text="Texte de niveau 1", verbose_name="Titre affiché"
            ),
        ),
        migrations.AlterField(
            model_name="evaluationaction",
            name="order",
            field=models.PositiveIntegerField(default=1, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="evaluationaction",
            name="type",
            field=models.CharField(
                choices=[("action", "Action"), ("pc", "Pièce complémentaire")],
                max_length=20,
                verbose_name="Type d'action",
            ),
        ),
    ]
