# Generated by Django 4.2.23 on 2025-11-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0052_alter_evaluationaction_details_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="evaluationaction",
            table="evaluations_evaluationaction",
        ),
    ]
