# Generated by Django 4.2.23 on 2025-11-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0053_alter_evaluationaction_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EvaluationAction",
        ),
    ]

    # Override database operations to do nothing
    def apply(self, project_state, schema_editor=None, collect_sql=False):
        # only update state, skip database operations
        for op in self.operations:
            op.state_forwards(self.app_label, project_state)
        return project_state

    def unapply(self, project_state, schema_editor=None, collect_sql=False):
        # do nothing
        return project_state
