# Generated by Django 4.2.27 on 2026-02-04 06:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0054_delete_evaluationaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="obfuscation_key",
            field=models.UUIDField(
                default=uuid.uuid4, null=True, verbose_name="Clé d'obfuscation"
            ),
        ),
    ]
