# Generated by Django 3.2.12 on 2022-03-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0054_alter_criterion_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='legend_md',
            field=models.TextField(blank=True, verbose_name='Legend'),
        ),
    ]
