# Generated by Django 4.2.27 on 2026-02-04 08:37
import uuid

from django.db import migrations

def gen_uuid(apps, schema_editor):
    Request = apps.get_model("evaluations", "Request")
    for row in Request.objects.all():
        row.obfuscation_key = uuid.uuid4()
        row.save(update_fields=["obfuscation_key"])

class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0055_request_obfuscation_key"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
