# Generated by Django 3.2.12 on 2022-04-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0056_alter_evaluation_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='result_2',
            field=models.CharField(choices=[('soumis', 'Seuil franchi'), ('non_soumis', 'Seuil non franchi'), ('action_requise', 'Action requise')], max_length=32, null=True, verbose_name='Result'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='result_2',
            field=models.CharField(choices=[('soumis', 'Subject to LSE'), ('non_soumis', 'Non subject to LSE'), ('action_requise', 'Action required'), ('non_disponible', 'Non disponible')], max_length=32, null=True, verbose_name='Result'),
        ),
    ]
