# Generated by Django 4.2.27 on 2026-02-04 08:37
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0056_request_obfuscation_key_populate"),
    ]

    operations = [

        migrations.AlterField(
            model_name="request",
            name="obfuscation_key",
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, verbose_name="Clé d'obfuscation"
            ),
        ),
    ]
