# Generated by Django 4.2.28 on 2026-03-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0058_add_evaluation_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipientstatus",
            name="reject_reason",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Reject reason"
            ),
        ),
    ]
