# Generated by Django 3.2.12 on 2022-04-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0058_copy_result_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterion',
            name='result',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='result',
        ),
    ]
