# Generated by Django 4.2.28 on 2026-05-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0059_recipientstatus_reject_reason_default"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecipientStatus",
        ),
    ]
