# Generated by Django 3.2.12 on 2022-04-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0059_auto_20220419_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criterion',
            old_name='result_2',
            new_name='result',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='result_2',
            new_name='result',
        ),
    ]
