# Generated by Django 3.2.12 on 2022-05-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0056_alter_criterion_result'),
        ('evaluations', '0062_alter_evaluation_result'),
    ]

    operations = [
    ]
