# Generated by Django 3.2.12 on 2022-05-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0064_auto_20220517_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='user_type',
            field=models.CharField(choices=[('instructor', 'Un service instruction urbanisme'), ('petitioner', "Un porteur de projet ou maître d'œuvre")], default='instructor', max_length=32, verbose_name='Who are you?'),
        ),
    ]
