# Generated by Django 3.2.15 on 2022-11-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0068_alter_criterion_criterion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='moulinette_url',
            field=models.URLField(blank=True, verbose_name='Moulinette url'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='result',
            field=models.CharField(choices=[('soumis', 'Soumis'), ('non_soumis', 'Non soumis'), ('action_requise', 'Action requise'), ('non_disponible', 'Non disponible'), ('non_applicable', 'Non applicable'), ('non_concerne', 'Non concerné')], max_length=32, null=True, verbose_name='Result'),
        ),
    ]
