# Generated by Django 3.2.15 on 2022-12-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0069_auto_20221125_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='moulinette_url',
            field=models.URLField(blank=True, verbose_name='Moulinette url'),
        ),
    ]
