# Generated by Django 3.2.16 on 2022-12-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0070_request_moulinette_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='contact_md',
            field=models.TextField(blank=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='moulinette_url',
            field=models.URLField(blank=True, max_length=1024, verbose_name='Moulinette url'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='result',
            field=models.CharField(choices=[('soumis', 'Soumis'), ('non_soumis', 'Non soumis'), ('action_requise', 'Action requise'), ('non_disponible', 'Non disponible'), ('cas_par_cas', 'Cas par cas'), ('systematique', 'Soumis'), ('non_applicable', 'Non applicable'), ('non_concerne', 'Non concerné'), ('clause_filet', 'Clause filet')], max_length=32, null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='request',
            name='moulinette_url',
            field=models.URLField(blank=True, max_length=1024, verbose_name='Moulinette url'),
        ),
    ]
