# Generated by Django 3.2.16 on 2023-03-03 08:13

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0071_auto_20221215_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='moulinette_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Moulinette metadata'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='application_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='The application number format is invalid.', regex='^(PC|PA|DP|CU)(?P<department>\\d{3})(?P<commune>\\d{3})(?P<year>\\d{2})(?P<file>[\\w\\d]{5})$')], verbose_name='Application number'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='result',
            field=models.CharField(choices=[('soumis', 'Soumis'), ('non_soumis', 'Non soumis'), ('action_requise', 'Action requise'), ('non_disponible', 'Non disponible'), ('cas_par_cas', 'Cas par cas'), ('systematique', 'Soumis'), ('non_applicable', 'Non applicable'), ('non_concerne', 'Non concerné'), ('a_verifier', 'À vérifier'), ('iota_a_verifier', "En cas de dossier Loi sur l'eau")], max_length=32, null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='request',
            name='application_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='The application number format is invalid.', regex='^(PC|PA|DP|CU)(?P<department>\\d{3})(?P<commune>\\d{3})(?P<year>\\d{2})(?P<file>[\\w\\d]{5})$')], verbose_name='Application number'),
        ),
    ]
