# Generated by Django 3.2.16 on 2023-03-03 08:17

from django.db import migrations
from urllib.parse import urlparse
from django.http import QueryDict


def params_from_url(url):
    """Extract query string from url and return a dict."""

    url = urlparse(url)
    params = QueryDict(url.query)
    return params.dict()


def save_moulinette_data(apps, schema_editor):
    Evaluation = apps.get_model("evaluations", "Evaluation")
    for evaluation in Evaluation.objects.all():
        evaluation.moulinette_data = params_from_url(evaluation.moulinette_url)
        evaluation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0072_auto_20230303_0813'),
    ]

    operations = [
        migrations.RunPython(save_moulinette_data),
    ]
