# Generated by Django 3.2.12 on 2022-05-24 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128, verbose_name='Category')),
                ('event', models.CharField(max_length=128, verbose_name='Event')),
                ('session_key', models.CharField(max_length=40, verbose_name='Session key')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', 'event'], name='analytics_e_categor_167957_idx'),
        ),
    ]
