# Generated by Django 3.2.16 on 2023-02-17 14:13
import json
from django.db import migrations

def migrate_formsubmit_metadata(apps, schema_editor):
    Event = apps.get_model("analytics", "Event")
    events = Event.objects.filter(category="FeedbackDialog", event="Respond")

    for event in events:
        data = event.metadata
        if 'data' in data:
            event.metadata = {'feedback': data['data']}
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_formsubmit_metadata, migrations.RunPython.noop),
    ]
