# Generated by Django 4.2 on 2024-01-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_event_analytics_e_session_5d031e_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="session_key",
            field=models.CharField(max_length=128, verbose_name="Session key"),
        ),
    ]
