# Generated by Django 4.2.23 on 2025-10-02 07:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_add_haie"),
        ("analytics", "0005_event_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSPReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.JSONField(verbose_name="Content")),
                (
                    "session_key",
                    models.CharField(max_length=128, verbose_name="Session key"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date created"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sites.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "CSP report",
                "verbose_name_plural": "CSP reports",
            },
        ),
    ]
