# Generated by Django 4.2.23 on 2025-12-09 05:26

from django.db import migrations


def edit_events(apps, schema_editor):
    Event = apps.get_model("analytics", "Event")
    count = Event.objects.filter(
        category="projet",
        event="consultation"
    ).update(category="simulateur")

    print(f"projet > consultation → simulateur > consultation: {count} events updated")

    count = Event.objects.filter(
        category="dossier",
        event="creation"
    ).update(category="demande")

    print(f"dossier > creation → demande > creation: {count} events updated")

    count = Event.objects.filter(
        category="dossier",
        event="depot"
    ).update(category="demande")

    print(f"dossier > depot → demande > depot: {count} events updated")

    count = Event.objects.filter(
        category="projet",
        event="consultation_i"
    ).update(category="dossier", event="consultation")

    print(f"projet > consultation_i → dossier > consultation: {count} events updated")

    count = Event.objects.filter(
        category="projet",
        event="invitation"
    ).update(category="dossier")

    print(f"projet > invitation → dossier > invitation: {count} events updated")

    count = Event.objects.filter(
        category="projet",
        event="edition_notes"
    ).update(category="dossier")

    print(f"projet > edition_notes → dossier > edition_notes: {count} events updated")

    count = Event.objects.filter(
        category="projet",
        event="simulation_alt"
    ).update(category="dossier")

    print(f"projet > simulation_alt → dossier > simulation_alt: {count} events updated")

    count = Event.objects.filter(
        category="projet",
        event="modification_statut"
    ).update(category="dossier", event="modification_etat")

    print(f"projet > modification_statut → dossier > modification_etat: {count} events updated")

    count = Event.objects.filter(
        category="projet",
        event="suivi"
    ).update(category="dossier")

    print(f"projet > suivi → dossier > suivi: {count} events updated")

    count = Event.objects.filter(
        category="projet",
        event="suspension_delai"
    ).update(category="dossier")

    print(f"projet > suspension_delai → dossier > suspension_delai: {count} events updated")


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0006_cspreport"),
    ]


    operations = [
        migrations.RunPython(edit_events, migrations.RunPython.noop)
    ]

