# Generated by Django 4.2.23 on 2025-12-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_auto_20251209_0626"),
        ("analytics", "0007_repopulate_evaluation_visit"),
    ]

    operations = []
