# Generated by Django 4.2.27 on 2026-02-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0008_merge_20251215_1042"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="unique_id",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="ID unique"
            ),
        ),
    ]
