query getDossier($dossierNumber: Int!) {
  dossier(number: $dossierNumber) {
    id
    number
    state
    dateDepot
    usager {
      email
    }
    demandeur {
      ... on PersonnePhysique {
        civilite
        nom
        prenom
        email
      }
    }
    champs {
      id
      label
      stringValue
    }
    demarche {
      title
      number
    }
  }
}
